### ISSUE TITLE
NPE Crash with certain plank types

### ISSUE THREAD

**Issue by twothe** [ForestryMC/ForestryMC#1050]
When using the OpenComputers Disassembler that can "uncraft" items, it can generate planks that cause an instant client crash when the game attempts to render them.

```
Description: Rendering item

java.lang.NullPointerException: Rendering item
  at forestry.arboriculture.render.IconProviderWood.getPlankIcon(IconProviderWood.java:43)
  at forestry.arboriculture.render.RenderPlankItem.renderItem(RenderPlankItem.java:73)
  at forestry.arboriculture.render.RenderPlankItem.renderItem(RenderPlankItem.java:57)
  at net.minecraftforge.client.ForgeHooksClient.renderInventoryItem(ForgeHooksClient.java:183)
  at net.minecraft.client.renderer.entity.RenderItem.func_82406_b(RenderItem.java:563)
  at codechicken.nei.guihook.GuiContainerManager.drawSlotItem(GuiContainerManager.java:489)
  at net.minecraft.client.gui.inventory.GuiContainer.func_146977_a(GuiContainer.java:270)
  at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:99)
  at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1358)
  at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
  at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
  at net.minecraft.client.main.Main.main(SourceFile:148)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  at java.lang.reflect.Method.invoke(Unknown Source)
  at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
  at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by mezz** [comment]
Thanks for the report!
I'm pretty sure this is a similar issue to https://github.com/ForestryMC/ForestryMC/issues/1043

Please try with the latest dev version of Forestry here http://jenkins.ic2.player.to/job/Forestry_Dev/
    forestry_1.7.10-4.2.5.876-unstable.jar
Let me know if that fixes the issue.

**Comment by mezz** [comment]
@twothe any luck?

**Comment by twothe** [comment]
No time to test it so far, the week is packed with annoying stuff. ;)

**Comment by ghost** [comment]
It might be planks that are above ID 15? I get a crash when trying to add them to the microblock list (those planks/logs above ID 15) because of a getHardness method or some such. I can post a separate issue if its unrelated/of interest. Logs also break at the speed of obsidian when in microblock from as well.

**Comment by twothe** [comment]
The latest version fixed the issue. Thank you!
