### ISSUE TITLE
Forestry and Openblocks render conflict.

### ISSUE THREAD

**Issue by Laniid** [ForestryMC/ForestryMC#1058]
Forestry 4.2.5

**No crash in latest version 4.2.7**

The Render conflict happens when the Openblocks manual book is opened to page 31-32 containing the 'Vacuum Hopper' and 'Village highlighter'. Both items can be viewed and placed within the world without a crash. My assumption is that the cycling crafting recipe is showing a glitched plank from Forestry, This only appears to happen with the book so maybe the book is coded to use all planks even those without render? Manual solution?

``````
`Description: Rendering item

java.lang.NullPointerException: Rendering item
    at forestry.arboriculture.render.IconProviderWood.getPlankIcon(IconProviderWood.java:43)
    at forestry.arboriculture.render.RenderPlankItem.renderItem(RenderPlankItem.java:73)
    at forestry.arboriculture.render.RenderPlankItem.renderItem(RenderPlankItem.java:57)
    at net.minecraftforge.client.ForgeHooksClient.renderInventoryItem(ForgeHooksClient.java:183)
    at net.minecraft.client.renderer.entity.RenderItem.func_82406_b(RenderItem.java:563)
    at openmods.gui.component.BaseComponent.drawItemStack(BaseComponent.java:189)
    at openmods.gui.component.GuiComponentCraftingGrid.render(GuiComponentCraftingGrid.java:85)
    at openmods.gui.component.BaseComposite.render(BaseComposite.java:56)
    at openmods.gui.component.BaseComposite.render(BaseComposite.java:56)
    at openmods.gui.ComponentGui.func_146976_a(ComponentGui.java:66)
    at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:78)
    at openmods.gui.ComponentGui.func_73863_a(ComponentGui.java:77)
    at openblocks.client.gui.GuiInfoBook.func_73863_a(GuiInfoBook.java:226)
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stack trace
    at forestry.arboriculture.render.IconProviderWood.getPlankIcon(IconProviderWood.java:43)
    at forestry.arboriculture.render.RenderPlankItem.renderItem(RenderPlankItem.java:73)
    at forestry.arboriculture.render.RenderPlankItem.renderItem(RenderPlankItem.java:57)
    at net.minecraftforge.client.ForgeHooksClient.renderInventoryItem(ForgeHooksClient.java:183)

-- Item being rendered --
Details:
    Item Type: forestry.arboriculture.items.ItemBlockWood@4310e6a3
    Item Aux: 32767
    Item NBT: null
    Item Foil: false
Stack trace
    at net.minecraft.client.renderer.entity.RenderItem.func_82406_b(RenderItem.java:563)
    at openmods.gui.component.BaseComponent.drawItemStack(BaseComponent.java:189)
    at openmods.gui.component.GuiComponentCraftingGrid.render(GuiComponentCraftingGrid.java:85)
    at openmods.gui.component.BaseComposite.render(BaseComposite.java:56)
    at openmods.gui.component.BaseComposite.render(BaseComposite.java:56)
    at openmods.gui.ComponentGui.func_146976_a(ComponentGui.java:66)
    at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:78)
    at openmods.gui.ComponentGui.func_73863_a(ComponentGui.java:77)
    at openblocks.client.gui.GuiInfoBook.func_73863_a(GuiInfoBook.java:226)

-- Screen render details --
Details:
    Screen name: openblocks.client.gui.GuiInfoBook
    Mouse location: Scaled: (385, 90). Absolute: (770, 298)
    Screen size: Scaled: (427, 240). Absolute: (854, 480). Scale factor of 2

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityClientPlayerMP['butbut'/137, l='MpServer', x=231.80, y=71.62, z=3.29]]
    Chunk stats: MultiplayerChunkCache: 603, 603
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: World: (-232,64,140), Chunk: (at 8,4,12 in -15,8; contains blocks -240,0,128 to -225,255,143), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
    Level time: 29119 game time, 79780 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
    Forced entities: 53 total; [EntityBat['Bat'/5249, l='MpServer', x=240.75, y=58.10, z=-14.50], EntityClientPlayerMP['butbut'/137, l='MpServer', x=231.80, y=71.62, z=3.29], EntityChicken['Chicken'/144, l='MpServer', x=204.56, y=64.00, z=-16.56], EntitySheep['Sheep'/146, l='MpServer', x=183.34, y=69.00, z=-18.44], EntityItem['item.item.feather'/147, l='MpServer', x=187.19, y=70.13, z=-36.13], EntityItem['item.item.chickenRaw'/148, l='MpServer', x=188.50, y=70.13, z=-35.06], EntityChicken['Chicken'/149, l='MpServer', x=231.44, y=68.00, z=-41.34], EntitySheep['Sheep'/155, l='MpServer', x=213.50, y=70.00, z=-62.50], EntitySheep['Sheep'/156, l='MpServer', x=215.50, y=70.00, z=-61.50], EntitySheep['Sheep'/157, l='MpServer', x=215.50, y=70.00, z=-60.03], EntitySheep['Sheep'/158, l='MpServer', x=215.50, y=70.00, z=-62.97], EntitySheep['Sheep'/159, l='MpServer', x=217.03, y=71.00, z=0.67], EntitySheep['Sheep'/160, l='MpServer', x=228.84, y=70.00, z=-12.94], EntitySheep['Sheep'/168, l='MpServer', x=255.50, y=71.00, z=-57.50], EntitySheep['Sheep'/169, l='MpServer', x=255.94, y=71.00, z=-59.09], EntitySheep['Sheep'/170, l='MpServer', x=254.50, y=70.00, z=-63.91], EntitySheep['Sheep'/171, l='MpServer', x=250.03, y=69.00, z=13.09], EntityBat['Bat'/6955, l='MpServer', x=308.25, y=37.63, z=-48.09], EntityBat['Bat'/6957, l='MpServer', x=301.34, y=40.67, z=-60.27], EntitySheep['Sheep'/176, l='MpServer', x=257.50, y=72.00, z=3.28], EntityChicken['Chicken'/177, l='MpServer', x=228.56, y=69.00, z=33.47], EntitySheep['Sheep'/178, l='MpServer', x=253.97, y=68.00, z=25.97], EntityItem['item.Robot'/7477, l='MpServer', x=226.94, y=70.13, z=5.06], EntitySheep['Sheep'/182, l='MpServer', x=258.50, y=71.00, z=-56.50], EntitySheep['Sheep'/183, l='MpServer', x=262.34, y=68.00, z=19.44], EntityItem['item.Robot'/7480, l='MpServer', x=226.31, y=70.13, z=5.16], EntityBat['Bat'/7097, l='MpServer', x=288.54, y=62.09, z=-68.75], EntitySheep['Sheep'/186, l='MpServer', x=260.78, y=65.00, z=16.22], EntitySheep['Sheep'/187, l='MpServer', x=256.06, y=68.00, z=20.97], EntitySheep['Sheep'/188, l='MpServer', x=260.66, y=65.00, z=18.03], EntitySheep['Sheep'/189, l='MpServer', x=222.09, y=73.00, z=60.63], EntitySheep['Sheep'/190, l='MpServer', x=224.91, y=73.00, z=60.63], EntitySheep['Sheep'/191, l='MpServer', x=226.63, y=75.00, z=51.53], EntityItem['item.tile.oc.switch'/6464, l='MpServer', x=221.22, y=70.13, z=1.19], EntityItem['item.tile.oc.hologram1'/6337, l='MpServer', x=221.28, y=70.13, z=1.59], EntityItem['item.tile.oc.keyboard'/6472, l='MpServer', x=221.31, y=70.13, z=1.41], EntitySheep['Sheep'/202, l='MpServer', x=224.38, y=73.00, z=64.75], EntitySheep['Sheep'/203, l='MpServer', x=284.50, y=65.00, z=43.50], EntitySheep['Sheep'/204, l='MpServer', x=285.94, y=65.00, z=34.16], EntityItem['item.tile.oc.capacitor'/6350, l='MpServer', x=221.16, y=70.13, z=1.66], EntitySquid['Squid'/4435, l='MpServer', x=206.03, y=60.00, z=-27.81], EntitySquid['Squid'/4436, l='MpServer', x=207.75, y=60.00, z=-42.09], EntityItem['item.tile.oc.printer'/6484, l='MpServer', x=221.25, y=70.13, z=1.00], EntitySheep['Sheep'/214, l='MpServer', x=284.13, y=65.00, z=49.06], EntityItem['item.tile.oc.redstone'/6491, l='MpServer', x=221.19, y=70.13, z=1.59], EntitySheep['Sheep'/220, l='MpServer', x=288.78, y=64.00, z=44.91], EntityBat['Bat'/7393, l='MpServer', x=176.52, y=59.33, z=6.75], EntityItem['item.tile.oc.microcontroller'/6498, l='MpServer', x=221.28, y=70.13, z=1.03], EntityBat['Bat'/7394, l='MpServer', x=181.25, y=54.00, z=5.50], EntityBat['Bat'/7018, l='MpServer', x=187.75, y=50.07, z=69.75], EntityItem['item.tile.oc.accessPoint'/6514, l='MpServer', x=221.28, y=70.13, z=1.00], EntityBat['Bat'/4983, l='MpServer', x=291.44, y=48.10, z=-66.75], EntityBat['Bat'/6908, l='MpServer', x=183.93, y=24.82, z=73.03]]
    Retry entities: 0 total; []
    Server brand: dml,forge
    Server type: Integrated single player server
Stack trace
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Mac OS X (x86_64) version 10.11.2
    Java Version: 1.8.0_60, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 319547880 bytes (304 MB) / 1060372480 bytes (1011 MB) up to 1060372480 bytes (1011 MB)
    JVM Flags: 5 total; -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 96
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 75 mods loaded, 66 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
    UCHIJAAAA   FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
    UCHIJAAAA   Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
    UCHIJAAAA   appliedenergistics2-core{rv3-beta-5} [Applied Energistics 2 Core] (minecraft.jar) 
    UCHIJAAAA   CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
    UCHIJAAAA   NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
    UCHIJAAAA   OpenComputers|Core{1.5.22.43} [OpenComputers (Core)] (minecraft.jar) 
    UCHIJAAAA   OpenModsCore{0.9} [OpenModsCore] (minecraft.jar) 
    UCHIJAAAA   <CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
    UCHIJAAAA   appliedenergistics2{rv3-beta-5} [Applied Energistics 2] (appliedenergistics2-rv3-beta-5.jar) 
    UCHIJAAAA   CoFHCore{1.7.10R3.1.0} [CoFH Core] (CoFHCore-[1.7.10]3.1.0-323.jar) 
    UCHIJAAAA   ThermalFoundation{1.7.10R1.2.2} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.2-111.jar) 
    UCHIJAAAA   ThermalExpansion{1.7.10R4.1.1} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.1.1-237.jar) 
    UCHIJAAAA   BigReactors{0.4.3A} [Big Reactors] (BigReactors-0.4.3A.jar) 
    UCHIJAAAA   BuildCraft|Core{7.1.14} [BuildCraft] (buildcraft-7.1.14.jar) 
    UCHIJAAAA   BuildCraft|Builders{7.1.14} [BC Builders] (buildcraft-7.1.14.jar) 
    UCHIJAAAA   BuildCraft|Transport{7.1.14} [BC Transport] (buildcraft-7.1.14.jar) 
    UCHIJAAAA   BuildCraft|Energy{7.1.14} [BC Energy] (buildcraft-7.1.14.jar) 
    UCHIJAAAA   BuildCraft|Silicon{7.1.14} [BC Silicon] (buildcraft-7.1.14.jar) 
    UCHIJAAAA   BuildCraft|Robotics{7.1.14} [BC Robotics] (buildcraft-7.1.14.jar) 
    UCHIJAAAA   BuildCraft|Factory{7.1.14} [BC Factory] (buildcraft-7.1.14.jar) 
    UCHIJAAAA   CarpentersBlocks{3.3.7} [Carpenter's Blocks] (Carpenter's Blocks v3.3.7 - MC 1.7.10.jar) 
    UCHIJAAAA   endercore{1.7.10-0.2.0.31_beta} [EnderCore] (EnderCore-1.7.10-0.2.0.31_beta.jar) 
    UCHIJAAAA   MineFactoryReloaded{1.7.10R2.8.1} [MineFactory Reloaded] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UCHIJAAAA   Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
    UCHIJAAAA   EnderIO{1.7.10-2.3.0.422_beta} [Ender IO] (EnderIO-1.7.10-2.3.0.422_beta.jar) 
    UCHIJAAAA   EnderStorage{1.4.7.38} [EnderStorage] (EnderStorage-1.7.10-1.4.7.38-universal.jar) 
    UCHIJAAAA   EnderZoo{1.7.10-1.0.15.32} [Ender Zoo] (EnderZoo-1.7.10-1.0.15.32.jar) 
    UCHIJAAAA   ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    UCHIJAAAA   ExtraUtilities{1.2.12} [Extra Utilities] (extrautilities-1.2.12.jar) 
    UCHIJAAAA   flansmod{4.10.0} [Flan's Mod] (Flans Mod-1.7.10-4.10.0.jar) 
    UCHIJAAAA   Forestry{4.2.5.53} [Forestry for Minecraft] (forestry_1.7.10-4.2.5.53.jar) 
    UCHIJAAAA   MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.1} [MFR Compat: Applied Energistics] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UCHIJAAAA   MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.1} [MFR Compat: BuildCraft] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UCHIJAAAA   MineFactoryReloaded|CompatForestry{1.7.10R2.8.1} [MFR Compat: Forestry] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UCHIJAAAA   MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.1} [MFR Compat: ForgeMicroblock] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UCHIJAAAA   MrTJPCoreMod{1.1.0.32} [MrTJPCore] (MrTJPCore-1.7.10-1.1.0.32-universal.jar) 
    UCHIJAAAA   ProjRed|Core{4.7.0pre10.93} [ProjectRed Core] (ProjectRed-1.7.10-4.7.0pre10.93-Base.jar) 
    UCHIJAAAA   ProjRed|Exploration{4.7.0pre10.93} [ProjectRed Exploration] (ProjectRed-1.7.10-4.7.0pre10.93-World.jar) 
    UCHIJAAAA   MineFactoryReloaded|CompatProjRed{1.7.10R2.8.1} [MFR Compat ProjectRed] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UCHIJAAAA   Railcraft{9.8.0.0} [Railcraft] (Railcraft_1.7.10-9.8.0.0.jar) 
    UCHIJAAAA   MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.1} [MFR Compat: Railcraft] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UCHIJAAAA   MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.1} [MFR Compat: Thermal Expansion] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UCHIJAAAA   MineFactoryReloaded|CompatVanilla{1.7.10R2.8.1} [MFR Compat: Vanilla] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UCHIJAAAA   NetherOres{1.7.10R2.3.1} [Nether Ores] (NetherOres-[1.7.10]2.3.1-22.jar) 
    UCHIJAAAA   OpenMods{0.9} [OpenMods] (OpenModsLib-1.7.10-0.9.jar) 
    UCHIJAAAA   OpenBlocks{1.5} [OpenBlocks] (OpenBlocks-1.7.10-1.5.jar) 
    UCHIJAAAA   ProjRed|Transmission{4.7.0pre10.93} [ProjectRed Transmission] (ProjectRed-1.7.10-4.7.0pre10.93-Integration.jar) 
    UCHIJAAAA   OpenComputers{1.5.22.43} [OpenComputers] (OpenComputers-MC1.7.10-1.5.22.43-universal.jar) 
    UCHIJAAAA   ProjRed|Compatibility{4.7.0pre10.93} [ProjectRed Compatibility] (ProjectRed-1.7.10-4.7.0pre10.93-Compat.jar) 
    UCHIJAAAA   ProjRed|Integration{4.7.0pre10.93} [ProjectRed Integration] (ProjectRed-1.7.10-4.7.0pre10.93-Integration.jar) 
    UCHIJAAAA   ProjRed|Fabrication{4.7.0pre10.93} [ProjectRed Fabrication] (ProjectRed-1.7.10-4.7.0pre10.93-Fabrication.jar) 
    UCHIJAAAA   ProjRed|Illumination{4.7.0pre10.93} [ProjectRed Illumination] (ProjectRed-1.7.10-4.7.0pre10.93-Lighting.jar) 
    UCHIJAAAA   RandomThings{2.2.4} [Random Things] (RandomThings-2.2.4.jar) 
    UCHIJAAAA   RedstoneArsenal{1.7.10R1.1.2} [Redstone Arsenal] (RedstoneArsenal-[1.7.10]1.1.2-92.jar) 
    UCHIJAAAA   rftools{4.21} [RFTools] (rftools-4.21.jar) 
    UCHIJAAAA   simplyjetpacks{1.5.3} [Simply Jetpacks] (SimplyJetpacks-MC1.7.10-1.5.3.jar) 
    UCHIJAAAA   StevesCarts{2.0.0.b18} [Steve's Carts 2] (StevesCarts2.0.0.b18.jar) 
    UCHIJAAAA   ThermalDynamics{1.7.10R1.1.0} [Thermal Dynamics] (ThermalDynamics-[1.7.10]1.1.0-161.jar) 
    UCHIJAAAA   Translocator{1.1.2.16} [Translocator] (Translocator-1.7.10-1.1.2.16-universal.jar) 
    UCHIJAAAA   weaponmod{v1.14.3} [Balkon's WeaponMod] (weaponmod-1.14.3.jar) 
    UCHIJAAAA   WR-CBE|Core{1.4.1.9} [WR-CBE Core] (WR-CBE-1.7.10-1.4.1.9-universal.jar) 
    UCHIJAAAA   WR-CBE|Addons{1.4.1.9} [WR-CBE Addons] (WR-CBE-1.7.10-1.4.1.9-universal.jar) 
    UCHIJAAAA   WR-CBE|Logic{1.4.1.9} [WR-CBE Logic] (WR-CBE-1.7.10-1.4.1.9-universal.jar) 
    UCHIJAAAA   McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    UCHIJAAAA   ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    UD  MineFactoryReloaded|CompatAtum{1.7.10R2.8.1} [MFR Compat: Atum] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UD  MineFactoryReloaded|CompatBackTools{1.7.10R2.8.1} [MFR Compat: BackTools] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UD  MineFactoryReloaded|CompatChococraft{1.7.10R2.8.1} [MFR Compat: Chococraft] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UD  MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.1} [MFR Compat: ExtraBiomes] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UD  MineFactoryReloaded|CompatIC2{1.7.10R2.8.1} [MFR Compat: IC2] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UD  MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.1} [MFR Compat: Sufficient Biomes] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UD  MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.1} [MFR Compat: Thaumcraft] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UD  MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.1} [MFR Compat: Tinkers' Construct] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UD  MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.1} [MFR Compat: TwilightForest] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    GL info: ' Vendor: 'ATI Technologies Inc.' Version: '2.1 ATI-1.40.15' Renderer: 'AMD Radeon HD 6750M OpenGL Engine'
    OpenModsLib class transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[map_gen_fix:FINISHED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
    Class transformer null safety: all safe
    AE2 Version: beta rv3-beta-5 for Forge 10.13.4.1448
    CoFHCore: -[1.7.10]3.1.0-323
    ThermalFoundation: -[1.7.10]1.2.2-111
    ThermalExpansion: -[1.7.10]4.1.1-237
    MineFactoryReloaded: -[1.7.10]2.8.1-174
    NetherOres: -[1.7.10]2.3.1-22
    RedstoneArsenal: -[1.7.10]1.1.2-92
    ThermalDynamics: -[1.7.10]1.1.0-161
    EnderIO: Found the following problem(s) with your installation:
                  * An unknown AE2 API is installed (rv3 from appliedenergistics2-rv3-beta-5.jar).
                    Ender IO was build against API version rv2 and my not work with newer version.
                  * The RF API that is being used (1.7.10R1.1.0 from <unknown>) differes from that that is reported as being loaded (1.7.10R1.0.2 from forestry_1.7.10-4.2.5.53.jar).
                    It is a supported version, but that difference may lead to problems.
                 This may have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
    Stencil buffer state: Function set: ARB, pool: forge, bits: 8
    AE2 Integration: IC2:OFF, RotaryCraft:OFF, RC:ON, BuildCraftCore:ON, BuildCraftTransport:ON, BuildCraftBuilder:ON, RF:ON, RFItem:ON, MFR:ON, DSU:ON, FZ:OFF, FMP:ON, RB:OFF, CLApi:OFF, Waila:ON, InvTweaks:OFF, NEI:ON, CraftGuide:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF, OpenComputers:ON, PneumaticCraft:OFF
    Launched Version: 1.7.10-Forge10.13.4.1614-1.7.10
    LWJGL: 2.9.1
    OpenGL: AMD Radeon HD 6750M OpenGL Engine GL version 2.1 ATI-1.40.15, ATI Technologies Inc.
    GL Caps: Using GL 1.3 multi texturing
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

    Is Modded: Definitely; Client brand changed to 'dml,forge'
    Type: Client (map_client.txt)
    Resource Packs: []
    Current Language: English (US)
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Anisotropic Filtering: Off (1)`
```.:::
``````

**Comment by mezz** [comment]
Thanks for the report!
Please try with the latest version of Forestry. I think this is the same issue as #1043.

**Comment by Laniid** [comment]
~~Sorry, I should have put the version number. This is the latest 4.2.7~~

Was indeed 4.2.5

**Comment by mezz** [comment]
The crash log shows 4.2.5

**Comment by Laniid** [comment]
My apologies, upon second inspection it appears I somehow failed to download the latest version. 4.2.7 works and there is no crash.

**Comment by mezz** [comment]
Thanks, glad that fixes it!
