### ISSUE TITLE
a problem that spent three days

### ISSUE THREAD

**Issue by naluisio** [ForestryMC/ForestryMC#1064]
Was using version 3.xx "Forestry" and my giga-world, I tried to update it, and there was conflict with "Bibliocraft (Forestry)," uninstalled noticed all backups, cleaned settings, organized the folder "Forge", summarizing did the necessary. But in a new attempt when I put the "Forestry 4.xx" all my world changed blocks to others even blocks of my hand, conflict of "ID" can only, from to play for a minute or less and! CRASH world!.
If someone can teach me to solve'm totally willing to learn and pass on everything you can to solve similar cases, I'm not asking for help without first trying to solve a lot and always looking, but a major barrier and poor English.

**Comment by mezz** [comment]
Block ID conflicts should not be possible in 1.7.10. Something is broken with your world, but it is not possible for Bibliocraft or Forestry to cause it.

You should use your backup, and remove "Bibliowoods for Forestry". It should work.

Bibliowoods for Forestry does not work with Forestry 4.xx. It is not updated because it is not needed any more. You can use the [Bibliocraft "Furniture Paneler"](http://www.bibliocraftmod.com/wiki/furniture-paneler/) to make wood items from Forestry planks.

**Comment by naluisio** [comment]
i run to test now!

**Comment by naluisio** [comment]
I am no longer "Bibliocraft" ID conflict occurs without the "Bibliocraft" installed, removed it was unnecessary after my last "inssue" which received a divine help.
  For now I'm "Forestry4" off hoping to find solution.

**Comment by naluisio** [comment]
More info 
The steps performed
- Removed the forge folder
- Removed the bibliocraft mod and addons
- Removed old Forestry
- I put Forestry 4
  
  What happens: lately after many changes, "MC" predisposes to make a auto backup in charge of my world reporting corruption in level.dat and off the game.
  
  error second Openeye:

` java.lang.InstantiationException: com.mrdimka.soultech.tileentity.SolarPanelTileEntity

```
at java.lang.Class.newInstance(-1)
at net.minecraft.tileentity.TileEntity.func_145827_c(TileEntity.java:104)
at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:496)
at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:41)
at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:12)
at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:344)
at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302)
at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12)
at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:126)
at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101)
at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:265)
at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:130)
at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:153)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

Caused by..

java.lang.NoSuchMethodException: com.mrdimka.soultech.tileentity.SolarPanelTileEntity.<init>()

```
at java.lang.Class.getConstructor0(-1)´
```

**Comment by mezz** [comment]
Why did you remove the Forge folder? That doesn't sound like a good idea.

**Comment by naluisio** [comment]
One thing occurring since the beginning of the year, I can only open minecraft if I delete the mod "forgerealocation" and put a copy of which has never been used instead.

**Comment by naluisio** [comment]
I am close to the solution, "forge relocation" with this problem in my modpack soon have to delete every time I play to create a new file forge realocation and this process is preventing me from putting the "Forestry 4".

Its review this crash for me to figure out how to proceed? Follows.`---- Minecraft Crash Report ----
// Oh - I know what I did wrong!

Time: 2/9/16 11:06 PM
Description: Initializing game

java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    net/minecraft/client/renderer/RenderBlocks.func_147805_b(Lnet/minecraft/block/Block;III)Z @9: invokestatic
  Reason:
    Type integer (current frame, stack[3]) is not assignable to 'net/minecraft/block/Block'
  Current Frame:
    bci: @9
    flags: { }
    locals: { 'net/minecraft/client/renderer/RenderBlocks', 'net/minecraft/block/Block', integer, integer, integer }
    stack: { 'net/minecraft/block/Block', integer, integer, integer, integer, integer, integer }
  Bytecode:
    0x0000000: 2b1c 1d15 041c 1d15 04b8 00f7 3605 2ab4
    0x0000010: 0076 1c1d 1504 2b15 05b8 00fd 3605 1505
    0x0000020: 02a0 000f 032a 2b1c 1d15 04b8 0103 80ac
    0x0000030: 2b2a b400 761c 1d15 04b6 0107 b801 0a99
    0x0000040: 0023 2bb2 010f a600 1c2a 1c1d 1504 b601
    0x0000050: 1399 0011 2a1c 1d15 04b2 0116 b600 ccb6
    0x0000060: 011a 2a2b b601 1c15 05aa 0000 0000 0429
    0x0000070: 0000 0000 0000 0029 0000 00b7 0000 00f3
    0x0000080: 0000 011e 0000 01ec 0000 00cb 0000 0171
    0x0000090: 0000 01d8 0000 0217 0000 0203 0000 0199
    0x00000a0: 0000 022b 0000 0146 0000 0270 0000 0185
    0x00000b0: 0000 02ac 0000 02c0 0000 0305 0000 031a
    0x00000c0: 0000 032f 0000 01b0 0000 0132 0000 035a
    0x00000d0: 0000 0429 0000 01c4 0000 0371 0000 03b6
    0x00000e0: 0000 03cd 0000 0242 0000 03e4 0000 0284
    0x00000f0: 0000 0298 0000 00df 0000 0259 0000 0388
    0x0000100: 0000 03fb 0000 039f 0000 02d7 0000 02ee
    0x0000110: 0000 0412 0000 015d 0000 0107 0000 0346
    0x0000120: 2a2b 1c1d 1504 b601 1f2a 2b1c 1d15 04b8
    0x0000130: 0103 80ac 2a2b 1c1d 1504 b601 222a 2b1c
    0x0000140: 1d15 04b8 0103 80ac 2a2b 1c1d 1504 b601
    0x0000150: 252a 2b1c 1d15 04b8 0103 80ac 2a2b 1c1d
    0x0000160: 1504 b601 282a 2b1c 1d15 04b8 0103 80ac
    0x0000170: 2a2b c001 2a1c 1d15 04b6 012e 2a2b 1c1d
    0x0000180: 1504 b801 0380 ac2a 2b1c 1d15 04b6 0131
    0x0000190: 2a2b 1c1d 1504 b801 0380 ac2a 2b1c 1d15
    0x00001a0: 04b6 0134 2a2b 1c1d 1504 b801 0380 ac2a
    0x00001b0: 2bc0 0136 1c1d 1504 b601 3a2a 2b1c 1d15
    0x00001c0: 04b8 0103 80ac 2a2b 1c1d 1504 b601 3d2a
    0x00001d0: 2b1c 1d15 04b8 0103 80ac 2a2b 1c1d 1504
    0x00001e0: b601 402a 2b1c 1d15 04b8 0103 80ac 2a2b
    0x00001f0: 1c1d 1504 b601 432a 2b1c 1d15 04b8 0103
    0x0000200: 80ac 2a2b c001 451c 1d15 04b6 0149 2a2b
    0x0000210: 1c1d 1504 b801 0380 ac2a 2b1c 1d15 04b6
    0x0000220: 014c 2a2b 1c1d 1504 b801 0380 ac2a 2b1c
    0x0000230: 1d15 04b6 014f 2a2b 1c1d 1504 b801 0380
    0x0000240: ac2a 2b1c 1d15 04b6 0152 2a2b 1c1d 1504
    0x0000250: b801 0380 ac2a 2bc0 0154 1c1d 1504 b601
    0x0000260: 582a 2b1c 1d15 04b8 0103 80ac 2a2b 1c1d
    0x0000270: 1504 b601 5b2a 2b1c 1d15 04b8 0103 80ac
    0x0000280: 2a2b 1c1d 1504 b601 5e2a 2b1c 1d15 04b8
    0x0000290: 0103 80ac 2a2b c001 601c 1d15 04b6 0164
    0x00002a0: 2a2b 1c1d 1504 b801 0380 ac2a 2bc0 0166
    0x00002b0: 1c1d 1504 b601 6a2a 2b1c 1d15 04b8 0103
    0x00002c0: 80ac 2a2b c001 6c1c 1d15 04b6 0170 2a2b
    0x00002d0: 1c1d 1504 b801 0380 ac2a 2b1c 1d15 04b6
    0x00002e0: 0173 2a2b 1c1d 1504 b801 0380 ac2a 2b1c
    0x00002f0: 1d15 04b6 0176 2a2b 1c1d 1504 b801 0380
    0x0000300: ac2a 2b1c 1d15 04b6 0179 2a2b 1c1d 1504
    0x0000310: b801 0380 ac2a 2b1c 1d15 04b6 017c 2a2b
    0x0000320: 1c1d 1504 b801 0380 ac2a 2bc0 017e 1c1d
    0x0000330: 1504 b601 822a 2b1c 1d15 04b8 0103 80ac
    0x0000340: 2a2b c001 841c 1d15 04b6 0188 2a2b 1c1d
    0x0000350: 1504 b801 0380 ac2a 2bc0 018a 1c1d 1504
    0x0000360: b601 8e2a 2b1c 1d15 04b8 0103 80ac 2a2b
    0x0000370: 1c1d 1504 03b6 0192 2a2b 1c1d 1504 b801
    0x0000380: 0380 ac2a 2b1c 1d15 0404 b601 952a 2b1c
    0x0000390: 1d15 04b8 0103 80ac 2a2b c001 971c 1d15
    0x00003a0: 04b6 019b 2a2b 1c1d 1504 b801 0380 ac2a
    0x00003b0: 2b1c 1d15 04b6 019e 2a2b 1c1d 1504 b801
    0x00003c0: 0380 ac2a 2bc0 01a0 1c1d 1504 b601 a42a
    0x00003d0: 2b1c 1d15 04b8 0103 80ac 2a2b c001 a61c
    0x00003e0: 1d15 04b6 01aa 2a2b 1c1d 1504 b801 0380
    0x00003f0: ac2a 2bc0 01ac 1c1d 1504 b601 b02a 2b1c
    0x0000400: 1d15 04b8 0103 80ac 2a2b c001 b21c 1d15
    0x0000410: 04b6 01b6 2a2b 1c1d 1504 b801 0380 ac2a
    0x0000420: 2bc0 01b8 1c1d 1504 b601 bc2a 2b1c 1d15
    0x0000430: 04b8 0103 80ac 2a2b c001 be1c 1d15 04b6
    0x0000440: 01c2 2a2b 1c1d 1504 b801 0380 ac2a 2bc0
    0x0000450: 01c4 1c1d 1504 b601 c82a 2b1c 1d15 04b8
    0x0000460: 0103 80ac 2a2b c001 ca1c 1d15 04b6 01ce
    0x0000470: 2a2b 1c1d 1504 b801 0380 ac2a 2bc0 01d0
    0x0000480: 1c1d 1504 b601 d42a 2b1c 1d15 04b8 0103
    0x0000490: 80ac b201 dab6 01df 9900 47b2 01e3 1007
    0x00004a0: bd00 0459 032a 5359 042a b400 7653 5905
    0x00004b0: 1cb8 01e9 5359 061d b801 e953 5907 1504
    0x00004c0: b801 e953 5908 2b53 5910 0615 05b8 01e9
    0x00004d0: 53b8 01ed 2a2b 1c1d 1504 b801 0380 acb2
    0x00004e0: 01f0 b601 df99 0047 b201 f310 07bd 0004
    0x00004f0: 5903 2a53 5904 2ab4 0076 5359 051c b801
    0x0000500: e953 5906 1db8 01e9 5359 0715 04b8 01e9
    0x0000510: 5359 082b 5359 1006 1505 b801 e953 b801
    0x0000520: ed2a 2b1c 1d15 04b8 0103 80ac 032a 2b1c
    0x0000530: 1d15 04b8 0103 80ac  
  Stackmap Table:
    append_frame(@48,Integer)
    same_frame(@98)
    same_frame_extended(@288)
    same_frame(@308)
    same_frame(@328)
    same_frame(@348)
    same_frame(@368)
    same_frame(@391)
    same_frame(@411)
    same_frame(@431)
    same_frame(@454)
    same_frame(@474)
    same_frame(@494)
    same_frame(@514)
    same_frame(@537)
    same_frame(@557)
    same_frame(@577)
    same_frame(@597)
    same_frame(@620)
    same_frame(@640)
    same_frame(@660)
    same_frame(@683)
    same_frame(@706)
    same_frame(@729)
    same_frame(@749)
    same_frame(@769)
    same_frame(@789)
    same_frame(@809)
    same_frame(@832)
    same_frame(@855)
    same_frame(@878)
    same_frame(@899)
    same_frame(@920)
    same_frame(@943)
    same_frame(@963)
    same_frame(@986)
    same_frame(@1009)
    same_frame(@1032)
    same_frame(@1055)
    same_frame(@1078)
    same_frame(@1101)
    same_frame(@1124)
    same_frame(@1147)
    same_frame(@1170)
    same_frame_extended(@1247)
    same_frame_extended(@1324)

```
at net.minecraft.client.renderer.entity.Render.<init>(SourceFile:26)
at net.minecraft.client.renderer.entity.RenderItem.<init>(RenderItem.java:46)
at net.minecraft.client.gui.achievement.GuiAchievement.<init>(SourceFile:29)
at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:469)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
at net.minecraft.client.main.Main.main(SourceFile:148)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:273)
at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:363)
at org.multimc.EntryPoint.listen(EntryPoint.java:165)
at org.multimc.EntryPoint.main(EntryPoint.java:54)
```

## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at net.minecraft.client.renderer.entity.Render.<init>(SourceFile:26)
    at net.minecraft.client.renderer.entity.RenderItem.<init>(RenderItem.java:46)
    at net.minecraft.client.gui.achievement.GuiAchievement.<init>(SourceFile:29)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:469)

-- Initialization --
Details:
Stacktrace:
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:273)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:363)
    at org.multimc.EntryPoint.listen(EntryPoint.java:165)
    at org.multimc.EntryPoint.main(EntryPoint.java:54)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.8.0_73, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 824988928 bytes (786 MB) / 1589641216 bytes (1516 MB) up to 2863661056 bytes (2731 MB)
    JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms1024m -Xmx3072m
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: 
    Launched Version: 1.7.10
    LWJGL: 2.9.1
    OpenGL: AMD Radeon HD 6670 GL version 4.5.13399 Compatibility Profile Context 15.200.1062.1004, ATI Technologies Inc.
    GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

```
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: []
Current Language: ~~ERROR~~ NullPointerException: null
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Anisotropic Filtering: Off (1)`
```

**Comment by mezz** [comment]
I'm sorry, I have never seen an error like this and I have no idea what you are doing.

**Comment by naluisio** [comment]
ho tanks

**Comment by naluisio** [comment]
Bingo! Mod "thus mod beta" its make problem in forge realocation and sequentile broken ids in ut forestry 4

reply in minuts!

**Comment by mezz** [comment]
???

**Comment by naluisio** [comment]
I found a mod called truss he was giving crash was an old problem that I had to clean the forge all the time folder, but still when I put Forestry4 he keeps changing the blocks already created world awaiting solution in some of reported forums.
