### ISSUE TITLE
Forestry 1.7.10 stable has thrown an exception during loading

### ISSUE THREAD

**Issue by vulunijo** [ForestryMC/ForestryMC#1128]
I m using thermos last build + last stable forestry and sometimes get this error in server log:

```
A TileEntity forestry.AlvearySwarmer(forestry.apiculture.multiblock.TileAlvearySwarmer) has thrown an exception during loading, its state cannot be restored. Report this to the mod author
java.lang.NullPointerException
    at forestry.apiculture.multiblock.TileAlvearySwarmer.setActive(TileAlvearySwarmer.java:218) ~[TileAlvearySwarmer.class:?]
    at forestry.apiculture.multiblock.TileAlvearySwarmer.func_145839_a(TileAlvearySwarmer.java:178) ~[TileAlvearySwarmer.class:?]
    at net.minecraft.tileentity.TileEntity.func_145827_c(TileEntity.java:125) [aor.class:?]
    at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:525) [aqk.class:?]
    at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:44) [ChunkIOProvider.class:1.7.10-1614.54]
    at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:15) [ChunkIOProvider.class:1.7.10-1614.54]
    at net.minecraftforge.common.util.AsynchronousExecutor$Task.finish(AsynchronousExecutor.java:189) [AsynchronousExecutor$Task.class:1.7.10-1614.54]
    at net.minecraftforge.common.util.AsynchronousExecutor.finishActive(AsynchronousExecutor.java:354) [AsynchronousExecutor.class:1.7.10-1614.54]
    at net.minecraftforge.common.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:30) [ChunkIOExecutor.class:1.7.10-1614.54]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:907) [MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:831) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:683) [MinecraftServer.class:?]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
```

**Comment by Bogdan-G** [comment]
meh, you write scant information, please more info (builds number/versions mods, mod list(server), full server log).

**Comment by mezz** [comment]
Thanks for the report!
Can you post the full crash log to https://gist.github.com ?

**Comment by mezz** [comment]
@vulunijo Can you post the full crash log to https://gist.github.com ?
