### ISSUE TITLE
Minecraft 1.8.9 crash with buildcraft + forestry

### ISSUE THREAD

**Issue by admincheg** [ForestryMC/ForestryMC#1130]
Minecraft crash when i put pump, engine and lever.

[09:28:09] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking block entity
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:707) ~[MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605) ~[MinecraftServer.class:?]
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:152) ~[bpo.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481) [MinecraftServer.class:?]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_92]
Caused by: java.lang.NoSuchMethodError: cofh.api.energy.IEnergyConnection.canConnectEnergy(Lnet/minecraft/util/EnumFacing;)Z
    at buildcraft.core.lib.engines.TileEngineBase.isPoweredTile(TileEngineBase.java:469) ~[TileEngineBase.class:?]
    at buildcraft.core.lib.engines.TileEngineBase.switchOrientationDo(TileEngineBase.java:342) ~[TileEngineBase.class:?]
    at buildcraft.core.lib.engines.TileEngineBase.switchOrientation(TileEngineBase.java:332) ~[TileEngineBase.class:?]
    at buildcraft.core.lib.engines.TileEngineBase.func_73660_a(TileEngineBase.java:194) ~[TileEngineBase.class:?]
    at net.minecraft.world.World.func_72939_s(World.java:1718) ~[adm.class:?]
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:545) ~[le.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:701) ~[MinecraftServer.class:?]
    ... 4 more
[09:28:09] [Server thread/ERROR]: This crash report has been saved to: E:\multimc\instances\test\minecraft\crash-reports\crash-2016-04-22_09.28.09-server.txt
[09:28:09] [Server thread/INFO]: Stopping server
[09:28:09] [Server thread/INFO]: Saving players
[09:28:09] [Client thread/INFO]: [net.minecraft.init.Bootstrap:func_179870_a:529]: ---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// Ouch. That hurt :(

Time: 4/22/16 9:28 AM
Description: Ticking block entity

java.lang.NoSuchMethodError: cofh.api.energy.IEnergyConnection.canConnectEnergy(Lnet/minecraft/util/EnumFacing;)Z
    at buildcraft.core.lib.engines.TileEngineBase.isPoweredTile(TileEngineBase.java:469)
    at buildcraft.core.lib.engines.TileEngineBase.switchOrientationDo(TileEngineBase.java:342)
    at buildcraft.core.lib.engines.TileEngineBase.switchOrientation(TileEngineBase.java:332)
    at buildcraft.core.lib.engines.TileEngineBase.func_73660_a(TileEngineBase.java:194)
    at net.minecraft.world.World.func_72939_s(World.java:1718)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:545)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:701)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:152)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
    at java.lang.Thread.run(Unknown Source)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at buildcraft.core.lib.engines.TileEngineBase.isPoweredTile(TileEngineBase.java:469)
    at buildcraft.core.lib.engines.TileEngineBase.switchOrientationDo(TileEngineBase.java:342)
    at buildcraft.core.lib.engines.TileEngineBase.switchOrientation(TileEngineBase.java:332)
    at buildcraft.core.lib.engines.TileEngineBase.func_73660_a(TileEngineBase.java:194)

-- Block entity being ticked --
Details:
    Name: buildcraft.core.engine.wood // buildcraft.core.TileEngineWood
    Block type: ID #200 (tile.engineBlock // buildcraft.core.BlockEngine)
    Block data value: 0 / 0x0 / 0b0000
    Block location: World: (-92,67,248), Chunk: (at 4,4,8 in -6,15; contains blocks -96,0,240 to -81,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
    Actual block type: ID #200 (tile.engineBlock // buildcraft.core.BlockEngine)
    Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
    at net.minecraft.world.World.func_72939_s(World.java:1718)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:545)

-- Affected level --
Details:
    Level name: New World44
    All players: 1 total; [EntityPlayerMP['<PROFILE NAME>'/1400, l='New World44', x=-89.84, y=67.00, z=247.32]]
    Chunk stats: ServerChunkCache: 672 Drop: 0
    Level seed: -2897356788910223115
    Level generator: ID 00 - default, ver 1. Features enabled: true
    Level generator options: 
    Level spawn location: -83.00,64.00,258.00 - World: (-83,64,258), Chunk: (at 13,4,2 in -6,16; contains blocks -96,0,256 to -81,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
    Level time: 398 game time, 398 day time
    Level dimension: 0
    Level storage version: 0x04ABD - Anvil
    Level weather: Rain time: 155020 (now: false), thunder time: 34175 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:701)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:152)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
    at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
    Minecraft Version: 1.8.9
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.8.0_92, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 2695588128 bytes (2570 MB) / 4110417920 bytes (3920 MB) up to 4110417920 bytes (3920 MB)
    JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms4096m -Xmx4096m
    IntCache: cache: 3, tcache: 0, allocated: 12, tallocated: 96
    FML: MCP 9.19 Powered by Forge 11.15.1.1764 13 mods loaded, 13 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{8.0.99.99} [Forge Mod Loader](forge-1.8.9-11.15.1.1764-universal.jar) 
    UCHIJAAAA   Forge{11.15.1.1764} [Minecraft Forge](forge-1.8.9-11.15.1.1764-universal.jar) 
    UCHIJAAAA   BuildCraft|Core{7.2.5} [BuildCraft](buildcraft-7.2.5.jar) 
    UCHIJAAAA   BuildCraft|Silicon{7.2.5} [BC Silicon](buildcraft-7.2.5.jar) 
    UCHIJAAAA   BuildCraft|Transport{7.2.5} [BC Transport](buildcraft-7.2.5.jar) 
    UCHIJAAAA   BuildCraft|Builders{7.2.5} [BC Builders](buildcraft-7.2.5.jar) 
    UCHIJAAAA   BuildCraft|Energy{7.2.5} [BC Energy](buildcraft-7.2.5.jar) 
    UCHIJAAAA   BuildCraft|Robotics{7.2.5} [BC Robotics](buildcraft-7.2.5.jar) 
    UCHIJAAAA   BuildCraft|Factory{7.2.5} [BC Factory](buildcraft-7.2.5.jar) 
    UCHIJAAAA   BuildCraft|Compat{7.2.1} [BuildCraft Compat](buildcraft-compat-7.2.1.jar) 
    UCHIJAAAA   reborncore{1.5.1.57} [RebornCore](RebornCore-1.8.9-1.5.1.57-universal.jar) 
    UCHIJAAAA   Baubles{1.1.3.0} [Baubles](Baubles-1.8.9-1.1.3.0.jar) 
    Loaded coremods (and transformers): 
    GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
    Profiler Position: N/A (disabled)
    Player Count: 1 / 8; [EntityPlayerMP['<PROFILE NAME>'/1400, l='New World44', x=-89.84, y=67.00, z=247.32]]
    Type: Integrated Server (map_client.txt)
    Is Modded: Definitely; Client brand changed to 'fml,forge'

If I disable Forestry - engines work perfectly.

**Comment by Nedelosk** [comment]
![2016-04-29_21 25 54](https://cloud.githubusercontent.com/assets/10259214/14927241/f864855e-0e50-11e6-8f9b-2ece260f95d3.png)
