### ISSUE TITLE
[1.9.4] Forestry 5.0.9.143 Crash on Startup related to plugins.cfg lepidopterology

### ISSUE THREAD

**Issue by Gepett0** [ForestryMC/ForestryMC#1303]
Forge: *.1954
Mods: Just Forestry.143

Sorry if already reported, didn't find any issue related to 1.9.4.

With just Forestry (also in a modpack),
if I set

```
 B:forestry.lepidopterology=false
```

Minecraft crashes on Initialize with:

java.lang.NullPointerException: Initializing game
    at net.minecraftforge.client.model.ModelLoader.setCustomStateMapper(ModelLoader.java:1052)
    at forestry.core.proxy.ProxyRenderClient.registerStateMapper(ProxyRenderClient.java:160)
    at forestry.core.proxy.ProxyRenderClient.registerBlockModel(ProxyRenderClient.java:140)
    at forestry.greenhouse.proxy.ProxyGreenhouseClient.initializeModels(ProxyGreenhouseClient.java:37)
    at forestry.greenhouse.PluginGreenhouse.preInit(PluginGreenhouse.java:226)
    at forestry.plugins.PluginManager.runPreInit(PluginManager.java:231)
    at forestry.Forestry.preInit(Forestry.java:93)
        [...]

http://pastebin.com/2zdTPmgf

**Comment by Nedelosk** [comment]
Fixed in : cc53894473a73d9cb9464fa6ba54fa86b7805d6a
