### ISSUE TITLE
[1.7.10] game crashes with mekanism

### ISSUE THREAD

**Issue by ghost** [ForestryMC/ForestryMC#1424]
---- Minecraft Crash Report ----
// Sorry :(

Time: 9/11/16 12:41 AM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: mekanism/common/recipe/machines/SolarEvaporationRecipe
    at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:739)
    at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: mekanism/common/recipe/machines/SolarEvaporationRecipe
    at java.lang.Class.getDeclaredMethods0(Native Method)
    at java.lang.Class.privateGetDeclaredMethods(Class.java:2693)
    at java.lang.Class.privateGetPublicMethods(Class.java:2894)
    at java.lang.Class.getMethods(Class.java:1607)
    at stanhebben.zenscript.type.ZenTypeNative.complete(ZenTypeNative.java:157)
    at minetweaker.runtime.GlobalRegistry.registerNativeClass(GlobalRegistry.java:95)
    at minetweaker.MineTweakerAPI.registerClass(MineTweakerAPI.java:340)
    at modtweaker2.mods.mekanism.Mekanism.<init>(Mekanism.java:48)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
    at java.lang.Class.newInstance(Class.java:438)
    at modtweaker2.utils.TweakerPlugin.load(TweakerPlugin.java:18)
    at modtweaker2.utils.TweakerPlugin.register(TweakerPlugin.java:12)
    at modtweaker2.ModTweaker2.init(ModTweaker2.java:73)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
    at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:737)
    ... 10 more
Caused by: java.lang.ClassNotFoundException: mekanism.common.recipe.machines.SolarEvaporationRecipe
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 52 more
Caused by: java.lang.NullPointerException
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 608804504 bytes (580 MB) / 1736966144 bytes (1656 MB) up to 3817865216 bytes (3641 MB)
    JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m -XX:PermSize=256m
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 Optifine OptiFine_1.7.10_HD_U_C1 60 mods loaded, 60 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHI    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCHI    FML{7.10.99.99} [Forge Mod Loader](forge-1.7.10-10.13.4.1614-1.7.10.jar) 
    UCHI    Forge{10.13.4.1614} [Minecraft Forge](forge-1.7.10-10.13.4.1614-1.7.10.jar) 
    UCHI    appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core](minecraft.jar) 
    UCHI    Aroma1997Core{1.0.2.16} [Aroma1997Core](Aroma1997Core-1.7.10-1.0.2.16.jar) 
    UCHI    CodeChickenCore{1.0.7.47} [CodeChicken Core](minecraft.jar) 
    UCHI    NotEnoughItems{1.0.5.118} [Not Enough Items](NotEnoughItems-1.7.10-1.0.5.118-universal.jar) 
    UCHI    OpenModsCore{0.8} [OpenModsCore](minecraft.jar) 
    UCHI    <CoFH ASM>{000} [CoFH ASM](minecraft.jar) 
    UCHI    FastCraft{1.23} [FastCraft](fastcraft-1.23.jar) 
    UCHI    bspkrsCore{6.16} [bspkrsCore]([1.7.10]bspkrsCore-universal-6.16.jar) 
    UCHI    StatusEffectHUD{1.27} [StatusEffectHUD]([1.7.10]StatusEffectHUD-client-1.27.jar) 
    UCHI    Treecapitator{1.7.10} [Treecapitator]([1.7.10]Treecapitator-universal-2.0.4.jar) 
    UCHI    AgriCraft{1.7.10-1.4.6-hotfix} [AgriCraft](AgriCraft-1.7.10-1.4.6-hotfix.jar) 
    UCHI    AppleCore{1.1.0} [AppleCore](AppleCore-mc1.7.10-1.1.0.jar) 
    UCHI    appliedenergistics2{rv2-stable-10} [Applied Energistics 2](appliedenergistics2-rv2-stable-10.jar) 
    UCHI    Aroma1997CoreHelper{1.0.2.16} [Aroma1997Core|Helper](Aroma1997Core-1.7.10-1.0.2.16.jar) 
    UCHI    AromaBackup{0.0.0.6} [AromaBackup](AromaBackup-1.7.10-0.0.0.6.jar) 
    UCHI    AromaBackupRecovery{1.0} [AromaBackup Recovery](AromaBackup-1.7.10-0.0.0.6.jar) 
    UCHI    Backpack{2.0.1} [Backpack](backpack-2.0.1-1.7.x.jar) 
    UCHI    Baubles{1.0.1.10} [Baubles](Baubles-1.7.10-1.0.1.10.jar) 
    UCHI    CoFHCore{1.7.10R3.1.2} [CoFH Core](CoFHCore-[1.7.10]3.1.2-325.jar) 
    UCHI    ThermalFoundation{1.7.10R1.2.3} [Thermal Foundation](ThermalFoundation-[1.7.10]1.2.3-112.jar) 
    UCHI    ThermalExpansion{1.7.10R4.1.2} [Thermal Expansion](ThermalExpansion-[1.7.10]4.1.2-240.jar) 
    UCHI    BigReactors{0.4.3A} [Big Reactors](BigReactors-0.4.3A.jar) 
    UCHI    Botania{r1.8-246} [Botania](Botania r1.8-246.jar) 
    UCHI    ComputerCraft{1.75} [ComputerCraft](ComputerCraft1.75.jar) 
    UCHI    CustomMainMenu{1.9.2} [Custom Main Menu](CustomMainMenu-MC1.7.10-1.9.2.jar) 
    UCHI    defaultworldgenerator{0.1-b13} [Default World Generator](DefaultWorldGenerator-1.7.10-0.1-b13-universal.jar) 
    UCHI    etfuturum{1.5.2} [Et Futurum](Et Futurum-1.5.2.jar) 
    UCHI    ForgeMultipart{1.2.0.345} [Forge Multipart](ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    UCHI    ExtraUtilities{1.2.12} [Extra Utilities](extrautilities-1.2.12.jar) 
    UCHI    GardenOfGlass{sqrt(-1)} [Garden of Glass](GardenOfGlass.jar) 
    UCHI    HardcoreQuesting{4.4.4} [Hardcore Questing Mode](HQM-The Journey-4.4.4.jar) 
    UCHI    inpure|core{1.7.10R1.0.0B9} [INpureCore](INpureCore-[1.7.10]1.0.0B9-62.jar) 
    UCHI    inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks](InventoryTweaks-1.59-dev-152.jar) 
    UCHI    journeymap{5.1.3} [JourneyMap](journeymap-1.7.10-5.1.3-unlimited.jar) 
    UCHI    Mantle{1.7.10-0.3.2.jenkins191} [Mantle](Mantle-1.7.10-0.3.2b.jar) 
    UCHI    Mekanism{9.1.0} [Mekanism](Mekanism-1.7.10-9.1.0.281.jar) 
    UCHI    MekanismGenerators{9.1.0} [MekanismGenerators](MekanismGenerators-1.7.10-9.1.0.281 %281%29.jar) 
    UCHI    MekanismTools{9.1.0} [MekanismTools](MekanismTools-1.7.10-9.1.0.281.jar) 
    UCHI    MineTweaker3{3.0.9B} [MineTweaker 3](MineTweaker3-1.7.10-3.0.9C.jar) 
    UCHE    modtweaker2{0.9.6} [Mod Tweaker 2](ModTweaker2-0.9.6.jar) 
    UCHI    OpenMods{0.8} [OpenMods](OpenModsLib-1.7.10-0.8.jar) 
    UCHI    OpenBlocks{1.4.4} [OpenBlocks](OpenBlocks-1.7.10-1.4.4.jar) 
    UCHI    harvestcraft{1.7.10j} [Pam's HarvestCraft](Pam's HarvestCraft 1.7.10Lb.jar) 
    UCHI    ProjectE{1.7.10-PE1.10.0} [ProjectE](ProjectE-1.7.10-PE1.10.0.jar) 
    UCHI    ResourceLoader{1.2} [Resource Loader](ResourceLoader-1.2.jar) 
    UCHI    runicdungeons{1.1.6a} [Runic Dungeons](runicdungeons-1.1.6a.jar) 
    UCHI    StevesFactoryManager{A93} [Steve's Factory Manager](StevesFactoryManagerA93.jar) 
    UCHI    StorageDrawers{1.7.10-1.7.5} [Storage Drawers](StorageDrawers-1.7.10-1.7.5.jar) 
    UCHI    Waila{1.5.10} [Waila](Waila-1.5.10_1.7.10.jar) 
    UCHI    TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct](TConstruct-1.7.10-1.8.8.jar) 
    UCHI    ThermalDynamics{1.7.10R1.1.0} [Thermal Dynamics](ThermalDynamics-[1.7.10]1.1.0-161.jar) 
    UCHI    treeGrowingSimulator{0.0.4} [Tree Growing Simulator 2014](treeGrowingSimulator-0.0.4.jar) 
    UCHI    WailaHarvestability{1.1.6} [Waila Harvestability](WailaHarvestability-mc1.7.10-1.1.6.jar) 
    UCHI    wawla{1.3.3} [What Are We Looking At](Wawla-1.3.3-1.7.10.jar) 
    UCHI    McMultipart{1.2.0.345} [Minecraft Multipart Plugin](ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    UCHI    HungerOverhaul{1.7.10-1.0.0.jenkins75} [Hunger Overhaul](HungerOverhaul-1.7.10-1.0.0.jar) 
    UCHI    ForgeMicroblock{1.2.0.345} [Forge Microblocks](ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    GL info: ' Vendor: 'Intel' Version: '4.3.0 - Build 10.18.15.4240' Renderer: 'Intel(R) HD Graphics 4400'
    OpenModsLib class transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[map_gen_fix:ENABLED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
    Class transformer null safety: all safe
    AE2 Version: stable rv2-stable-10 for Forge 10.13.2.1291
    CoFHCore: -[1.7.10]3.1.2-325
    ThermalFoundation: -[1.7.10]1.2.3-112
    ThermalExpansion: -[1.7.10]4.1.2-240
    Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine
    TConstruct Environment: Environment healthy.
    ThermalDynamics: -[1.7.10]1.1.0-161
    Stencil buffer state: Function set: GL30, pool: forge, bits: 8

**Comment by mezz** [comment]
Thanks for the report!
This appears to be an issue with Minetweaker/Modtweaker and Mekanism, not Forestry.
