### ISSUE TITLE
[1.10.2]Forestry Crate Model Error

### ISSUE THREAD

**Issue by Speiger** [ForestryMC/ForestryMC#1480]
```
[03:41:51] [Client thread/ERROR] [JEI]: Couldn't get ItemModel for Forestry itemStack 1xitem.crated.ic2.itemMisc.52@0 forestry:crated.ic2.itemMisc.52
java.lang.NullPointerException
    at forestry.core.models.ModelCrate.bakeModel(ModelCrate.java:208) ~[ModelCrate.class:?]
    at forestry.core.models.ModelCrate.access$200(ModelCrate.java:61) ~[ModelCrate.class:?]
    at forestry.core.models.ModelCrate$CrateOverrideList.handleItemState(ModelCrate.java:247) ~[ModelCrate$CrateOverrideList.class:?]
    at net.minecraft.client.renderer.RenderItem.getItemModelWithOverrides(RenderItem.java:254) ~[RenderItem.class:?]
    at mezz.jei.IngredientBaseListFactory$IngredientChecker.isIngredientHidden(IngredientBaseListFactory.java:161) [IngredientBaseListFactory$IngredientChecker.class:?]
    at mezz.jei.IngredientBaseListFactory.addToBaseList(IngredientBaseListFactory.java:66) [IngredientBaseListFactory.class:?]
    at mezz.jei.IngredientBaseListFactory.create(IngredientBaseListFactory.java:42) [IngredientBaseListFactory.class:?]
    at mezz.jei.ItemFilter.build(ItemFilter.java:36) [ItemFilter.class:?]
    at mezz.jei.JeiStarter.startJEI(JeiStarter.java:46) [JeiStarter.class:?]
    at mezz.jei.ProxyCommonClient.startJEI(ProxyCommonClient.java:128) [ProxyCommonClient.class:?]
    at mezz.jei.ProxyCommonClient.onEntityJoinedWorld(ProxyCommonClient.java:114) [ProxyCommonClient.class:?]
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_87_ProxyCommonClient_onEntityJoinedWorld_EntityJoinWorldEvent.invoke(.dynamic) [?:?]
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185) [EventBus.class:?]
    at net.minecraft.world.World.spawnEntityInWorld(World.java:1219) [World.class:?]
    at net.minecraft.client.multiplayer.WorldClient.spawnEntityInWorld(WorldClient.java:211) [WorldClient.class:?]
    at net.minecraft.client.Minecraft.loadWorld(Minecraft.java:2557) [Minecraft.class:?]
    at net.minecraft.client.Minecraft.loadWorld(Minecraft.java:2462) [Minecraft.class:?]
    at net.minecraft.client.network.NetHandlerPlayClient.handleJoinGame(NetHandlerPlayClient.java:301) [NetHandlerPlayClient.class:?]
    at net.minecraft.network.play.server.SPacketJoinGame.processPacket(SPacketJoinGame.java:89) [SPacketJoinGame.class:?]
    at net.minecraft.network.play.server.SPacketJoinGame.processPacket(SPacketJoinGame.java:13) [SPacketJoinGame.class:?]
    at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:15) [PacketThreadUtil$1.class:?]
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_91]
    at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_91]
    at net.minecraft.util.Util.runTask(Util.java:25) [Util.class:?]
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1108) [Minecraft.class:?]
    at net.minecraft.client.Minecraft.run(Minecraft.java:406) [Minecraft.class:?]
    at net.minecraft.client.main.Main.main(Main.java:118) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_91]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_91]
    at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97) [start/:?]
    at GradleStart.main(GradleStart.java:26) [start/:?]
```

This happens with IC2Classic. The thing is. It happens because you are expecting that the containing Items in the creates have no ItemMeshDefinition.
All Items/Blocks in IC2Classic use a ItemMeshDefinition & IBlockStateMapper it would be great if you could account for that. 
~~Since you guys try to copy a Block/Item from a Model. Why dont you just get the IBakedModel and draw the vertexData to get the Texture. Partical Texture is not a case because IC2Exp returns there only missing models.~~
Since the last thing i told was wrong because you do that already proprly (Sry) i fixed that.
Also a thing to take into account and i just saw that. You are trying to load the ModelFiles from Forge.. That will not work with my models. I use the Vanilla Only Registry. (I generate the models via JavaCode)
So i do use only IBakedModels. No IModel or something else like that.

Edit: Cleared some text to make it better understandable
Edit2: Added some extra info.

**Comment by Speiger** [comment]
Its happening even with basic Ingots. You really need to have that renderer rewritten. Since classic will rely on this i try to help out and make a fix & a better renderer...

**Comment by Speiger** [comment]
Fixed. Just a question @mezz when do you think this is going to be released?

**Comment by mezz** [comment]
Changes are automatically built and released, it is available now.

**Comment by Speiger** [comment]
ok thanks :3
