### ISSUE TITLE
Crash with Energy Transfer from Engines

### ISSUE THREAD

**Issue by robaimes** [ForestryMC/ForestryMC#1507]
I tested this with a few engines. Clockwork mainly, as it was easy, but it also occurs with peat fired engines so I suspect it affects more.

Having an activated engine next to a Mekanism machine causes the following crash. It occurs on both SSP and SMP. This may be a fault of Mekanism as it only affects machines from that mod, but the stacktrace does point to Forestry.

**Crash log:** http://pastebin.com/QeCwSWyY

**Comment by mezz** [comment]
Thanks for the report!
This is definitely a Mekanism issue but I can defend against it in Forestry.

Basically Forestry is asking the Mekanism machine if it handles Tesla from a specific side, the machine says yes, and then when Forestry tries to interact with the machine it doesn't actually handle Tesla, causing a crash.

You can see Mekanism crashing in the log:

```
[20:34:54] [Server thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: java.lang.NoSuchMethodException: mekanism.common.integration.TeslaIntegration.<init>(mekanism.common.base.IEnergyWrapper, net.minecraft.util.EnumFacing)
[20:34:54] [Server thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]:    at java.lang.Class.getConstructor0(Class.java:3082)
[20:34:54] [Server thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]:    at java.lang.Class.getConstructor(Class.java:1825)
[20:34:54] [Server thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]:    at mekanism.common.capabilities.CapabilityWrapperManager.getWrapper(CapabilityWrapperManager.java:26)
[20:34:54] [Server thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]:    at mekanism.common.tile.TileEntityElectricBlock.getCapability(TileEntityElectricBlock.java:455)
[20:34:54] [Server thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]:    at mekanism.common.tile.TileEntityBasicMachine.getCapability(TileEntityBasicMachine.java:329)
[20:34:54] [Server thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]:    at forestry.energy.compat.tesla.TeslaHelper._sendEnergy(TeslaHelper.java:49)
[20:34:54] [Server thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]:    at forestry.energy.compat.tesla.TeslaHelper.sendEnergy(TeslaHelper.java:36)
[20:34:54] [Server thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]:    at forestry.energy.EnergyHelper.sendEnergy(EnergyHelper.java:66)
[20:34:54] [Server thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]:    at forestry.energy.EnergyHelper.canSendEnergy(EnergyHelper.java:84)
[20:34:54] [Server thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]:    at forestry.core.tiles.TileEngine.updateServerSide(TileEngine.java:140)
[20:34:54] [Server thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]:    at forestry.core.tiles.TileForestry.update(TileForestry.java:90)
[20:34:54] [Server thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]:    at net.minecraft.world.World.updateEntities(World.java:1942)
[20:34:54] [Server thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]:    at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:645)
[20:34:54] [Server thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]:    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:783)
[20:34:54] [Server thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]:    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:687)
[20:34:54] [Server thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]:    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:156)
[20:34:54] [Server thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]:    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:536)
[20:34:54] [Server thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]:    at java.lang.Thread.run(Thread.java:745)
```

**Comment by robaimes** [comment]
Thanks for the update, will forward this to the Mekanism repo.

**Comment by mezz** [comment]
I fixed the crash but you will now get _crazy_ log spam from Mekanism until they can resolve the issue.
