### ISSUE TITLE
[Crash] Ticking block entity

### ISSUE THREAD

**Issue by ExDomino** [ForestryMC/ForestryMC#1541]
Minecraft 1.10.2 - Forestry 5.2.16.330 (& 335)

java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[north, east, south, west, down, up]} as it does not exist in BlockStateContainer{block=forestry:candle, properties=[facing, state]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:203)
	at forestry.core.tiles.TileEngine.updateServerSide(TileEngine.java:118)
	at forestry.energy.tiles.TileEnginePeat.updateServerSide(TileEnginePeat.java:93)
	at forestry.core.tiles.TileForestry.func_73660_a(TileForestry.java:90)
	at net.minecraft.world.World.func_72939_s(World.java:1804)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:619)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Unknown Source)

**Comment by Nedelosk** [comment]
Same Bug as #1543
