### ISSUE TITLE
[1.11.2] World freeze - NPE in PacketGenomeTrackerSync$Handler.onPacketData

### ISSUE THREAD

**Issue by asiekierka** [ForestryMC/ForestryMC#1560]
[11:29:48] [Client thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_111]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_111]
        at net.minecraft.util.Util.runTask(Util.java:27) [Util.class:?]
        at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1109) [Minecraft.class:?]
        at net.minecraft.client.Minecraft.run(Minecraft.java:407) [Minecraft.class:?]
        at net.minecraft.client.main.Main.main(Main.java:118) [Main.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_111]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_111]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
        at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97) [start/:?]
        at GradleStart.main(GradleStart.java:26) [start/:?]
Caused by: java.lang.NullPointerException
        at forestry.core.network.packets.PacketGenomeTrackerSync$Handler.onPacketData(PacketGenomeTrackerSync.java:55) ~[PacketGenomeTrackerSync$Handler.class:?]
        at forestry.core.network.PacketHandler.lambda$checkThreadAndEnqueue$0(PacketHandler.java:68) ~[PacketHandler.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_111]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_111]
        at net.minecraft.util.Util.runTask(Util.java:26) ~[Util.class:?]
        ... 15 more

(Random freeze on world load; 1.11.2; Forge 2201; build 11)

**Comment by mezz** [comment]
The timing for syncing data from server->client on login is not straightforward.
I need to make a packet from client to server requesting this data, instead of just having the server blindly send it.
