### ISSUE TITLE
Gamecrash while trying to produce basic circuit board

### ISSUE THREAD

**Issue by itsjakc** [ForestryMC/ForestryMC#1561]
**## If you put the needed materials for the basic circuit board into the carpenter and ad water to it in order to start the process, the game crashes and you're not able to log back into the world.**

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (Quark-r1.2-73.jar)
Contact their authors BEFORE contacting forge

// Would you like a cupcake?

Time: 1/7/17 4:54 PM
Description: Ticking block entity

java.lang.AbstractMethodError: forestry.core.recipes.ShapedRecipeCustom.getRecipeOutput()Lnet/minecraft/item/ItemStack;
	at forestry.factory.tiles.TileCarpenter.hasWork(TileCarpenter.java:208)
	at forestry.core.tiles.TilePowered.updateServerSide(TilePowered.java:109)
	at forestry.factory.tiles.TileCarpenter.updateServerSide(TileCarpenter.java:130)
	at forestry.core.tiles.TileForestry.func_73660_a(TileForestry.java:85)
	at net.minecraft.world.World.func_72939_s(World.java:1801)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at forestry.factory.tiles.TileCarpenter.hasWork(TileCarpenter.java:208)
	at forestry.core.tiles.TilePowered.updateServerSide(TilePowered.java:109)
	at forestry.factory.tiles.TileCarpenter.updateServerSide(TileCarpenter.java:130)
	at forestry.core.tiles.TileForestry.func_73660_a(TileForestry.java:85)

-- Block entity being ticked --
Details:
	Name: minecraft:forestry.carpenter // forestry.factory.tiles.TileCarpenter
	Block type: ID #479 (tile.for.carpenter // forestry.factory.blocks.BlockFactoryTESR)
	Block data value: 3 / 0x3 / 0b0011
	Block location: World: (114,64,215), Chunk: (at 2,4,7 in 7,13; contains blocks 112,0,208 to 127,255,223), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Actual block type: ID #479 (tile.for.carpenter // forestry.factory.blocks.BlockFactoryTESR)
	Actual block data value: 3 / 0x3 / 0b0011
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1801)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621)

-- Affected level --
Details:
	Level name: test
	All players: 1 total; [EntityPlayerMP['JackAkise'/1105, l='test', x=114.49, y=64.00, z=217.37]]
	Chunk stats: ServerChunkCache: 1042 Drop: 0
	Level seed: 3621140850432204912
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: {"diamondSize":8,"lapisCenterHeight":16,"lavaLakeChance":80,"redstoneMaxHeight":16,"diamondMaxHeight":16,"coalMaxHeight":128,"coalMinHeight":0,"seaLevel":63,"graniteCount":10,"riverSize":4,"gravelMinHeight":0,"graniteSize":33,"redstoneSize":8,"fixedBiome":-1,"waterLakeChance":4,"dioriteMinHeight":0,"andesiteCount":10,"graniteMaxHeight":80,"redstoneMinHeight":0,"lapisSize":7,"dirtCount":10,"ironMinHeight":0,"dioriteMaxHeight":80,"coalCount":20,"gravelCount":8,"coalSize":17,"gravelSize":33,"ironMaxHeight":64,"lapisSpread":16,"dioriteCount":10,"andesiteSize":33,"biomeSize":4,"graniteMinHeight":0,"goldCount":2,"diamondCount":1,"dirtSize":33,"gravelMaxHeight":256,"goldSize":9,"ironCount":20,"diamondMinHeight":0,"ironSize":9,"redstoneCount":8,"andesiteMinHeight":0,"dioriteSize":33,"goldMaxHeight":32,"dungeonChance":8,"andesiteMaxHeight":80,"dirtMinHeight":0,"lapisCount":1,"goldMinHeight":0,"dirtMaxHeight":256,"lowerLimitScale":512.0,"biomeDepthOffset":0.0,"upperLimitScale":512.0,"heightScale":684.412,"biomeScaleWeight":1.0,"biomeDepthWeight":1.0,"mainNoiseScaleZ":80.0,"mainNoiseScaleY":160.0,"depthNoiseScaleX":200.0,"mainNoiseScaleX":80.0,"baseSize":8.5,"depthNoiseScaleZ":200.0,"stretchY":12.0,"depthNoiseScaleExponent":0.5,"biomeScaleOffset":0.0,"coordinateScale":684.412,"useStrongholds":true,"useMineShafts":true,"useTemples":true,"useLavaOceans":false,"useCaves":true,"useWaterLakes":true,"useLavaLakes":true,"useMonuments":true,"useRavines":true,"useDungeons":true,"useVillages":true}
	Level spawn location: World: (116,64,224), Chunk: (at 4,4,0 in 7,14; contains blocks 112,0,224 to 127,255,239), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 159 game time, 159 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 123968 (now: false), thunder time: 33671 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 320818320 bytes (305 MB) / 858910720 bytes (819 MB) up to 4281597952 bytes (4083 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 1, tcache: 1, allocated: 12, tallocated: 94
	FML: MCP 9.38 Powered by Forge 13.20.0.2203 12 mods loaded, 12 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2203.jar) 
	UCHIJAAAA	forge{13.20.0.2203} [Minecraft Forge] (forge-1.11.2-13.20.0.2203.jar) 
	UCHIJAAAA	quark{r1.2-73} [Quark] (Quark-r1.2-73.jar) 
	UCHIJAAAA	autoreglib{1.1-4} [AutoRegLib] (AutoRegLib-1.1-4.jar) 
	UCHIJAAAA	forestry{5.3.0.13} [Forestry] (forestry_1.11.2-5.3.0.13.jar) 
	UCHIJAAAA	jei{4.2.2.220} [Just Enough Items] (jei_1.11.2-4.2.2.220.jar) 
	UCHIJAAAA	neat{1.4-13} [Neat] (Neat 1.4-13.jar) 
	UCHIJAAAA	lteleporters{1.11.2-2.0.2} [Simple Teleporters] (SimpleTeleporters-1.11.2-2.0.2.jar) 
	UCHIJAAAA	veinminer{0.35.3} [Vein Miner] (VeinMiner-1.11-0.35.3.605+dad98e1.jar) 
	UCHIJAAAA	veinminermodsupport{0.35.3} [Mod Support] (VeinMiner-1.11-0.35.3.605+dad98e1.jar) 
	Loaded coremods (and transformers): 
LoadingPlugin (Quark-r1.2-73.jar)
  vazkii.quark.base.asm.ClassTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['JackAkise'/1105, l='test', x=114.49, y=64.00, z=217.37]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
```

**Comment by mezz** [comment]
Thanks for the report!
Please include the full error log. You seem to have cut it short for some reason.
You can paste the full thing to https://gist.github.com and link it here.

**Comment by itsjakc** [comment]
well.. iam sorry
https://gist.github.com/itsjakc/52b53f7925abc833d15bdf62a36c7810

**Comment by itsjakc** [comment]
Just realised i used the wrong recipe. But the recipe i used is still abel to crash a server. I uploaded on imgur a screenshot of the recepi. http://imgur.com/a/JU9Lg

**Comment by itsjakc** [comment]
Nvm it crashes with the right recipe too...

**Comment by mezz** [comment]
Thanks, fixed in the latest version.
