### ISSUE TITLE
Gamecrash while trying to trade with the Apiarist

### ISSUE THREAD

**Issue by itsjakc** [ForestryMC/ForestryMC#1563]
**Today I found a Village and the Apiarist has some cool Forestry stuff. But the thing is, if i go through the offers he makes the Game crash every Time on the same offer page.
Full Crash Report**
```
`---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (Quark-r1.2-73.jar)
Contact their authors BEFORE contacting forge

// I just don't know what went wrong :(

Time: 1/8/17 12:18 AM
Description: Rendering item

java.lang.IllegalArgumentException: itemStack must have nbt
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:125)
	at forestry.core.genetics.Genome.getChromosome(Genome.java:139)
	at forestry.core.genetics.Genome.getActiveAllele(Genome.java:178)
	at forestry.apiculture.genetics.BeeGenome.getSpecies(BeeGenome.java:90)
	at forestry.apiculture.items.ItemBeeGE.getSpecies(ItemBeeGE.java:61)
	at forestry.apiculture.items.ItemBeeGE$BeeMeshDefinition.func_178113_a(ItemBeeGE.java:147)
	at net.minecraft.client.renderer.ItemModelMesher.func_178089_a(ItemModelMesher.java:52)
	at net.minecraft.client.renderer.RenderItem.func_184393_a(RenderItem.java:247)
	at net.minecraft.client.renderer.RenderItem.func_184391_a(RenderItem.java:347)
	at net.minecraft.client.renderer.RenderItem.func_180450_b(RenderItem.java:336)
	at net.minecraft.client.gui.GuiMerchant.func_73863_a(SourceFile:152)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1111)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1077)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:125)
	at forestry.core.genetics.Genome.getChromosome(Genome.java:139)
	at forestry.core.genetics.Genome.getActiveAllele(Genome.java:178)
	at forestry.apiculture.genetics.BeeGenome.getSpecies(BeeGenome.java:90)
	at forestry.apiculture.items.ItemBeeGE.getSpecies(ItemBeeGE.java:61)
	at forestry.apiculture.items.ItemBeeGE$BeeMeshDefinition.func_178113_a(ItemBeeGE.java:147)
	at net.minecraft.client.renderer.ItemModelMesher.func_178089_a(ItemModelMesher.java:52)
	at net.minecraft.client.renderer.RenderItem.func_184393_a(RenderItem.java:247)

-- Item being rendered --
Details:
	Item Type: forestry.apiculture.items.ItemBeeGE@42d071d4
	Item Aux: 0
	Item NBT: null
	Item Foil: ~~ERROR~~ IllegalArgumentException: itemStack must have nbt
Stacktrace:
	at net.minecraft.client.renderer.RenderItem.func_184391_a(RenderItem.java:347)
	at net.minecraft.client.renderer.RenderItem.func_180450_b(RenderItem.java:336)
	at net.minecraft.client.gui.GuiMerchant.func_73863_a(SourceFile:152)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)

-- Screen render details --
Details:
	Screen name: net.minecraft.client.gui.GuiMerchant
	Mouse location: Scaled: (545, 220). Absolute: (1091, 638)
	Screen size: Scaled: (960, 540). Absolute: (1920, 1080). Scale factor of 2

-- Affected level --
Details:
	Level name: MpServer
	All players: 2 total; [EntityPlayerSP['JackAkise'/214995, l='MpServer', x=-3538.33, y=75.94, z=-2386.70], EntityOtherPlayerMP['Bluebirdy_'/215308, l='MpServer', x=-3540.05, y=76.00, z=-2386.06]]
	Chunk stats: MultiplayerChunkCache: 441, 441
	Level seed: 0
	Level generator: ID 06 - quark_realistic, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-104,64,252), Chunk: (at 8,4,12 in -7,15; contains blocks -112,0,240 to -97,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 1960197 game time, 2011 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 114 total; [EntityPlayerSP['JackAkise'/214995, l='MpServer', x=-3538.33, y=75.94, z=-2386.70], EntityZombie['Zombie'/216327, l='MpServer', x=-3519.48, y=15.00, z=-2365.72], EntitySkeleton['Skeleton'/217093, l='MpServer', x=-3566.50, y=53.00, z=-2391.50], EntityBat['Bat'/216587, l='MpServer', x=-3462.70, y=14.48, z=-2427.20], EntityCreeper['Creeper'/217099, l='MpServer', x=-3485.50, y=12.00, z=-2373.50], EntityCreeper['Creeper'/217098, l='MpServer', x=-3486.50, y=12.00, z=-2373.50], EntitySpider['Spider'/217096, l='MpServer', x=-3486.50, y=12.00, z=-2373.50], EntityOtherPlayerMP['Bluebirdy_'/215308, l='MpServer', x=-3540.05, y=76.00, z=-2386.06], EntityCreeper['Creeper'/217100, l='MpServer', x=-3482.50, y=47.00, z=-2339.50], EntityBat['Bat'/216598, l='MpServer', x=-3522.77, y=16.40, z=-2417.29], EntityZombie['Zombie'/215835, l='MpServer', x=-3476.50, y=32.00, z=-2318.50], EntitySkeleton['Skeleton'/215837, l='MpServer', x=-3475.50, y=32.00, z=-2322.50], EntitySkeleton['Skeleton'/216093, l='MpServer', x=-3470.50, y=34.00, z=-2370.50], EntityZombie['Zombie'/215836, l='MpServer', x=-3478.50, y=32.00, z=-2322.50], EntitySquid['Squid'/215080, l='MpServer', x=-3586.00, y=62.41, z=-2361.40], EntitySheep['Sheep'/215086, l='MpServer', x=-3596.48, y=92.00, z=-2340.77], EntityCreeper['Creeper'/215340, l='MpServer', x=-3562.50, y=27.00, z=-2371.50], EntityCreeper['Creeper'/216372, l='MpServer', x=-3497.50, y=12.00, z=-2375.50], EntitySheep['Sheep'/215097, l='MpServer', x=-3583.17, y=74.00, z=-2401.36], EntitySquid['Squid'/215101, l='MpServer', x=-3578.89, y=61.40, z=-2367.60], EntityCreeper['Creeper'/215356, l='MpServer', x=-3613.50, y=39.00, z=-2370.50], EntitySkeleton['Skeleton'/216907, l='MpServer', x=-3480.50, y=39.00, z=-2347.50], EntityZombie['Zombie'/215114, l='MpServer', x=-3578.50, y=27.00, z=-2365.50], EntityCreeper['Creeper'/215113, l='MpServer', x=-3580.50, y=27.00, z=-2364.50], EntityBat['Bat'/216141, l='MpServer', x=-3460.85, y=32.00, z=-2361.42], EntitySheep['Sheep'/215123, l='MpServer', x=-3578.25, y=83.00, z=-2344.59], EntityMinecartChest['Minecart with Chest'/215122, l='MpServer', x=-3580.50, y=12.06, z=-2338.49], EntitySheep['Sheep'/215124, l='MpServer', x=-3583.76, y=93.00, z=-2331.69], EntityBat['Bat'/216411, l='MpServer', x=-3597.11, y=42.11, z=-2374.44], EntityBat['Bat'/216410, l='MpServer', x=-3609.89, y=39.11, z=-2373.09], EntitySquid['Squid'/216927, l='MpServer', x=-3516.07, y=60.00, z=-2421.90], EntitySquid['Squid'/216926, l='MpServer', x=-3508.93, y=60.00, z=-2418.17], EntityBat['Bat'/216669, l='MpServer', x=-3520.81, y=52.52, z=-2343.58], EntitySquid['Squid'/216925, l='MpServer', x=-3510.91, y=60.15, z=-2414.33], EntityBat['Bat'/216668, l='MpServer', x=-3516.24, y=54.99, z=-2341.41], EntitySkeleton['Skeleton'/215907, l='MpServer', x=-3465.50, y=35.00, z=-2373.68], EntityBat['Bat'/216417, l='MpServer', x=-3542.67, y=17.39, z=-2361.25], EntitySquid['Squid'/216928, l='MpServer', x=-3518.60, y=60.00, z=-2420.40], EntityZombie['Zombie'/215910, l='MpServer', x=-3533.50, y=35.00, z=-2422.50], EntityButterfly['Brimstone'/215141, l='MpServer', x=-3555.25, y=82.60, z=-2369.25], EntityVillager['Villager'/215140, l='MpServer', x=-3541.56, y=76.00, z=-2383.53], EntityItem['item.item.potatoPoisonous'/215151, l='MpServer', x=-3553.50, y=76.94, z=-2357.59], EntityVillager['Villager'/215150, l='MpServer', x=-3543.30, y=77.00, z=-2354.70], EntityVillager['Villager'/215149, l='MpServer', x=-3552.48, y=75.50, z=-2384.41], EntitySkeleton['Skeleton'/215155, l='MpServer', x=-3537.21, y=15.00, z=-2420.46], EntitySkeleton['Skeleton'/215159, l='MpServer', x=-3549.50, y=48.00, z=-2408.50], EntitySkeleton['Skeleton'/215158, l='MpServer', x=-3550.50, y=48.00, z=-2409.50], EntityItem['item.item.seeds'/215163, l='MpServer', x=-3546.13, y=65.00, z=-2363.36], EntitySkeleton['Skeleton'/215161, l='MpServer', x=-3549.50, y=39.00, z=-2354.50], EntityCreeper['Creeper'/215929, l='MpServer', x=-3512.50, y=20.00, z=-2457.50], EntitySkeleton['Skeleton'/215928, l='MpServer', x=-3512.50, y=20.00, z=-2457.50], EntitySheep['Sheep'/215165, l='MpServer', x=-3540.74, y=81.00, z=-2350.84], EntityItem['item.item.wheat'/215164, l='MpServer', x=-3546.13, y=65.00, z=-2363.46], EntitySkeleton['Skeleton'/215682, l='MpServer', x=-3545.50, y=51.00, z=-2394.23], EntitySkeleton['Skeleton'/216967, l='MpServer', x=-3593.50, y=58.00, z=-2392.50], EntityBat['Bat'/216709, l='MpServer', x=-3512.95, y=14.52, z=-2363.41], EntityOtherPlayerMP['Bluebirdy_'/215308, l='MpServer', x=-3540.05, y=76.00, z=-2386.06], EntitySpider['Spider'/215690, l='MpServer', x=-3529.50, y=16.00, z=-2307.50], EntityZombie['Zombie'/215433, l='MpServer', x=-3572.50, y=48.00, z=-2408.50], EntitySpider['Spider'/215689, l='MpServer', x=-3529.50, y=16.00, z=-2307.50], EntitySkeleton['Skeleton'/216968, l='MpServer', x=-3593.50, y=58.00, z=-2393.50], EntityBat['Bat'/215436, l='MpServer', x=-3556.80, y=33.10, z=-2369.55], EntitySkeleton['Skeleton'/215698, l='MpServer', x=-3522.50, y=16.00, z=-2350.50], EntitySkeleton['Skeleton'/215194, l='MpServer', x=-3520.50, y=15.00, z=-2368.50], EntitySpider['Spider'/215198, l='MpServer', x=-3535.50, y=13.00, z=-2370.50], EntityVillager['Villager'/215203, l='MpServer', x=-3540.72, y=77.00, z=-2377.55], EntityVillager['Villager'/215202, l='MpServer', x=-3517.50, y=75.94, z=-2386.61], EntityEnderman['Enderman'/216231, l='MpServer', x=-3536.54, y=47.00, z=-2383.45], EntityZombie['Zombie'/215208, l='MpServer', x=-3570.42, y=54.00, z=-2411.03], EntitySquid['Squid'/215219, l='MpServer', x=-3514.35, y=61.86, z=-2417.52], EntityVillager['Villager'/215218, l='MpServer', x=-3515.61, y=77.00, z=-2362.50], EntitySquid['Squid'/215223, l='MpServer', x=-3499.40, y=45.03, z=-2416.40], EntityCreeper['Creeper'/215221, l='MpServer', x=-3505.50, y=12.00, z=-2308.50], EntityAshen['entity.Quark.ashen.name'/215227, l='MpServer', x=-3497.50, y=8.00, z=-2389.50], EntityItem['item.item.dyePowder.black'/215225, l='MpServer', x=-3497.74, y=43.00, z=-2421.06], EntitySheep['Sheep'/215231, l='MpServer', x=-3491.73, y=80.00, z=-2400.50], EntityItem['item.item.bread'/215230, l='MpServer', x=-3511.47, y=76.00, z=-2371.67], EntityVillager['Villager'/215229, l='MpServer', x=-3529.28, y=77.00, z=-2373.67], EntityCreeper['Creeper'/216509, l='MpServer', x=-3571.50, y=27.00, z=-2370.50], EntityZombie['Zombie'/217020, l='MpServer', x=-3482.50, y=33.00, z=-2330.66], EntityBat['Bat'/216770, l='MpServer', x=-3511.90, y=11.71, z=-2336.25], EntityMinecartChest['Minecart with Chest'/215233, l='MpServer', x=-3496.50, y=8.06, z=-2357.19], EntityItem['item.tile.dirt.default'/214999, l='MpServer', x=-3538.25, y=74.00, z=-2385.13], EntityVillager['Villager'/214998, l='MpServer', x=-3538.30, y=74.00, z=-2385.30], EntityZombie['Zombie'/214997, l='MpServer', x=-3546.42, y=49.00, z=-2404.78], EntityCreeper['Creeper'/214996, l='MpServer', x=-3544.80, y=51.00, z=-2390.56], EntityVillager['Villager'/215003, l='MpServer', x=-3546.51, y=77.00, z=-2380.02], EntityVillager['Villager'/215000, l='MpServer', x=-3544.70, y=77.00, z=-2381.70], EntityButterfly['Holly Blue'/215007, l='MpServer', x=-3547.71, y=77.32, z=-2370.32], EntityChicken['Chicken'/215263, l='MpServer', x=-3477.62, y=82.00, z=-2380.87], EntityButterfly['Common Clouded Yellow'/215006, l='MpServer', x=-3545.15, y=76.00, z=-2378.11], EntityVillager['Villager'/215005, l='MpServer', x=-3544.70, y=77.00, z=-2379.30], EntityCreeper['Creeper'/215773, l='MpServer', x=-3615.50, y=37.00, z=-2374.50], EntityZombie['Zombie'/217053, l='MpServer', x=-3588.50, y=56.00, z=-2390.50], EntityVillager['Villager'/215004, l='MpServer', x=-3552.65, y=75.50, z=-2385.53], EntityButterfly['Palaeno Sulphur'/215011, l='MpServer', x=-3548.75, y=80.00, z=-2376.35], EntityButterfly['Zebra Swallowtail'/215010, l='MpServer', x=-3547.30, y=82.00, z=-2375.49], EntityZombie['Zombie'/215266, l='MpServer', x=-3479.50, y=37.00, z=-2350.50], EntityCreeper['Creeper'/216546, l='MpServer', x=-3574.50, y=27.00, z=-2368.50], EntityButterfly['Diana Fritillary'/215009, l='MpServer', x=-3542.67, y=76.93, z=-2365.69], EntitySkeleton['Skeleton'/216545, l='MpServer', x=-3569.50, y=27.00, z=-2370.50], EntityVillager['Villager'/215008, l='MpServer', x=-3538.30, y=79.00, z=-2379.30], EntityZombie['Zombie'/216806, l='MpServer', x=-3504.50, y=63.00, z=-2334.50], EntityZombie['Zombie'/215269, l='MpServer', x=-3476.50, y=61.00, z=-2308.50], EntityButterfly['Diana Fritillary'/215012, l='MpServer', x=-3545.20, y=81.00, z=-2378.80], EntityZombie['Zombie'/216555, l='MpServer', x=-3536.50, y=44.00, z=-2307.50], EntityChicken['Chicken'/215274, l='MpServer', x=-3461.38, y=85.00, z=-2374.85], EntityChicken['Chicken'/215273, l='MpServer', x=-3459.21, y=84.00, z=-2389.64], EntityZombie['Zombie'/216556, l='MpServer', x=-3537.50, y=44.00, z=-2308.50], EntitySkeleton['Skeleton'/216562, l='MpServer', x=-3485.50, y=12.00, z=-2322.50], EntityVillager['Villager'/215031, l='MpServer', x=-3556.51, y=76.00, z=-2384.45], EntitySheep['Sheep'/215030, l='MpServer', x=-3539.73, y=81.50, z=-2349.50], EntitySkeleton['Skeleton'/216570, l='MpServer', x=-3464.27, y=59.00, z=-2315.51], EntityZombie['Zombie'/216063, l='MpServer', x=-3539.50, y=14.00, z=-2456.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:415)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2655)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:393)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 366426104 bytes (349 MB) / 807927808 bytes (770 MB) up to 4281597952 bytes (4083 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.38 Powered by Forge 13.20.0.2203 12 mods loaded, 12 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2203.jar) 
	UCHIJA	forge{13.20.0.2203} [Minecraft Forge] (forge-1.11.2-13.20.0.2203.jar) 
	UCHIJA	quark{r1.2-73} [Quark] (Quark-r1.2-73.jar) 
	UCHIJA	autoreglib{1.1-4} [AutoRegLib] (AutoRegLib-1.1-4.jar) 
	UCHIJA	forestry{5.3.0.13} [Forestry] (forestry_1.11.2-5.3.0.13.jar) 
	UCHIJA	jei{4.2.2.220} [Just Enough Items] (jei_1.11.2-4.2.2.220.jar) 
	UCHIJA	neat{1.4-13} [Neat] (Neat 1.4-13.jar) 
	UCHIJA	lteleporters{1.11.2-2.0.2} [Simple Teleporters] (SimpleTeleporters-1.11.2-2.0.2.jar) 
	UCHIJA	veinminer{0.35.3} [Vein Miner] (VeinMiner-1.11-0.35.3.605+dad98e1.jar) 
	UCHIJA	veinminermodsupport{0.35.3} [Mod Support] (VeinMiner-1.11-0.35.3.605+dad98e1.jar) 
	Loaded coremods (and transformers): 
LoadingPlugin (Quark-r1.2-73.jar)
  vazkii.quark.base.asm.ClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 376.33' Renderer: 'GeForce GTX 960/PCIe/SSE2'
	Launched Version: 1.11.2-forge1.11.2-13.20.0.2203
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 960/PCIe/SSE2 GL version 4.5.0 NVIDIA 376.33, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 6x AMD FX(tm)-6100 Six-Core Processor `
```

**Comment by mezz** [comment]
Thanks for the report!
Fixed in the latest version.
