### ISSUE TITLE
[1.7.10] NEI Crash with Butterfly Module Disabled

### ISSUE THREAD

**Issue by Peppe-KSP** [ForestryMC/ForestryMC#1567]
Latest Forestry/NEI from curse.
Installed mods Forestry, NEI, and any dependents. 

modules.cfg disable butterfly:
    # Butterflies. Shiny.
    B:lepidopterology=false

Open NEI and try to reset the filter (double click a mod/subset to filter).  NEI will log:  
```
Exception in thread "NEI Subset Item Allocation" [08:38:07] [NEI Subset Item Allocation/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.NullPointerException
[08:38:07] [NEI Subset Item Allocation/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at forestry.core.recipes.nei.ItemFilterGenetic.isMember(ItemFilterGenetic.java:36)
[08:38:07] [NEI Subset Item Allocation/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at forestry.core.recipes.nei.ItemFilterGenetic.matches(ItemFilterGenetic.java:45)
[08:38:07] [NEI Subset Item Allocation/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at codechicken.nei.SubsetWidget$UpdateStateTask.execute(SubsetWidget.java:534)
[08:38:07] [NEI Subset Item Allocation/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at codechicken.nei.RestartableTask$1.run(RestartableTask.java:24)
```

**Comment by Nedelosk** [comment]
I don't think that we will ever fix this so I close this.
