### ISSUE TITLE
World Crash Caused by Carpenter..

### ISSUE THREAD

**Issue by ghost** [ForestryMC/ForestryMC#1571]
can not open my world anymore =:(
here is the log file everytime i get:
---- Minecraft Crash Report ----

WARNING: coremods are present:
  ShetiPhian-ASM (shetiphiancore-1.11.0-3.4.1.jar)
  BCModPlugin (zz-backpacks 1.11.2 - 3.1.6.jar)
  MMFMLCorePlugin (MultiMine-1.11.2.jar)
  ServerPropertiesLAN (ServerPropertiesLAN-2.3.jar)
  FMLPlugin (InventoryTweaks-1.62-dev-75.jar)
  RebornCoreASM (RebornCore-1.11.2-2.13.0.12-universal.jar)
  IvToolkit (IvToolkit-1.3.1.jar)
Contact their authors BEFORE contacting forge

// On the bright side, I bought you a teddy bear!

Time: 1/17/17 8:57 PM
Description: Ticking block entity

java.lang.ArrayIndexOutOfBoundsException: 4
	at java.util.Arrays$ArrayList.get(Unknown Source)
	at net.minecraft.util.NonNullList.get(SourceFile:40)
	at forestry.core.utils.InventoryUtil.removeSets(InventoryUtil.java:269)
	at forestry.core.utils.InventoryUtil.removeSets(InventoryUtil.java:215)
	at forestry.factory.tiles.TileCarpenter.removeItemResources(TileCarpenter.java:189)
	at forestry.factory.tiles.TileCarpenter.workCycle(TileCarpenter.java:142)
	at forestry.core.tiles.TilePowered.updateServerSide(TilePowered.java:131)
	at forestry.factory.tiles.TileCarpenter.updateServerSide(TileCarpenter.java:130)
	at forestry.core.tiles.TileForestry.func_73660_a(TileForestry.java:85)
	at net.minecraft.world.World.func_72939_s(World.java:1801)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at java.util.Arrays$ArrayList.get(Unknown Source)
	at net.minecraft.util.NonNullList.get(SourceFile:40)
	at forestry.core.utils.InventoryUtil.removeSets(InventoryUtil.java:269)
	at forestry.core.utils.InventoryUtil.removeSets(InventoryUtil.java:215)
	at forestry.factory.tiles.TileCarpenter.removeItemResources(TileCarpenter.java:189)
	at forestry.factory.tiles.TileCarpenter.workCycle(TileCarpenter.java:142)
	at forestry.core.tiles.TilePowered.updateServerSide(TilePowered.java:131)
	at forestry.factory.tiles.TileCarpenter.updateServerSide(TileCarpenter.java:130)
	at forestry.core.tiles.TileForestry.func_73660_a(TileForestry.java:85)

-- Block entity being ticked --
Details:
	Name: minecraft:forestry.carpenter // forestry.factory.tiles.TileCarpenter
	Block type: ID #620 (tile.for.carpenter // forestry.factory.blocks.BlockFactoryTESR)
	Block data value: 4 / 0x4 / 0b0100
	Block location: World: (-171,71,-333), Chunk: (at 5,4,3 in -11,-21; contains blocks -176,0,-336 to -161,255,-321), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Actual block type: ID #620 (tile.for.carpenter // forestry.factory.blocks.BlockFactoryTESR)
	Actual block data value: 4 / 0x4 / 0b0100
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1801)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621)

-- Affected level --
Details:
	Level name: world
	All players: 1 total; [EntityPlayerMP['kenijey'/434, l='world', x=-180.46, y=71.00, z=-334.54]]
	Chunk stats: ServerChunkCache: 553 Drop: 0
	Level seed: 66879395171352347
	Level generator: ID 02 - largeBiomes, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-48,78,-64), Chunk: (at 0,4,0 in -3,-4; contains blocks -48,0,-64 to -33,255,-49), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 1444119 game time, 10192 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 79594 (now: false), thunder time: 13092 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_111, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1205257400 bytes (1149 MB) / 2174222336 bytes (2073 MB) up to 2863661056 bytes (2731 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3072m -XX:MaxPermSize=256m
	IntCache: cache: 0, tcache: 14, allocated: 0, tallocated: 16
	FML: MCP 9.38 Powered by Forge 13.20.0.2216 Optifine OptiFine_1.11.2_HD_U_B6

**Comment by Nedelosk** [comment]
#1568
