### ISSUE TITLE
Crash client

### ISSUE THREAD

**Issue by lerion13** [ForestryMC/ForestryMC#1598]
[crash-2017-02-15_10.54.53-client.txt](https://github.com/ForestryMC/ForestryMC/files/776021/crash-2017-02-15_10.54.53-client.txt)
It occurs when using fashion JEI - when viewing the craft.

mezz edit:
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  AppEngCore (appliedenergistics2-rv4-alpha-0.jar)
  NWRTweak (redstonepaste.jar)
  IC2core (industrialcraft-2-2.6.151-ex110.jar)
Contact their authors BEFORE contacting forge

// This doesn't make any sense!

Time: 2/15/17 10:54 AM
Description: Rendering item

java.lang.NullPointerException: Rendering item
	at forestry.core.models.ModelCrate$CrateOverrideList.handleItemState(ModelCrate.java:135)
	at sun.reflect.GeneratedMethodAccessor33.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at Reflector.call(Reflector.java:819)
	at net.minecraft.client.renderer.RenderItem.func_184393_a(RenderItem.java:363)
	at net.minecraft.client.renderer.RenderItem.func_184391_a(RenderItem.java:509)
	at mezz.jei.plugins.vanilla.ingredients.ItemStackRenderer.render(ItemStackRenderer.java:27)
	at mezz.jei.plugins.vanilla.ingredients.ItemStackRenderer.render(ItemStackRenderer.java:21)
	at mezz.jei.gui.ingredients.GuiIngredient.draw(GuiIngredient.java:148)
	at mezz.jei.gui.ingredients.GuiIngredientGroup.draw(GuiIngredientGroup.java:155)
	at mezz.jei.gui.recipes.RecipeLayout.draw(RecipeLayout.java:127)
	at mezz.jei.gui.recipes.RecipesGui.func_73863_a(RecipesGui.java:202)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)
	at sun.reflect.GeneratedMethodAccessor19.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at Reflector.callVoid(Reflector.java:512)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1398)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at launcher.client.ClientLauncher.launch(ClientLauncher.java:313)
	at launcher.client.ClientLauncher.main(ClientLauncher.java:196)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at forestry.core.models.ModelCrate$CrateOverrideList.handleItemState(ModelCrate.java:135)
	at sun.reflect.GeneratedMethodAccessor33.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at Reflector.call(Reflector.java:819)
	at net.minecraft.client.renderer.RenderItem.func_184393_a(RenderItem.java:363)

-- Item being rendered --
Details:
	Item Type: forestry.core.items.ItemCrated@710acdfd
	Item Aux: 0
	Item NBT: null
	Item Foil: false
Stacktrace:
	at net.minecraft.client.renderer.RenderItem.func_184391_a(RenderItem.java:509)
	at mezz.jei.plugins.vanilla.ingredients.ItemStackRenderer.render(ItemStackRenderer.java:27)
	at mezz.jei.plugins.vanilla.ingredients.ItemStackRenderer.render(ItemStackRenderer.java:21)
	at mezz.jei.gui.ingredients.GuiIngredient.draw(GuiIngredient.java:148)
	at mezz.jei.gui.ingredients.GuiIngredientGroup.draw(GuiIngredientGroup.java:155)
	at mezz.jei.gui.recipes.RecipeLayout.draw(RecipeLayout.java:127)
	at mezz.jei.gui.recipes.RecipesGui.func_73863_a(RecipesGui.java:202)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)
	at sun.reflect.GeneratedMethodAccessor19.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at Reflector.callVoid(Reflector.java:512)

-- Screen render details --
Details:
	Screen name: mezz.jei.gui.recipes.RecipesGui
	Mouse location: Scaled: (417, 53). Absolute: (835, 484)
	Screen size: Scaled: (556, 296). Absolute: (1111, 591). Scale factor of 2

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['lerion'/199, l='MpServer', x=5.97, y=136.00, z=0.08]]
	Chunk stats: MultiplayerChunkCache: 169, 169
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (0,157,2), Chunk: (at 0,9,2 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 30813424 game time, 6226025 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 65 total; [EntityArmorStand['§4§l/rtp - случайный телепорт по карте!'/130, l='MpServer', x=7.77, y=156.75, z=0.70], EntityArmorStand['§2§lКомната обменников'/131, l='MpServer', x=10.86, y=150.20, z=10.89], EntityPlayerSP['lerion'/199, l='MpServer', x=5.97, y=136.00, z=0.08], EntityItemFrame['entity.ItemFrame.name'/440237, l='MpServer', x=7.50, y=138.50, z=3.97], EntityArmorStand['§6Магазин блоков'/60, l='MpServer', x=-27.34, y=73.79, z=-19.51], EntityArmorStand['§2§lТелепорт в ад'/61, l='MpServer', x=-29.01, y=154.04, z=-9.13], EntityArmorStand['§2§lТелепорт в край'/62, l='MpServer', x=-27.60, y=153.68, z=-11.51], EntityItemFrame['entity.ItemFrame.name'/69, l='MpServer', x=-15.97, y=136.50, z=-0.50], EntityItemFrame['entity.ItemFrame.name'/70, l='MpServer', x=-14.97, y=136.50, z=-2.50], EntityItemFrame['entity.ItemFrame.name'/71, l='MpServer', x=-14.97, y=136.50, z=-4.50], EntityItemFrame['entity.ItemFrame.name'/72, l='MpServer', x=-13.50, y=136.50, z=-5.97], EntityItemFrame['entity.ItemFrame.name'/73, l='MpServer', x=-11.50, y=136.50, z=-5.97], EntityItemFrame['entity.ItemFrame.name'/74, l='MpServer', x=-3.03, y=136.50, z=-6.50], EntityItemFrame['entity.ItemFrame.name'/75, l='MpServer', x=-3.03, y=136.50, z=-4.50], EntityItemFrame['entity.ItemFrame.name'/76, l='MpServer', x=-4.50, y=136.50, z=-3.03], EntityItemFrame['entity.ItemFrame.name'/77, l='MpServer', x=-6.50, y=136.50, z=-3.03], EntityItemFrame['entity.ItemFrame.name'/78, l='MpServer', x=-7.97, y=136.50, z=-6.50], EntityItemFrame['entity.ItemFrame.name'/79, l='MpServer', x=-7.97, y=136.50, z=-8.50], EntityItemFrame['entity.ItemFrame.name'/187341, l='MpServer', x=1.50, y=138.50, z=-0.03], EntityItemFrame['entity.ItemFrame.name'/80, l='MpServer', x=-6.50, y=136.50, z=-9.97], EntityItemFrame['entity.ItemFrame.name'/355029, l='MpServer', x=5.50, y=138.50, z=3.97], EntityItemFrame['entity.ItemFrame.name'/81, l='MpServer', x=-4.50, y=136.50, z=-9.97], EntityItemFrame['entity.ItemFrame.name'/82, l='MpServer', x=-3.03, y=136.50, z=-8.50], EntityItemFrame['entity.ItemFrame.name'/83, l='MpServer', x=-6.50, y=136.50, z=-1.97], EntityItemFrame['entity.ItemFrame.name'/84, l='MpServer', x=-0.50, y=138.50, z=-0.03], EntityArmorStand['§4§l/rtp - случайный телепорт по карте!'/85, l='MpServer', x=-8.27, y=156.75, z=-0.01], EntityArmorStand['§2§lКомната обменников'/86, l='MpServer', x=-10.47, y=150.20, z=-10.51], EntityItemFrame['entity.ItemFrame.name'/87, l='MpServer', x=-14.97, y=136.50, z=3.50], EntityItemFrame['entity.ItemFrame.name'/88, l='MpServer', x=-15.97, y=136.50, z=1.50], EntityItemFrame['entity.ItemFrame.name'/89, l='MpServer', x=-14.97, y=136.50, z=5.50], EntityItemFrame['entity.ItemFrame.name'/90, l='MpServer', x=-13.50, y=136.50, z=6.97], EntityItemFrame['entity.ItemFrame.name'/91, l='MpServer', x=-11.50, y=136.50, z=6.97], EntityItemFrame['entity.ItemFrame.name'/92, l='MpServer', x=-6.50, y=136.50, z=5.03], EntityItemFrame['entity.ItemFrame.name'/93, l='MpServer', x=-4.50, y=136.50, z=5.03], EntityItemFrame['entity.ItemFrame.name'/94, l='MpServer', x=-3.03, y=136.50, z=6.50], EntityItemFrame['entity.ItemFrame.name'/95, l='MpServer', x=-3.03, y=136.50, z=8.50], EntityItemFrame['entity.ItemFrame.name'/96, l='MpServer', x=-4.50, y=136.50, z=11.97], EntityItemFrame['entity.ItemFrame.name'/97, l='MpServer', x=-2.50, y=136.50, z=12.97], EntityItemFrame['entity.ItemFrame.name'/98, l='MpServer', x=-1.97, y=136.50, z=8.50], EntityItemFrame['entity.ItemFrame.name'/99, l='MpServer', x=-1.97, y=136.50, z=6.50], EntityArmorStand['§2§lКомната обменников'/100, l='MpServer', x=-9.30, y=149.77, z=9.87], EntityArmorStand['§4Случайный телепорт - /rtp'/105, l='MpServer', x=0.68, y=155.25, z=-20.72], EntityItemFrame['entity.ItemFrame.name'/106, l='MpServer', x=7.50, y=136.50, z=-1.97], EntityItemFrame['entity.ItemFrame.name'/107, l='MpServer', x=5.50, y=136.50, z=-1.97], EntityItemFrame['entity.ItemFrame.name'/108, l='MpServer', x=15.97, y=136.50, z=-4.50], EntityItemFrame['entity.ItemFrame.name'/109, l='MpServer', x=0.50, y=138.50, z=-0.03], EntityArmorStand['§4§l/rtp - случайный телепорт по карте!'/110, l='MpServer', x=0.74, y=156.75, z=-7.55], EntityArmorStand['§aВедется набор стажеров на сервер!'/111, l='MpServer', x=0.37, y=156.38, z=-3.58], EntityArmorStand['§2§lКомната обменников'/112, l='MpServer', x=10.00, y=150.20, z=-8.92], EntityItemFrame['entity.ItemFrame.name'/113, l='MpServer', x=1.50, y=136.50, z=12.97], EntityItemFrame['entity.ItemFrame.name'/114, l='MpServer', x=2.97, y=136.50, z=6.50], EntityItemFrame['entity.ItemFrame.name'/115, l='MpServer', x=2.97, y=136.50, z=8.50], EntityItemFrame['entity.ItemFrame.name'/116, l='MpServer', x=8.97, y=136.50, z=10.50], EntityItemFrame['entity.ItemFrame.name'/117, l='MpServer', x=8.97, y=136.50, z=8.50], EntityItemFrame['entity.ItemFrame.name'/118, l='MpServer', x=5.50, y=136.50, z=5.03], EntityItemFrame['entity.ItemFrame.name'/119, l='MpServer', x=7.50, y=136.50, z=5.03], EntityItemFrame['entity.ItemFrame.name'/120, l='MpServer', x=4.03, y=136.50, z=6.50], EntityItemFrame['entity.ItemFrame.name'/121, l='MpServer', x=4.03, y=136.50, z=8.50], EntityItemFrame['entity.ItemFrame.name'/122, l='MpServer', x=5.50, y=136.50, z=11.97], EntityItemFrame['entity.ItemFrame.name'/123, l='MpServer', x=7.50, y=136.50, z=11.97], EntityItemFrame['entity.ItemFrame.name'/124, l='MpServer', x=12.50, y=136.50, z=6.97], EntityItemFrame['entity.ItemFrame.name'/231807, l='MpServer', x=-1.50, y=138.50, z=-0.03], EntityItemFrame['entity.ItemFrame.name'/125, l='MpServer', x=14.50, y=136.50, z=6.97], EntityItemFrame['entity.ItemFrame.name'/126, l='MpServer', x=15.97, y=136.50, z=5.50], EntityItemFrame['entity.ItemFrame.name'/127, l='MpServer', x=15.97, y=136.50, z=3.50]]
	Retry entities: 0 total; []
	Server brand: Waterfall (git:Waterfall-Bootstrap:1.11-SNAPSHOT:17f2ead:unknown) <- fml,forge,sponge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:524)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:392)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at launcher.client.ClientLauncher.launch(ClientLauncher.java:313)
	at launcher.client.ClientLauncher.main(ClientLauncher.java:196)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_66, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 194404472 bytes (185 MB) / 1056309248 bytes (1007 MB) up to 1056309248 bytes (1007 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=ThisTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1024M -XX:+AggressiveOpts -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:ParallelCMSThreads=2 -XX:ParallelGCThreads=2 -XX:+DisableAttachMechanism
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.32 Powered by Forge 12.18.3.2221 Optifine OptiFine_1.10.2_HD_U_D6 20 mods loaded, 20 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge.jar) 
	UCHIJA	Forge{12.18.3.2221} [Minecraft Forge] (forge.jar) 
	UCHIJA	appliedenergistics2-core{rv4-alpha-0} [Applied Energistics 2 Core] (minecraft.jar) 
	UCHIJA	IC2{2.6.151-ex110} [IndustrialCraft 2] (industrialcraft-2-2.6.151-ex110.jar) 
	UCHIJA	advanced_solar_panels{4.0.4} [Advanced Solar Panels] (Advanced Solar Panels-4.0.4.jar) 
	UCHIJA	appliedenergistics2{rv4-alpha-0} [Applied Energistics 2] (appliedenergistics2-rv4-alpha-0.jar) 
	UCHIJA	bdlib{1.12.2.20} [BD Lib] (bdlib-1.12.2.20-mc1.10.2.jar) 
	UCHIJA	ae2stuff{0.6.0.1} [AE2 Stuff] (ae2stuff-0.6.0.1-mc1.10.2.jar) 
	UCHIJA	XaeroBetterPvP{1.12.1} [Better PVP Mod] (BetterPvP_1.12.1_Forge_1.10.2.jar) 
	UCHIJA	customnpcs{1.10.2} [CustomNPCs] (CustomNPCs_1.10.2(20nov16).jar) 
	UCHIJA	JEI{3.14.6.408} [Just Enough Items] (jei_1.10.2-3.14.6.408.jar) 
	UCHIJA	FloodLights{1.2.7-145} [Flood Lights] (FloodLights-1.9.4-1.2.7-145.jar) 
	UCHIJA	forestry{5.2.17.362} [Forestry] (forestry_1.10.2-5.2.17.362.jar) 
	UCHIJA	gravisuite{3.0.1} [Gravitation Suite] (GravitationSuite.jar) 
	UCHIJA	ironchest{1.10.2-7.0.11.797} [Iron Chest] (ironchest-1.10.2-7.0.11.797.jar) 
	UCHIJA	reap{1.3.0} [Reap Mod] (reapmod-1.3.0.jar) 
	UCHIJA	redstonepaste{1.7.4} [Redstone Paste] (redstonepaste.jar) 
	UCHIJA	lerionaddon{0.1} [lerionaddon] (TrudioAddPlugins-1.0.jar) 
	UCHIJA	Waila{1.7.0} [Waila] (waila-1.10.2.jar) 
	Loaded coremods (and transformers): 
AppEngCore (appliedenergistics2-rv4-alpha-0.jar)
  appeng.coremod.transformer.ASMIntegration
NWRTweak (redstonepaste.jar)
  net.fybertech.nwr.NWRTransformer
IC2core (industrialcraft-2-2.6.151-ex110.jar)
  
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '3.3.11672 Compatibility Profile Context' Renderer: 'ATI Radeon 3000 Graphics'
	AE2 Version: alpha rv4-alpha-0 for Forge 12.18.3.2185
	List of loaded APIs: 
		* appliedenergistics2|API (rv4) from appliedenergistics2-rv4-alpha-0.jar
		* CoFHAPI (1.8.9R1.2.0B1) from FloodLights-1.9.4-1.2.7-145.jar
		* CoFHAPI|energy (1.8.9R1.2.0B1) from FloodLights-1.9.4-1.2.7-145.jar
		* Core (0.1) from CustomNPCs_1.10.2(20nov16).jar
		* Core|Blocks (0.1) from CustomNPCs_1.10.2(20nov16).jar
		* Core|Constants (0.1) from CustomNPCs_1.10.2(20nov16).jar
		* Core|Entities (0.1) from CustomNPCs_1.10.2(20nov16).jar
		* Core|Entities|Data (0.1) from CustomNPCs_1.10.2(20nov16).jar
		* Core|Entities|Data|Role (0.1) from CustomNPCs_1.10.2(20nov16).jar
		* Core|Events (0.1) from CustomNPCs_1.10.2(20nov16).jar
		* Core|Handlers (0.1) from CustomNPCs_1.10.2(20nov16).jar
		* Core|Handlers|Data (0.1) from CustomNPCs_1.10.2(20nov16).jar
		* ForestryAPI|apiculture (5.0.0) from forestry_1.10.2-5.2.17.362.jar
		* ForestryAPI|arboriculture (4.2.1) from forestry_1.10.2-5.2.17.362.jar
		* ForestryAPI|circuits (3.1.0) from forestry_1.10.2-5.2.17.362.jar
		* ForestryAPI|climate (2.1.0) from forestry_1.10.2-5.2.17.362.jar
		* ForestryAPI|core (5.1.0) from forestry_1.10.2-5.2.17.362.jar
		* ForestryAPI|farming (2.1.0) from forestry_1.10.2-5.2.17.362.jar
		* ForestryAPI|food (1.1.0) from forestry_1.10.2-5.2.17.362.jar
		* ForestryAPI|fuels (3.0.0) from forestry_1.10.2-5.2.17.362.jar
		* ForestryAPI|genetics (4.7.1) from forestry_1.10.2-5.2.17.362.jar
		* ForestryAPI|greenhouse (5.2.0) from forestry_1.10.2-5.2.17.362.jar
		* ForestryAPI|hives (4.1.0) from forestry_1.10.2-5.2.17.362.jar
		* ForestryAPI|lepidopterology (1.3.0) from forestry_1.10.2-5.2.17.362.jar
		* ForestryAPI|mail (3.1.0) from forestry_1.10.2-5.2.17.362.jar
		* ForestryAPI|multiblock (3.0.0) from forestry_1.10.2-5.2.17.362.jar
		* ForestryAPI|recipes (5.4.0) from forestry_1.10.2-5.2.17.362.jar
		* ForestryAPI|storage (5.0.0) from forestry_1.10.2-5.2.17.362.jar
		* ForestryAPI|world (2.1.0) from forestry_1.10.2-5.2.17.362.jar
		* JustEnoughItemsAPI (4.10.1) from jei_1.10.2-3.14.6.408.jar
		* WailaAPI (1.3) from waila-1.10.2.jar
	AE2 Integration: IC2:ON, RC:OFF, RF:OFF, RFItem:OFF, MFR:OFF, Waila:ON, InvTweaks:OFF, JEI:ON, Mekanism:OFF, OpenComputers:OFF, THE_ONE_PROBE:OFF
	Launched Version: 1.10.2
	LWJGL: 2.9.4
	OpenGL: ATI Radeon 3000 Graphics GL version 3.3.11672 Compatibility Profile Context, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: F32-1.10.2.zip
	Current Language: Русский (Россия)
	Profiler Position: N/A (disabled)
	CPU: 4x AMD FX(tm)-4100 Quad-Core Processor 
	OptiFine Version: OptiFine_1.10.2_HD_U_D6
	Render Distance Chunks: 18
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 3.3.11672 Compatibility Profile Context
	OpenGlRenderer: ATI Radeon 3000 Graphics
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 4
```

**Comment by ghost** [comment]
Having this issue in 1.12; 
[crash-2017-08-13_16.32.30-client.txt](https://github.com/ForestryMC/ForestryMC/files/1220547/crash-2017-08-13_16.32.30-client.txt)

**Comment by Nedelosk** [comment]
@Draylynn Can you please test it with the newest version and post the message that will appear in the log ?

**Comment by ghost** [comment]
Sorry for the delay, been busy.
[Forestry-1.12-5.5.0.163]: not crashing anymore (yay), just missing all crate items (except the empty crate)  from forestry in JEI (attached log). Is this now JEI's issue?
[fml-client-latest.TXT](https://github.com/ForestryMC/ForestryMC/files/1229335/fml-client-latest.TXT)

**Comment by Nedelosk** [comment]
@Draylynn The bug is not fixed. You only had luck, because you have looked in jei and not in the forestry creative tab. But that is probable because we not have released the newest version. @mezz First has to upload a new jar file to curseforge.

**Comment by mezz** [comment]
Forestry gets auto-uploaded to curseforge all the time, I think the fix is in the version they are using.

**Comment by Nedelosk** [comment]
@mezz I was confused by the jenkins name. And the build script was broken.
@Draylynn The bug should now be fixed.

**Comment by ghost** [comment]
I popped in creative this time (was luck, looking through JEI was randomly triggering the crash), no crashes in creative (yet) and all the crates have appeared in JEI. =big hugs!=
