### ISSUE TITLE
Broken Oredictionary Registration 

### ISSUE THREAD

**Issue by greatkronos** [ForestryMC/ForestryMC#1876]
[20:50:30] [Server thread/WARN] [FML]: ****************************************
[20:50:30] [Server thread/WARN] [FML]: ****************************************
[20:50:30] [Server thread/WARN] [FML]: * A broken ore dictionary registration with name cropChestnut has occurred. It adds an item (type: class forestry.core.items.ItemFruit) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
TO USERS: YES this is a BUG in the mod Forestry for Minecraft report it to them!
[20:50:30] [Server thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:534)
[20:50:30] [Server thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:501)
[20:50:30] [Server thread/WARN] [FML]: *  at forestry.core.items.ItemFruit.registerOreDictionary(ItemFruit.java:73)
[20:50:30] [Server thread/WARN] [FML]: *  at forestry.core.items.ItemFruit.<init>(ItemFruit.java:68)
[20:50:30] [Server thread/WARN] [FML]: *  at forestry.plugins.PluginCore.registerItems(PluginCore.java:286)
[20:50:30] [Server thread/WARN] [FML]: *  at forestry.plugins.PluginManager.runPreInit(PluginManager.java:265)...
[20:50:30] [Server thread/WARN] [FML]: ****************************************
[20:50:30] [Server thread/WARN] [FML]: ****************************************
[20:50:30] [Server thread/WARN] [FML]: * A broken ore dictionary registration with name cropLemon has occurred. It adds an item (type: class forestry.core.items.ItemFruit) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
TO USERS: YES this is a BUG in the mod Forestry for Minecraft report it to them!
[20:50:30] [Server thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:534)
[20:50:30] [Server thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:501)
[20:50:30] [Server thread/WARN] [FML]: *  at forestry.core.items.ItemFruit.registerOreDictionary(ItemFruit.java:73)
[20:50:30] [Server thread/WARN] [FML]: *  at forestry.core.items.ItemFruit.<init>(ItemFruit.java:68)
[20:50:30] [Server thread/WARN] [FML]: *  at forestry.plugins.PluginCore.registerItems(PluginCore.java:286)
[20:50:30] [Server thread/WARN] [FML]: *  at forestry.plugins.PluginManager.runPreInit(PluginManager.java:265)...
[20:50:30] [Server thread/WARN] [FML]: ****************************************
[20:50:30] [Server thread/WARN] [FML]: ****************************************
[20:50:30] [Server thread/WARN] [FML]: * A broken ore dictionary registration with name cropPlum has occurred. It adds an item (type: class forestry.core.items.ItemFruit) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
TO USERS: YES this is a BUG in the mod Forestry for Minecraft report it to them!
[20:50:30] [Server thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:534)
[20:50:30] [Server thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:501)
[20:50:30] [Server thread/WARN] [FML]: *  at forestry.core.items.ItemFruit.registerOreDictionary(ItemFruit.java:73)
[20:50:30] [Server thread/WARN] [FML]: *  at forestry.core.items.ItemFruit.<init>(ItemFruit.java:68)
[20:50:30] [Server thread/WARN] [FML]: *  at forestry.plugins.PluginCore.registerItems(PluginCore.java:286)
[20:50:30] [Server thread/WARN] [FML]: *  at forestry.plugins.PluginManager.runPreInit(PluginManager.java:265)...
[20:50:30] [Server thread/WARN] [FML]: ****************************************
[20:50:30] [Server thread/WARN] [FML]: ****************************************
[20:50:30] [Server thread/WARN] [FML]: * A broken ore dictionary registration with name cropDate has occurred. It adds an item (type: class forestry.core.items.ItemFruit) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
TO USERS: YES this is a BUG in the mod Forestry for Minecraft report it to them!
[20:50:30] [Server thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:534)
[20:50:30] [Server thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:501)
[20:50:30] [Server thread/WARN] [FML]: *  at forestry.core.items.ItemFruit.registerOreDictionary(ItemFruit.java:73)
[20:50:30] [Server thread/WARN] [FML]: *  at forestry.core.items.ItemFruit.<init>(ItemFruit.java:68)
[20:50:30] [Server thread/WARN] [FML]: *  at forestry.plugins.PluginCore.registerItems(PluginCore.java:286)
[20:50:30] [Server thread/WARN] [FML]: *  at forestry.plugins.PluginManager.runPreInit(PluginManager.java:265)...
[20:50:30] [Server thread/WARN] [FML]: ****************************************
[20:50:30] [Server thread/WARN] [FML]: ****************************************
[20:50:30] [Server thread/WARN] [FML]: * A broken ore dictionary registration with name cropPapaya has occurred. It adds an item (type: class forestry.core.items.ItemFruit) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
TO USERS: YES this is a BUG in the mod Forestry for Minecraft report it to them!
[20:50:30] [Server thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:534)
[20:50:30] [Server thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:501)
[20:50:30] [Server thread/WARN] [FML]: *  at forestry.core.items.ItemFruit.registerOreDictionary(ItemFruit.java:73)
[20:50:30] [Server thread/WARN] [FML]: *  at forestry.core.items.ItemFruit.<init>(ItemFruit.java:68)
[20:50:30] [Server thread/WARN] [FML]: *  at forestry.plugins.PluginCore.registerItems(PluginCore.java:286)
[20:50:30] [Server thread/WARN] [FML]: *  at forestry.plugins.PluginManager.runPreInit(PluginManager.java:265)...
[20:50:30] [Server thread/WARN] [FML]: ****************************************

**Comment by Nedelosk** [comment]
Which forestry version do you use ?
