### ISSUE TITLE
Crated "Item" tooltip error

### ISSUE THREAD

**Issue by MrMcFancyPants** [ForestryMC/ForestryMC#1877]
java.lang.NullPointerException: null
[17:14:40] [main/ERROR]: Failed to get tooltip: 1xitem.crated.natura.edibles.5@0 forestry:crated.natura.edibles.5
that is the term of the log.

Failed to get tooltip: 1xitem.crated.natura.edibles.5@0 forestry:crated.natura.edibles.5
java.lang.NullPointerException: null
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:881) ~[aip.class:?]
	at mezz.jei.plugins.vanilla.ingredients.ItemStackRenderer.getTooltip(ItemStackRenderer.java:39) [ItemStackRenderer.class:?]
	at mezz.jei.plugins.vanilla.ingredients.ItemStackRenderer.getTooltip(ItemStackRenderer.java:20) [ItemStackRenderer.class:?]
	at mezz.jei.render.IngredientRenderer.getIngredientTooltipSafe(IngredientRenderer.java:148) [IngredientRenderer.class:?]
	at mezz.jei.render.IngredientRenderer.getTooltip(IngredientRenderer.java:119) [IngredientRenderer.class:?]
	at mezz.jei.render.IngredientRenderer.drawTooltip(IngredientRenderer.java:89) [IngredientRenderer.class:?]
	at mezz.jei.gui.overlay.IngredientGrid.drawTooltips(IngredientGrid.java:108) [IngredientGrid.class:?]
	at mezz.jei.gui.overlay.IngredientListOverlay.drawTooltips(IngredientListOverlay.java:197) [IngredientListOverlay.class:?]
	at mezz.jei.gui.GuiEventHandler.onDrawScreenEventPost(GuiEventHandler.java:98) [GuiEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_781_GuiEventHandler_onDrawScreenEventPost_Post.invoke(.dynamic) [?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179) [EventBus.class:?]
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:350) [ForgeHooksClient.class:?]
	at sun.reflect.GeneratedMethodAccessor25.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at Reflector.callVoid(Reflector.java:555) [Reflector.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1449) [buq.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[17:14:38] [main/ERROR]: Failed to get tooltip: 1xitem.crated.natura.edibles.5@0 forestry:crated.natura.edibles.5

**Comment by Nedelosk** [comment]
Same as #1920
