### ISSUE TITLE
Server Crash on several Bee Effects

### ISSUE THREAD

**Issue by TheFlipflop** [ForestryMC/ForestryMC#1899]
The Whole Server Crashes (forestry_1.12.2-5.7.0.212) on several Bee Effects in Modern Skyblock 2

Bees that crashes when trying to render the Bee effect (the moment you put them into apiary server crashes immidiatly)

Only /setblock x y z air with the location of the apiary put the server out of the crashloop.

Broken Bees we found so far:

amped, pyro, cryo

----------------- 
```
Thread: Server thread
Stacktrace:
	at magicbees.elec332.corerepack.compat.forestry.allele.AlleleEffectThrottled.isThrottled(AlleleEffectThrottled.java:54)
	at magicbees.elec332.corerepack.compat.forestry.allele.AlleleEffectThrottled.doEffect(AlleleEffectThrottled.java:42)
	at forestry.apiculture.genetics.Bee.doEffect(Bee.java:187)
	at forestry.apiculture.genetics.Bee.doEffect(Bee.java:168)
	at forestry.apiculture.BeekeepingLogic.queenWorkTick(BeekeepingLogic.java:275)
	at forestry.apiculture.BeekeepingLogic.doWork(BeekeepingLogic.java:252)
	at net.bdew.gendustry.machines.apiary.TileApiary$$anonfun$2$$anonfun$apply$mcV$sp$1.apply$mcV$sp(TileApiary.scala:137)
	at net.bdew.gendustry.machines.apiary.TileApiary$$anonfun$2$$anonfun$apply$mcV$sp$1.apply(TileApiary.scala:129)
	at net.bdew.gendustry.machines.apiary.TileApiary$$anonfun$2$$anonfun$apply$mcV$sp$1.apply(TileApiary.scala:129)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at net.bdew.gendustry.misc.DataSlotErrorStates.withSuspendedUpdates(DataSlotErrorStates.scala:80)
	at net.bdew.gendustry.machines.apiary.TileApiary$$anonfun$2.apply$mcV$sp(TileApiary.scala:129)
	at net.bdew.lib.Event0$$anonfun$trigger$1.apply(Event.scala:19)
	at net.bdew.lib.Event0$$anonfun$trigger$1.apply(Event.scala:19)
	at scala.collection.immutable.List.foreach(List.scala:383)
	at net.bdew.lib.Event0.trigger(Event.scala:19)
	at net.bdew.lib.tile.TileTicking$class.update(TileTicking.scala:24)
	at net.bdew.gendustry.machines.apiary.TileApiary.func_73660_a(TileApiary.scala:44)

-- Block entity being ticked --
Details:
	Name: gendustry:industrial_apiary // net.bdew.gendustry.machines.apiary.TileApiary
	Block type: ID #1149 (tile.gendustry.industrial_apiary // net.bdew.gendustry.machines.apiary.BlockApiary$)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-2059,41,-972), Chunk: (at 5,2,4 in -129,-61; contains blocks -2064,0,-976 to -2049,255,-961), Region: (-5,-2; contains chunks -160,-64 to -129,-33, blocks -2560,0,-1024 to -2049,255,-513)
	Actual block type: ID #1149 (tile.gendustry.industrial_apiary // net.bdew.gendustry.machines.apiary.BlockApiary$)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1829)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:612)

```

**Comment by mezz** [comment]
Thanks for the report!
The amped bee is from Magic Bees, reported here: https://github.com/ForestryMC/MagicBees/issues/40
pyro is also from Magic Bees.
I am not sure which mod the cryo bee is from.
If you update to the latest versions of Forge, Forestry, and JEI, it should show the correct mod name on the tooltip for the bee.
