### ISSUE TITLE
[1.12.2] 'fieldSize is too long! Length is #####, but maximum is 128'

### ISSUE THREAD

**Issue by Rumpelstiltskinny** [ForestryMC/ForestryMC#1912]
I find nothing in the changelogs or issue tracker concerning 'fieldSize'. I am getting client disconnects for over sized packets. It is not crashing the server. However I will attempt the latest forestry version, currently 5.7.0.217.

I was not getting these errors when using forestry 5.7.0.212 prior to updating.

MC 1.12.2
forge-1.12.2-14.23.1.2577-installer
forestry_1.12.2-5.7.0.215
binnie-mods-1.12.2-2.5.0.97

relevant paste from log is:

```
java.util.concurrent.ExecutionException: net.minecraft.util.ReportedException: Loading NBT data
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_151]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_151]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1086) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_151]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: net.minecraft.util.ReportedException: Loading NBT data
	at net.minecraft.nbt.CompressedStreamTools.func_152455_a(CompressedStreamTools.java:141) ~[gi.class:?]
	at net.minecraft.nbt.CompressedStreamTools.func_152456_a(CompressedStreamTools.java:88) ~[gi.class:?]
	at net.minecraft.network.PacketBuffer.func_150793_b(PacketBuffer.java:315) ~[gy.class:?]
	at forestry.core.network.packets.PacketGenomeTrackerSync$Handler.onPacketData(PacketGenomeTrackerSync.java:52) ~[PacketGenomeTrackerSync$Handler.class:?]
	at forestry.core.network.PacketHandler.lambda$checkThreadAndEnqueue$0(PacketHandler.java:76) ~[PacketHandler.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_151]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_151]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 9 more
Caused by: java.io.EOFException: fieldSize is too long! Length is 67407, but maximum is 128
	at io.netty.buffer.ByteBufInputStream.checkAvailable(ByteBufInputStream.java:313) ~[ByteBufInputStream.class:4.1.9.Final]
	at io.netty.buffer.ByteBufInputStream.readFully(ByteBufInputStream.java:233) ~[ByteBufInputStream.class:4.1.9.Final]
	at io.netty.buffer.ByteBufInputStream.readFully(ByteBufInputStream.java:228) ~[ByteBufInputStream.class:4.1.9.Final]
	at net.minecraft.nbt.NBTTagByteArray.func_152446_a(SourceFile:53) ~[fw.class:?]
	at net.minecraft.nbt.CompressedStreamTools.func_152455_a(CompressedStreamTools.java:133) ~[gi.class:?]
	at net.minecraft.nbt.CompressedStreamTools.func_152456_a(CompressedStreamTools.java:88) ~[gi.class:?]
	at net.minecraft.network.PacketBuffer.func_150793_b(PacketBuffer.java:315) ~[gy.class:?]
	at forestry.core.network.packets.PacketGenomeTrackerSync$Handler.onPacketData(PacketGenomeTrackerSync.java:52) ~[PacketGenomeTrackerSync$Handler.class:?]
	at forestry.core.network.PacketHandler.lambda$checkThreadAndEnqueue$0(PacketHandler.java:76) ~[PacketHandler.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_151]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_151]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 9 more

```

**Comment by Rumpelstiltskinny** [comment]
update:

upgraded forestry to 5.7.0.217

now getting IllegalReferenceCountException

```[11:34:28] [main/FATAL]: Error executing task
java.util.concurrent.ExecutionException: io.netty.util.IllegalReferenceCountException: refCnt: 0
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_151]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_151]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1086) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_151]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: io.netty.util.IllegalReferenceCountException: refCnt: 0
	at io.netty.buffer.AbstractByteBuf.ensureAccessible(AbstractByteBuf.java:1408) ~[AbstractByteBuf.class:4.1.9.Final]
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1394) ~[AbstractByteBuf.class:4.1.9.Final]
	at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:687) ~[AbstractByteBuf.class:4.1.9.Final]
	at net.minecraft.network.PacketBuffer.readByte(PacketBuffer.java:864) ~[gy.class:?]
	at net.minecraft.network.PacketBuffer.readByte(PacketBuffer.java:864) ~[gy.class:?]
	at net.minecraft.network.PacketBuffer.func_150793_b(PacketBuffer.java:303) ~[gy.class:?]
	at forestry.core.network.packets.PacketGenomeTrackerSync$Handler.onPacketData(PacketGenomeTrackerSync.java:52) ~[PacketGenomeTrackerSync$Handler.class:?]
	at forestry.core.network.PacketHandler.lambda$checkThreadAndEnqueue$0(PacketHandler.java:76) ~[PacketHandler.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_151]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_151]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 9 more
[11:34:28] [main/FATAL]: Error executing task
java.util.concurrent.ExecutionException: io.netty.util.IllegalReferenceCountException: refCnt: 0
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_151]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_151]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1086) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_151]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: io.netty.util.IllegalReferenceCountException: refCnt: 0
	at io.netty.buffer.AbstractByteBuf.ensureAccessible(AbstractByteBuf.java:1408) ~[AbstractByteBuf.class:4.1.9.Final]
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1394) ~[AbstractByteBuf.class:4.1.9.Final]
	at io.netty.buffer.AbstractByteBuf.readInt(AbstractByteBuf.java:766) ~[AbstractByteBuf.class:4.1.9.Final]
	at net.minecraft.network.PacketBuffer.readInt(PacketBuffer.java:914) ~[gy.class:?]
	at net.minecraft.network.PacketBuffer.readInt(PacketBuffer.java:914) ~[gy.class:?]
	at forestry.mail.network.packets.PacketPOBoxInfoResponse$Handler.onPacketData(PacketPOBoxInfoResponse.java:49) ~[PacketPOBoxInfoResponse$Handler.class:?]
	at forestry.core.network.PacketHandler.lambda$checkThreadAndEnqueue$0(PacketHandler.java:76) ~[PacketHandler.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_151]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_151]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 9 more
```

...somebody has been playing with the mailbox code :) ask for further details if needed. Meanwhile I may rollback to 5.7.0.212 as I was not getting these errors and disconnects.
