### ISSUE TITLE
Crated items do not work properly on dedicated servers but work fine in single player

### ISSUE THREAD

**Issue by superfluke** [ForestryMC/ForestryMC#1920]
Forestry: forestry_1.12.2-5.7.0.218
Forge: forge-1.12.2-14.23.1.2575

Tested in a pack with only JEI and Forestry. No crash. Crated items from forestry work fine in single player but appear like this on a server:
![image](https://user-images.githubusercontent.com/20022336/34191899-81d22856-e518-11e7-86a9-b3b0c8727d52.png)
This is what shows in the log when hovering over one of those broken crate items:
```
[23:36:38] [main/ERROR] [jei/]: Failed to get tooltip: 1xitem.crated.stoneDiorite@0 forestry:crated.stonediorite
java.lang.NullPointerException: null
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:881) ~[aip.class:?]
	at mezz.jei.plugins.vanilla.ingredients.ItemStackRenderer.getTooltip(ItemStackRenderer.java:39) [ItemStackRenderer.class:?]
	at mezz.jei.plugins.vanilla.ingredients.ItemStackRenderer.getTooltip(ItemStackRenderer.java:20) [ItemStackRenderer.class:?]
	at mezz.jei.gui.ingredients.GuiIngredient.drawTooltip(GuiIngredient.java:175) [GuiIngredient.class:?]
	at mezz.jei.gui.ingredients.GuiIngredient.drawOverlays(GuiIngredient.java:158) [GuiIngredient.class:?]
	at mezz.jei.gui.recipes.RecipeLayout.drawOverlays(RecipeLayout.java:189) [RecipeLayout.class:?]
	at mezz.jei.gui.recipes.RecipesGui.func_73863_a(RecipesGui.java:216) [RecipesGui.class:?]
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:366) [ForgeHooksClient.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124) [buq.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_151]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_151]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
```

**Comment by temp1011** [comment]
Might be worth creating an issue on JEI as well (although I think mezz works on both repositories) since the error stack doesn't explicitly mention forestry but does mention JEI.
EDIT: https://github.com/ForestryMC/ForestryMC/issues/1598 still lurking around?

**Comment by Nedelosk** [comment]
@mezz Any idea ?

**Comment by superfluke** [comment]
This isn't just a tooltip error, the crates cannot be crafted at all on a server

**Comment by superfluke** [comment]
Video of crates not being craftable: https://www.twitch.tv/videos/211163533?t=06h31m09s

**Comment by temp1011** [comment]
What was up with the progress bar in the carpenter when it was open? Looked like it was stuck halfway or is that just a visual glitch?
