### ISSUE TITLE
More invalid properties from BuildCraft

### ISSUE THREAD

**Issue by jkroepke** [ForestryMC/ForestryMC#1925]
Hi,

looks like the same like here:  https://github.com/ForestryMC/ForestryMC/commit/5a10d8a0b2e2f6cef62cdd81cf06219604407eca

```
[19:22:33] [Server thread/ERROR] [BuildCraft]: [transport.facade] Invalid property!
java.lang.RuntimeException: Invalid property value detected!
  Property class = class forestry.arboriculture.blocks.PropertyTree
```

Thanks!

**Comment by temp1011** [comment]
Were you using the version of forestry where this was (hopefully) fixed when this happened?

**Comment by jkroepke** [comment]
5.7.0.219.

Curse says it should be fixed. https://minecraft.curseforge.com/projects/forestry/files/2514000 but its still happend.

Anyway, I post the wrong error her. I updated the OP.

**Comment by Nedelosk** [comment]
@jkroepke I can't find this error in my log. Are you sure you updated forestry ?

**Comment by temp1011** [comment]
I can't find this problem anywhere either.

**Comment by 3TUSK** [comment]
Can reliably replicate this issue with the following settings:

  * BuildCraft 7.99.16
  * Forestry 5.8.0.263
  * Binnie 1.12.2-2.5.0.161
  * MinecraftForge 14.23.2.2654

````
[21:51:38] [main/ERROR] [BuildCraft]: [silicon.facade] Invalid property!
java.lang.RuntimeException: Invalid property value detected!
  Property class = class forestry.arboriculture.blocks.PropertyTree
  Property = PropertyTree{name=tree, clazz=interface forestry.api.arboriculture.IAlleleTreeSpecies, values=[forestry.treeOak, forestry.treeDarkOak, forestry.treeBirch, forestry.treeLime, forestry.treeWalnut, forestry.treeChestnut, forestry.treeCherry, forestry.treeLemon, forestry.treePlum, forestry.treeMaple, forestry.treeSpruce, forestry.treeLarch, forestry.treePine, forestry.treeSequoia, forestry.treeGigant, forestry.treeJungle, forestry.treeTeak, forestry.treeIpe, forestry.treeKapok, forestry.treeEbony, forestry.treeZebrawood, forestry.treeMahogony, forestry.treeAcaciaVanilla, forestry.treeAcacia, forestry.treePadauk, forestry.treeBalsa, forestry.treeCocobolo, forestry.treeWenge, forestry.treeBaobab, forestry.treeMahoe, forestry.treeWillow, forestry.treeSipiri, forestry.treePapaya, forestry.treeDate, forestry.treePoplar, orchardapple, sweetcrabapple, floweringcrabapple, prairiecrabapple, blackthorn, cherryplum, peach, nectarine, apricot, almond, wildcherry, sourcherry, blackcherry, orange, manderin, satsuma, tangerine, lime, keylime, fingerlime, pomelo, grapefruit, kumquat, citron, buddhahand, banana, redbanana, plantain, butternut, rowan, hemlock, ash, alder, beech, copperbeech, aspen, yew, cypress, douglasfir, hazel, sycamore, whitebeam, hawthorn, pecan, elm, elder, holly, hornbeam, sallow, acornoak, fir, cedar, olive, redmaple, balsamfir, loblollypine, sweetgum, locust, pear, osangeorange, oldfustic, brazilwood, logwood, rosewood, purpleheart, iroko, gingko, brazilnut, rosegum, swampgum, box, clove, coffee, monkeypuzzle, rainbowgum, pinkivory, blackcurrant, redcurrant, blackberry, raspberry, blueberry, cranberry, juniper, gooseberry, goldenraspberry, cinnamon, coconut, cashew, avacado, nutmeg, allspice, chilli, staranise, mango, starfruit, candlenut, dwarfhazel]}
  Possible Values = [forestry.treeOak, forestry.treeDarkOak, forestry.treeBirch, forestry.treeLime, forestry.treeWalnut, forestry.treeChestnut, forestry.treeCherry, forestry.treeLemon, forestry.treePlum, forestry.treeMaple, forestry.treeSpruce, forestry.treeLarch, forestry.treePine, forestry.treeSequoia, forestry.treeGigant, forestry.treeJungle, forestry.treeTeak, forestry.treeIpe, forestry.treeKapok, forestry.treeEbony, forestry.treeZebrawood, forestry.treeMahogony, forestry.treeAcaciaVanilla, forestry.treeAcacia, forestry.treePadauk, forestry.treeBalsa, forestry.treeCocobolo, forestry.treeWenge, forestry.treeBaobab, forestry.treeMahoe, forestry.treeWillow, forestry.treeSipiri, forestry.treePapaya, forestry.treeDate, forestry.treePoplar, orchardapple, sweetcrabapple, floweringcrabapple, prairiecrabapple, blackthorn, cherryplum, peach, nectarine, apricot, almond, wildcherry, sourcherry, blackcherry, orange, manderin, satsuma, tangerine, lime, keylime, fingerlime, pomelo, grapefruit, kumquat, citron, buddhahand, banana, redbanana, plantain, butternut, rowan, hemlock, ash, alder, beech, copperbeech, aspen, yew, cypress, douglasfir, hazel, sycamore, whitebeam, hawthorn, pecan, elm, elder, holly, hornbeam, sallow, acornoak, fir, cedar, olive, redmaple, balsamfir, loblollypine, sweetgum, locust, pear, osangeorange, oldfustic, brazilwood, logwood, rosewood, purpleheart, iroko, gingko, brazilnut, rosegum, swampgum, box, clove, coffee, monkeypuzzle, rainbowgum, pinkivory, blackcurrant, redcurrant, blackberry, raspberry, blueberry, cranberry, juniper, gooseberry, goldenraspberry, cinnamon, coconut, cashew, avacado, nutmeg, allspice, chilli, staranise, mango, starfruit, candlenut, dwarfhazel]
  Value Name = lime
  Value (original) = forestry.treeLime
  Value (parsed) = lime
  Value class (original) = class forestry.arboriculture.genetics.alleles.AlleleTreeSpecies
  Value class (parsed) = class forestry.arboriculture.genetics.alleles.AlleleTreeSpecies

	at buildcraft.silicon.plug.FacadeStateManager.doesPropertyConform(FacadeStateManager.java:383) [FacadeStateManager.class:?]
	at buildcraft.silicon.plug.FacadeStateManager.init(FacadeStateManager.java:221) [FacadeStateManager.class:?]
	at buildcraft.silicon.BCSilicon.init(BCSilicon.java:70) [BCSilicon.class:?]
````

Let me know if you need more information.

**Comment by temp1011** [comment]
It's Binnie trees that are causing the problem. I don't know if the issue is with forestry or binnie though or who it should be solved by.

**Comment by MarshTheBacca** [comment]
I'm having a similar issue but it seems to be related to ExtraUtils.

Here's my paste of the error logs: https://pastebin.com/JQAWFtUL
Should I report this to ExtraUtil's team or is this BC's fault?
