### ISSUE TITLE
1.12.2: java.util.ConcurrentModificationException from forestry.lepidopterology.entities.AIButterflyMate.canInteract

### ISSUE THREAD

**Issue by jkroepke** [ForestryMC/ForestryMC#1929]
Crash Log: https://pastebin.com/F1SzMZZ1

```
Description: Ticking entity
 
java.util.ConcurrentModificationException
    at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:907)
    at java.util.ArrayList$Itr.next(ArrayList.java:857)
    at net.minecraft.world.World.func_72907_a(World.java:3122)
    at forestry.lepidopterology.entities.AIButterflyMate.canInteract(AIButterflyMate.java:41)
    at forestry.lepidopterology.entities.AIButterflyInteract.func_75250_a(AIButterflyInteract.java:40)
    at forestry.lepidopterology.entities.AIButterflyMate.func_75250_a(AIButterflyMate.java:76)
    at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:94)
    at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:763)
    at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2350)
    at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)
    at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2170)
    at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
    at forestry.lepidopterology.entities.EntityButterfly.func_70071_h_(EntityButterfly.java:456)
    at net.minecraft.world.World.func_72866_a(World.java:1990)
    at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:831)
    at net.minecraft.world.World.func_72870_g(World.java:1952)
    at net.minecraft.world.World.func_72939_s(World.java:1756)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:612)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
    at java.lang.Thread.run(Thread.java:748)
```

**Comment by temp1011** [comment]
If I'm understanding correctly (which might not be the case) I think this just needs a world isremote check somewhere, but equally it could be more complicated than that.

**Comment by jkroepke** [comment]
Hi!

It might be the amount of mods installed on the server. After reduce the mods (some technical non related forestry) the error does not appear anymore.
