### ISSUE TITLE
Farm multiblock causing chunks to be loaded

### ISSUE THREAD

**Issue by tornewuff** [ForestryMC/ForestryMC#1972]
I'm trying to debug issues on my server with chunks being constantly loaded and unloaded when no players are online and no chunkloaders are in use, and after writing a small mod to log chunk load events with stack traces it appears that one of the (several) mods doing this is Forestry. The stack I see repeatedly in the log is:

```
at net.minecraft.world.chunk.Chunk.onLoad(Chunk.java:920)
at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:105)
at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:94)
at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:130)
at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:101)
at net.minecraft.world.gen.ChunkProviderServer.provideChunk(ChunkProviderServer.java:147)
at net.minecraft.world.World.getChunkFromChunkCoords(World.java:361)
at net.minecraft.world.World.getChunkFromBlockCoords(World.java:353)
at net.minecraft.world.World.getBlockState(World.java:994)
at forestry.farming.logic.FarmLogicHomogeneous.maintainSoil(FarmLogicHomogeneous.java:105)
at forestry.farming.logic.FarmLogicHomogeneous.cultivate(FarmLogicHomogeneous.java:91)
at forestry.farming.multiblock.FarmController.cultivateTarget(FarmController.java:657)
at forestry.farming.multiblock.FarmController.cultivateTargets(FarmController.java:642)
at forestry.farming.multiblock.FarmController.doWork(FarmController.java:484)
at forestry.farming.tiles.TileFarmGearbox.updateServer(TileFarmGearbox.java:77)
at forestry.farming.multiblock.FarmController.updateServer(FarmController.java:274)
at forestry.core.multiblock.MultiblockControllerBase.updateMultiblockEntity(MultiblockControllerBase.java:445)
at forestry.core.multiblock.MultiblockWorldRegistry.tickStart(MultiblockWorldRegistry.java:81)
at forestry.core.multiblock.MultiblockRegistry.tickStart(MultiblockRegistry.java:31)
at forestry.core.multiblock.MultiblockServerTickHandler.onWorldTick(MultiblockServerTickHandler.java:20)
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_477_MultiblockServerTickHandler_onWorldTick_WorldTickEvent.invoke(.dynamic)
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
at net.minecraftforge.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:285)
at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:825)
at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:414)
at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:741)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:590)
at java.lang.Thread.run(Thread.java:748)
```

It looks like the farm controller isn't checking if its own chunk, or the chunks of the blocks it's interacting with, are loaded before it ticks? Not sure if this also applies to other forestry multiblocks as I don't currently have any on my server.

The chunks are unloaded again after the usual cache timeout and then reloaded the next time the farm ticks.

**Comment by tornewuff** [comment]
Oh, sorry, forgot to mention: I'm using Forestry 1.12.2-5.7.0.238 on Forge 1.12.2-14.23.1.2587.

**Comment by temp1011** [comment]
I'm not very familiar with the code myself but I think this may be the relevant part https://github.com/ForestryMC/ForestryMC/blob/d48fca46522e94a65dce64f1699bea121914f3ee/src/main/java/forestry/core/multiblock/MultiblockControllerBase.java#L445-L463. From what I can see there is a loaded chunk check so I'm not sure what's going on. 

EDIT: Nevermind, probably needs something doing https://github.com/ForestryMC/ForestryMC/blob/d48fca46522e94a65dce64f1699bea121914f3ee/src/main/java/forestry/farming/multiblock/FarmController.java#L260

**Comment by tornewuff** [comment]
By the time it's deciding whether or not it needs to save data it's too late, alas. The call to updateServer already caused the farm chunks to be loaded, to check if they need harvesting/planting/etc - so even if updateServer returns false to indicate that nothing was actually done and nothing needs to save, the chunks will still load and unload again.

The multiblock code does look like it's paying attention to whether the chunk(s) containing the multiblock are loaded, but possibly it's not doing the same for the actual farmland blocks?

I checked in my world and the farm covers a 2x2 chunk area. The multiblock itself does span a chunk boundary but only on one axis so the multiblock is only 1x2 chunks. So, even if the multiblock is being handled perfectly, it's still possible that any time the chunks containing the multiblock are loaded, the other two chunks in the farm are being loaded/unloaded in a cycle whenever the farm does work, and that does appear to be what's happening in my world..

**Comment by tornewuff** [comment]
Yeah, after experimenting a bit more it definitely looks like the farm is fine as long as the multiblock isn't loaded at all - it only causes this issue if the chunk containing the multiblock is loaded, but some of the farmland that the multiblock is managing is in another chunk that isn't loaded. So, an issue in the farm code specifically, not the general multiblock handling.

**Comment by temp1011** [comment]
So these farms are in the spawn chunks then since no players are online and no chunkloaders are in use? I'm not sure what there is to do about checking the farmland to see if the chunk is loaded, I guess checking chunk borders when building stuff would be helpful.

**Comment by tornewuff** [comment]
No - unrelated bugs in other mods are causing the chunks containing the farm multiblock to be loaded, and then the farm causes additional, adjacent chunks to be loaded as well.

**Comment by tornewuff** [comment]
The same thing would happen if a player was standing just far enough away that the chunk containing the multiblock was at the very edge of the player's chunk load radius, or if a chunkloader covered the multiblock but not the whole farm, though.

Or, yes, if the multiblock was in the spawn chunks, but the farmland extended outside of them.

**Comment by temp1011** [comment]
To be honest I think that's what I would expect it to do. It's unfortunate it happens but it could hopefully be mitigated by making sure the farm is inside chunk borders. It's a bit weird since nothing will actually grow in those chunks but equally the chunks would get loaded as well through things like trees growing.

**Comment by tornewuff** [comment]
You can check World.isBlockLoaded(BlockPos) before actually querying the state of the block itself, to avoid loading it. Most players are probably familiar with the fact that plants don't grow unless the chunk is loaded, so it might not be too surprising that the forestry farm also doesn't act on farmland unless the chunk is loaded?

With the default configuration settings even the smallest farm multiblock covers a 17x17 area, so it seems like it's always going to cross chunk borders wherever it's built, and the only way to actually stop this from happening is to chunkload the entire area, which removes the cost of the frequent loading and unloading of the additional chunks, but instead replaces that by the cost of having those additional chunks loaded and ticking constantly..

On my server I have five different mods showing different variations of this problem, and the combined result is that the server CPU usage when I'm online and at my base is *half as much* as when I'm offline or elsewhere in the world - the different bugs causing chunks to be loaded (either out of nowhere, or through this kind of adjacency issue being next to the chunks loaded out of nowhere) add up to enough churn that it's actually less costly to just chunkload the entire area permanently - but that's still much more CPU usage than if nothing was loaded.

Any one of the mods causing "secondary" effects like Forestry here isn't too big an issue by itself, but some variation of this seems to be pretty common in a lot of mods, and the combined effect adds up. It makes sense that it's a common issue since all the regular minecraft APIs load chunks implicitly when querying blocks, but in vanilla most things only have "local" effects and generally don't query blocks that aren't adjacent..

I'm filing bugs on all the other mods involved as well - and I'm planning to clean up and release the debugging mod I used to figure this out to try to make it easier to diagnose this sort of problem when it occurs, since there don't seem to be a lot of good tools out there for "why is my server consuming so much CPU" that are compatible with recent Minecraft versions.

**Comment by tornewuff** [comment]
Thanks a lot! With a bit more poking at mods I can hopefully get my server to actually go idle when nobody is online :)
