### ISSUE TITLE
crash game when creating a world, etc..

### ISSUE THREAD

**Issue by KiraLinux** [ForestryMC/ForestryMC#2081]
forestry_1.12.2-5.8.0.263 and forestry_1.12.2-5.8.0.264
1.12.2-forge1.12.2-14.23.2.2654

files
[crash.zip](https://github.com/ForestryMC/ForestryMC/files/1905138/crash.zip)

crash game when creating a world or when approaching the generating village during the generation of a new area of the world

**Comment by Nedelosk** [comment]
This crash was caused by Matter Overdrive and not by Forestry.
https://github.com/MatterOverdrive/MatterOverdrive/issues/112
```
java.lang.RuntimeException: Attempted to set villager profession to unregistered profession: -1 null
	at net.minecraftforge.fml.common.registry.VillagerRegistry.onSetProfession(VillagerRegistry.java:334)
	at net.minecraft.entity.passive.EntityVillager.func_184206_a(EntityVillager.java:457)
	at net.minecraft.network.datasync.EntityDataManager.func_187227_b(EntityDataManager.java:167)
	at net.minecraft.entity.passive.EntityVillager.func_70938_b(EntityVillager.java:423)
	at net.minecraft.entity.passive.EntityVillager.<init>(EntityVillager.java:129)
	at matteroverdrive.entity.EntityVillagerMadScientist.<init>(EntityVillagerMadScientist.java:74)
	at matteroverdrive.world.MadScientistHouse.func_74893_a(MadScientistHouse.java:219)
	at matteroverdrive.world.MadScientistHouse.func_74875_a(MadScientistHouse.java:192)
	at net.minecraft.world.gen.structure.StructureStart.func_75068_a(StructureStart.java:47)
	at net.minecraft.world.gen.structure.MapGenStructure.func_175794_a(MapGenStructure.java:94)
	at net.minecraft.world.gen.ChunkGeneratorFlat.func_185931_b(ChunkGeneratorFlat.java:181)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1017)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:997)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:344)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:186)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:209)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
	at java.lang.Thread.run(Unknown Source)
```
