### ISSUE TITLE
1.12.2 Crash (Rendering Screen) when opening Carpenter

### ISSUE THREAD

**Issue by ehmitchell3** [ForestryMC/ForestryMC#2224]
Might be a repeat of [2214](https://github.com/ForestryMC/ForestryMC/issues/2214), but updated the mod and Forge. Full gist available [here](https://gist.github.com/ehmitchell3/804040f0a591815797c0ee5aaf743992) with mods included.

I was able to open the top left tab once or twice, but the crash happens when opening the tabs on the right side.

Snippet below; thanks!

--------------------------------------------------
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at net.minecraftforge.client.MinecraftForgeClient.getLocale(MinecraftForgeClient.java:56)
	at forestry.core.config.EnergyDisplayMode.formatEnergyNum(EnergyDisplayMode.java:33)
	at forestry.core.config.EnergyDisplayMode.formatEnergyValue(EnergyDisplayMode.java:28)
	at forestry.core.gui.ledgers.PowerLedger.getTooltip(PowerLedger.java:56)
	at forestry.core.gui.ledgers.LedgerManager.drawTooltips(LedgerManager.java:177)
	at forestry.core.gui.GuiForestry.func_146979_b(GuiForestry.java:229)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:117)
	at forestry.core.gui.GuiForestry.func_73863_a(GuiForestry.java:109)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:381)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1118)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by temp1011** [comment]
This is probably due to the issue that was fixed in https://github.com/MinecraftForge/MinecraftForge/pull/5105. Hopefully updating forge to 14.23.4.2751 should fix this.

**Comment by ehmitchell3** [comment]
@temp1011 Upgraded to Forge ...##51 by hand (was using the Twitch App--they haven't released it yet in their dropdown), and all tabs seem to work.

Barring anything else, I think you can close this.

Thanks!
