### ISSUE TITLE
[Crash] 1.12.2 Loading screen on load forestry

### ISSUE THREAD

**Issue by KamiliaBlow** [ForestryMC/ForestryMC#2230]
minecraft 1.12.2
forge 14.23.4.2756

[Crash report](https://gist.github.com/DintyGadget/e4dc2bd2e6135d61ea6eb95f2526551a)

**Comment by Peach774** [comment]
Seems like that's caused by lucraft
Caused by: java.lang.ClassCastException: icbm.classic.lib.emp.CapabilityEmpEntityItem cannot be cast to lucraft.mods.lucraftcore.sizechanging.capabilities.ISizeChanging
	at lucraft.mods.lucraftcore.core.LCHooks.setSize(LCHooks.java:11)
	at net.minecraft.entity.Entity.func_70105_a(Entity.java)
	at net.minecraft.entity.item.EntityItem.<init>(EntityItem.java:76)
	at forestry.core.render.RenderAnalyzer.<init>(RenderAnalyzer.java:32)
	at forestry.core.proxy.ProxyRenderClient.setRendererAnalyzer(ProxyRenderClient.java:82)
	at forestry.core.blocks.BlockTypeCoreTesr.createAnalyzerProperties(BlockTypeCoreTesr.java:28)
	at forestry.core.blocks.BlockTypeCoreTesr.<clinit>(BlockTypeCoreTesr.java:19)
	... 50 more

**Comment by temp1011** [comment]
https://github.com/ForestryMC/ForestryMC/issues/2212
