### ISSUE TITLE
My Error Report!

### ISSUE THREAD

**Issue by Midnight-Vortex** [ForestryMC/ForestryMC#2287]
Here is my report.
they say that comes from forestry

[Forge Report](http://www.minecraftforge.net/forum/topic/67107-fatal-error-in-client-log/?tab=comments)

**Comment by Midnight-Vortex** [comment]
i have all reported my errors

**Comment by temp1011** [comment]
Relevant part of logs: 
```
java.util.concurrent.ExecutionException: java.lang.NullPointerException: Tried to send data to client before the player exists.
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_191]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_191]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1087) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_191]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NullPointerException: Tried to send data to client before the player exists.
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:787) ~[guava-21.0.jar:?]
	at forestry.core.network.PacketHandler.lambda$checkThreadAndEnqueue$0(PacketHandler.java:76) ~[PacketHandler.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_191]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 9 more
```
