### ISSUE TITLE
Invisible crafting recipes in JEI/Crash on recipe book's ghost item rendering

### ISSUE THREAD

**Issue by ferk6a** [ForestryMC/ForestryMC#2337]
These recipes that show up like this in JEI:
![image](https://user-images.githubusercontent.com/3057302/50977733-0fae0680-14da-11e9-9025-cfd9e653bef4.png)
![image](https://user-images.githubusercontent.com/3057302/50977765-1ccaf580-14da-11e9-9af5-436f547205b8.png)

Crash the recipe book like this:
```
java.lang.ArithmeticException: / by zero
	at net.minecraft.client.gui.recipebook.GhostRecipe$GhostIngredient.func_194184_c(SourceFile:111)
	at net.minecraft.client.gui.recipebook.GhostRecipe.func_194188_a(SourceFile:72)
	at net.minecraft.client.gui.recipebook.GuiRecipeBook.func_191864_a(GuiRecipeBook.java:309)
	at net.minecraft.client.gui.inventory.GuiCrafting.func_73863_a(SourceFile:64)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:381)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1118)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by Nedelosk** [comment]
@mezz Any idea what could cause this?

**Comment by mezz** [comment]
I'm not sure, it seems to work normally with just JEI and Forestry.
Try removing mods to see if you can narrow down what other mod might be causing the issue.

**Comment by ferk6a** [comment]
Ok, this issue is related to https://github.com/ForestryMC/ForestryMC/issues/2338. I enabled the `arboriculture` module and the decorative wood pile blocks show up again in recipes, and the recipe doesn't crash like it did before.

So I assume that by solving it, it effectively solves this issue as well, but I need to test it to make sure.

**Comment by temp1011** [comment]
So this is also fixed by https://github.com/ForestryMC/ForestryMC/commit/3c76628370373fcebfa118ce161dc5164e92c92d?
