### ISSUE TITLE
When I finished building the farm and supplying energy, the achievement system collapsed.

### ISSUE THREAD

**Issue by ShishiQ** [ForestryMC/ForestryMC#2403]
When I finished building the farm and supplying energy.
After that, all the achievements could not be accomplished.

Just install forestry_1.12.2-5.8.2.387.

**Comment by ShishiQ** [comment]
This is the error report generated when I use VanillaFix
`---- Minecraft Crash Report ----
// On the bright side, I bought you a teddy bear!

Time: 2019-04-25 17:31:55 CST
Description: Error executing task

java.util.concurrent.ExecutionException: java.lang.NullPointerException
    at java.util.concurrent.FutureTask.report(Unknown Source)
    at java.util.concurrent.FutureTask.get(Unknown Source)
    at net.minecraft.util.Util.runTask(SourceFile:531)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:179)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
    at net.minecraft.advancements.PlayerAdvancements.setSelectedTab(PlayerAdvancements.java:360)
    at net.minecraft.network.NetHandlerPlayServer.handleSeenAdvancements(NetHandlerPlayServer.java:447)
    at net.minecraft.network.play.client.CPacketSeenAdvancements.processPacket(SourceFile:50)
    at net.minecraft.network.play.client.CPacketSeenAdvancements.processPacket(SourceFile:11)
    at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at net.minecraft.util.Util.runTask(SourceFile:529)
    ... 3 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_211, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 10990131144 bytes (10481 MB) / 11760828416 bytes (11216 MB) up to 13522436096 bytes (12896 MB)
  JVM Flags: 11 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmn128m -Xmx12888m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
  IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
  FML: MCP 9.42 Powered by Forge 14.23.5.2836 8 mods loaded, 8 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State  | ID         | Version         | Source                             | Signature                                |
       |:------ |:---------- |:--------------- |:---------------------------------- |:---------------------------------------- |
       | LCHIJA | minecraft  | 1.12.2          | minecraft.jar                      | None                                     |
       | LCHIJA | mcp        | 9.42            | minecraft.jar                      | None                                     |
       | LCHIJA | FML        | 8.0.99.99       | forge-1.12.2-14.23.5.2836.jar      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | forge      | 14.23.5.2836    | forge-1.12.2-14.23.5.2836.jar      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | forestry   | 5.8.2.387       | forestry_1.12.2-5.8.2.387.jar      | None                                     |
       | LCHIJA | jeid       | 1.0.2-26        | ID上限JustEnoughIDs-1.0.2-26.jar     | None                                     |
       | LCHIJA | vanillafix | 1.0.10-SNAPSHOT | VanillaFix-1.0.10-99.jar           | None                                     |
       | LCHIJA | i18nmod    | 1.12.2-1.0.8    | 自动汉化i18nupdatemod-1.12.2-1.0.8.jar | None                                     |
  Loaded coremods (and transformers): JEIDLoadingPlugin (ID上限JustEnoughIDs-1.0.2-26.jar)
                                        org.dimdev.jeid.JEIDTransformer
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-99.jar)
  GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
  Suspected Mods: Unknown`

**Comment by temp1011** [comment]
As this involves vanilla fix and the player/player connection somehow being null, I tentatively suggest this is probably the same issue as https://github.com/ForestryMC/ForestryMC/issues/2318

**Comment by ShishiQ** [comment]
> 由于这涉及到普通修复，并且播放器/播放器连接某种程度上为空，因此我暂时建议这可能与[＃2318](https://github.com/ForestryMC/ForestryMC/issues/2318)相同[](https://github.com/ForestryMC/ForestryMC/issues/2318)
When I delete the vanilla fix, I still can't achieve anything. I used an integration package made by another author, which is the same phenomenon

**Comment by ShishiQ** [comment]
> As this involves vanilla fix and the player/player connection somehow being null, I tentatively suggest this is probably the same issue as #2318

When I delete the vanilla fix, I still can't achieve anything. I used an integration package made by another author, which is the same phenomenon
