### ISSUE TITLE
Bad bad things happen after naming the trade station

### ISSUE THREAD

**Issue by LordEpos** [ForestryMC/ForestryMC#2456]
On the latest version, I opened a trade station, wrote a name in the UI, and pressed enter.

My log then said the following repeatedly until MultiMC stopped recording, and then the server and client disconnected from eachother entirely. In singleplayer.

Log stuff:
```

[13:28:21] [Client thread/FATAL] [minecraft/Minecraft]: Error executing task
java.util.concurrent.ExecutionException: java.lang.IndexOutOfBoundsException: Index: 46, Size: 46
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_201]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_201]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1088) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_201]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_201]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.IndexOutOfBoundsException: Index: 46, Size: 46
	at java.util.ArrayList.rangeCheck(Unknown Source) ~[?:1.8.0_201]
	at java.util.ArrayList.get(Unknown Source) ~[?:1.8.0_201]
	at net.minecraft.inventory.Container.func_75139_a(Container.java:120) ~[afr.class:?]
	at net.minecraft.inventory.Container.func_190896_a(Container.java:527) ~[afr.class:?]
	at gigaherz.inventoryspam.ContainerWrapper.func_190896_a(ContainerWrapper.java:132) ~[ContainerWrapper.class:?]
	at net.minecraft.client.network.NetHandlerPlayClient.func_147241_a(NetHandlerPlayClient.java:1191) ~[brz.class:?]
	at net.minecraft.network.play.server.SPacketWindowItems.func_148833_a(SourceFile:50) ~[is.class:?]
	at net.minecraft.network.play.server.SPacketWindowItems.func_148833_a(SourceFile:12) ~[is.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_201]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_201]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 17 more
```

**Comment by temp1011** [comment]
- Please post full log, or at least versions of forestry and inventory spam
- What was the name you were trying to set?
- Please try without inventoryspam

**Comment by Nedelosk** [comment]
Closed because of no response.
