### ISSUE TITLE
Using with TE causes the game to crash

### ISSUE THREAD

**Issue by MiniDay** [ForestryMC/ForestryMC#2524]
I don't know exactly how this bug was generated, but when I deleted the coordinate [thermalexpansion:machine_pulverizer] using worldedit in the report, the server no longer crashed.

Maybe this bug has something to do with TE, but I saw the last code displayed in the tracker pointed to FR, so I decided to submit the issue here.

I don't know English very well. These sentences are all generated by translation software. If my rudeness offends you, please forgive me.

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
  AnotherCommonBugFix (AnotherCommonBugFix-1.0.7-1.12.2.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.10-1.12.2.jar)
  CreativePatchingLoader (CreativeCore_v1.9.90_mc1.12.2.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
Contact their authors BEFORE contacting forge

// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 2/16/20 6:50 PM
Description: Ticking block entity

java.lang.NoSuchMethodError: forestry.core.utils.ItemStackUtil.isIdenticalItemIgnoreCaps(Lnet/minecraft/item/ItemStack;Lnet/minecraft/item/ItemStack;)Z
	at forestry.factory.recipes.FabricatorRecipeManager.isPlan(FabricatorRecipeManager.java:65)
	at forestry.factory.inventory.InventoryFabricator.canSlotAccept(InventoryFabricator.java:39)
	at forestry.core.inventory.InventoryAdapterRestricted.func_94041_b(InventoryAdapterRestricted.java:27)
	at forestry.core.inventory.InventoryAdapterRestricted.func_180462_a(InventoryAdapterRestricted.java:32)
	at net.minecraftforge.items.wrapper.SidedInvWrapper.insertItem(SidedInvWrapper.java:145)
	at net.minecraftforge.items.ItemHandlerHelper.insertItemStacked(ItemHandlerHelper.java:139)
	at cofh.core.util.helpers.InventoryHelper.insertStackIntoInventory(InventoryHelper.java:90)
	at cofh.core.util.helpers.InventoryHelper.insertStackIntoInventory(InventoryHelper.java:85)
	at cofh.core.util.helpers.InventoryHelper.addToInventory(InventoryHelper.java:184)
	at cofh.core.block.TileInventory.transferItem(TileInventory.java:84)
	at cofh.thermalexpansion.block.machine.TilePulverizer.transferOutput(TilePulverizer.java:281)
	at cofh.thermalexpansion.block.machine.TileMachineBase.func_73660_a(TileMachineBase.java:336)
	at net.minecraft.world.World.func_72939_s(World.java:2168)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:742)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:910)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:473)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:780)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:634)
	at java.lang.Thread.run(Thread.java:748)

```
The full report is here：https://gist.github.com/ViosinDeng/2a8c6906a517c623eaa13bd33f7f7068

**Comment by Nedelosk** [comment]
This crash should not be possible because this is our own method, very strange.

**Comment by SettingDust** [comment]
Causing by AnotherCommonBugFix on my end
It replacing the class to fix https://github.com/ForestryMC/ForestryMC/issues/2579
