### ISSUE TITLE
Having trouble with game crashing 

### ISSUE THREAD

**Issue by ElizaT69** [ForestryMC/ForestryMC#2655]
Thank you for reporting!

For issues:
 * Try the latest version, it may have fixed the issue already.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

**Comment by ElizaT69** [comment]
I am having trouble trying to fix this issue.

---- Minecraft Crash Report ----
// There are four lights!

Time: 4/25/22 9:08 PM
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:85) [?:?] {re:classloading}
	at net.minecraftforge.fml.client.ClientModLoader.completeModLoading(ClientModLoader.java:188) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$null$1(Minecraft.java:508) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$24305/1010140169.run(Unknown Source) [?:?] {}
	at net.minecraft.util.Util.func_215077_a(Util.java:320) [?:?] {re:classloading,re:mixin}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:504) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$21894/585886948.accept(Unknown Source) [?:?] {}
	at net.minecraft.client.gui.ResourceLoadProgressGui.func_230430_a_(ResourceLoadProgressGui.java:113) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:481) [?:?] {re:mixin,pl:accesstransformer:B,xf:fml:fairylights:GameRendererTransformer,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:fairylights:GameRendererTransformer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:977) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.2.34.jar:36.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$507/1530206433.call(Unknown Source) [forge-1.16.5-36.2.34.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.util.ResourceLocation.<init>(ResourceLocation.java:33) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
-- MOD forestry --
Details:
	Mod File: Forestry-Mod-1.16.5.jar
	Failure message: Forestry (forestry) encountered an error during the common_setup event phase
		net.minecraft.util.ResourceLocationException: Non [a-z0-9/._-] character in path of location: ic2:crop_res:2
	Mod Version: 6.0.11
	Mod Issue URL: https://github.com/ForestryMC/ForestryMC/issues
	Exception message: net.minecraft.util.ResourceLocationException: Non [a-z0-9/._-] character in path of location: ic2:crop_res:2
Stacktrace:
	at net.minecraft.util.ResourceLocation.<init>(ResourceLocation.java:33) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.util.ResourceLocation.<init>(ResourceLocation.java:38) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at forestry.farming.FarmRegistry.parseConfig(FarmRegistry.java:146) ~[?:6.0.11] {re:classloading}
	at forestry.farming.FarmRegistry.checkConfig(FarmRegistry.java:118) ~[?:6.0.11] {re:classloading}
	at forestry.farming.FarmRegistry.loadConfig(FarmRegistry.java:111) ~[?:6.0.11] {re:classloading}
	at forestry.farming.ModuleFarming.doInit(ModuleFarming.java:159) ~[?:6.0.11] {re:classloading}
	at forestry.modules.CommonModuleHandler.runInit(CommonModuleHandler.java:166) ~[?:6.0.11] {re:classloading}
	at forestry.Forestry.setup(Forestry.java:231) ~[?:6.0.11] {re:classloading}
	at forestry.Forestry$$Lambda$11916/1546405973.accept(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$3009/1534177037.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$3172/1559346131.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[?:36.2] {re:classloading}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModContainer$$Lambda$3671/1675886984.run(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}


-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1459613632 bytes (1391 MB) / 5536481280 bytes (5280 MB) up to 6442450944 bytes (6144 MB)
	CPUs: 12
	JVM Flags: 10 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -XX:+IgnoreUnrecognizedVMOptions -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.1.3+8.1.3+main-8.1.x.c94d18ec
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.4.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.34.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.34.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.34.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.34.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.34.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.34
	FML Language Providers: 
		javafml@36.2
		minecraft@1
		kotlinforforge@1.17.0
	Mod List: 
		Wizards-Animals-Mod-1.16.5.jar                    |Wizard Animals Plus           |wizard_animals_plus           |2.5.0               |SIDED_SETU|Manifest: NOSIGNATURE
		supermartijn642configlib-1.0.9-mc1.16.jar         |SuperMartijn642's Config Lib  |supermartijn642configlib      |1.0.9               |SIDED_SETU|Manifest: NOSIGNATURE
		Dense-Ores-Reborn-Mod-1.16.5.jar                  |Dense Ores Reborn             |denseoresreborn               |2.0                 |SIDED_SETU|Manifest: NOSIGNATURE
		refinedpipes-0.5.1.jar                            |Refined Pipes                 |refinedpipes                  |0.5.1               |SIDED_SETU|Manifest: NOSIGNATURE
		Macaws-Windows-Mod-1.16.5.jar                     |Macaw's Windows               |mcwwindows                    |2.0.3               |SIDED_SETU|Manifest: NOSIGNATURE
		ForgeEndertech-1.16.5-7.2.2.0-build.0202.jar      |Forge Endertech               |forgeendertech                |7.2.2.0             |SIDED_SETU|Manifest: NOSIGNATURE
		XaerosWorldMap_1.18.6_Forge_1.16.5.jar            |Xaero's World Map             |xaeroworldmap                 |1.18.6              |SIDED_SETU|Manifest: NOSIGNATURE
		Just-Another-Rotten-Flesh-to-Leather-Mod-1.16.5.ja|JRFTL                         |jrftl                         |1.2                 |SIDED_SETU|Manifest: NOSIGNATURE
		citadel-1.8.1-1.16.5.jar                          |Citadel                       |citadel                       |1.8.1               |SIDED_SETU|Manifest: NOSIGNATURE
		YungsApi-1.16.4-Forge-13.jar                      |YUNG's API                    |yungsapi                      |1.16.4-Forge-13     |SIDED_SETU|Manifest: NOSIGNATURE
		Powah-Mod-1.16.5.jar                              |Powah                         |powah                         |2.3.9               |SIDED_SETU|Manifest: NOSIGNATURE
		Bookshelf-Forge-1.16.5-10.3.29.jar                |Bookshelf                     |bookshelf                     |10.3.29             |SIDED_SETU|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		u_team_core-1.16.5-3.2.1.196.jar                  |U Team Core                   |uteamcore                     |3.2.1.196           |SIDED_SETU|Manifest: f4:a6:0b:ee:cb:8a:1a:ea:9f:9d:45:91:8f:8b:b3:ae:26:f3:bf:05:86:1d:90:9e:f6:32:2a:1a:ed:1d:ce:b0
		Secret-Rooms-Mod-1.16.5.jar                       |Secret Rooms 6                |secretroomsmod                |1.16.5-1.1.4        |SIDED_SETU|Manifest: NOSIGNATURE
		Macaws-Doors-Mod-1.16.5.jar                       |Macaw's Doors                 |mcwdoors                      |1.0.6               |SIDED_SETU|Manifest: NOSIGNATURE
		Mekanism-Mod-Generators-1.16.5.jar                |Mekanism: Generators          |mekanismgenerators            |10.1.2              |SIDED_SETU|Manifest: NOSIGNATURE
		Hwyla-forge-1.10.11-B78_1.16.2.jar                |Waila                         |waila                         |1.10.11-B78_1.16.2  |SIDED_SETU|Manifest: NOSIGNATURE
		Enhanced-Vanilla-Mod-1.16.5.jar                   |Enhanced Vanilla              |enhanced_vanilla              |1.0.4               |SIDED_SETU|Manifest: NOSIGNATURE
		Just-Enough-Resources-Mod-1.16.5.jar              |Just Enough Resources         |jeresources                   |0.12.1.128          |SIDED_SETU|Manifest: NOSIGNATURE
		ShetiPhianCore-1.16.5.jar                         |ShetiPhian-Core               |shetiphiancore                |3.8.11              |SIDED_SETU|Manifest: NOSIGNATURE
		Dragon-Mounts-Legacy-Mod-1.16.5.jar               |Dragon Mounts: Legacy         |dragonmounts                  |1.0.10              |SIDED_SETU|Manifest: NOSIGNATURE
		Twilight-Forest-Mod-1.16.5.jar                    |The Twilight Forest           |twilightforest                |NONE                |SIDED_SETU|Manifest: NOSIGNATURE
		refinedstorage-1.9.16.jar                         |Refined Storage               |refinedstorage                |1.9.16              |SIDED_SETU|Manifest: NOSIGNATURE
		Better-End-Mod-1.16.5.jar                         |BetterEnd Forge               |betterendforge                |1.16.4-1.5.1        |SIDED_SETU|Manifest: NOSIGNATURE
		Chipped-Mod-1.16.5.jar                            |Chipped                       |chipped                       |1.1.2               |SIDED_SETU|Manifest: NOSIGNATURE
		Ore-Tweaker-Mod-1.16.5.jar                        |Ore Tweaker                   |oretweaker                    |2.7.1               |SIDED_SETU|Manifest: NOSIGNATURE
		industrial-foregoing-1.16.5-3.2.14.6-14.jar       |Industrial Foregoing          |industrialforegoing           |3.2.14.6            |SIDED_SETU|Manifest: NOSIGNATURE
		AI-Reducer-Mod-1.16.5.jar                         |AI Reducer                    |aireducer                     |0.1.0               |SIDED_SETU|Manifest: NOSIGNATURE
		Mekanism-Mod-Additions-1.16.5.jar                 |Mekanism: Additions           |mekanismadditions             |10.1.2              |SIDED_SETU|Manifest: NOSIGNATURE
		Lollipop-Library-1.16.5.jar                       |Lollipop                      |lollipop                      |3.2.4               |SIDED_SETU|Manifest: NOSIGNATURE
		Macaws-Fences-and-Walls-Mod-1.16.5.jar            |Macaw's Fences and Walls      |mcwfences                     |1.0.2               |SIDED_SETU|Manifest: NOSIGNATURE
		Advanced-Mining-Dimension-Mod-1.16.5.jar          |Mining World                  |mining_dimension              |1.16.5-1.0.4        |SIDED_SETU|Manifest: NOSIGNATURE
		wirelesschargers-1.0.3-mc1.16.jar                 |wirelesschargers              |wirelesschargers              |1.0.3               |SIDED_SETU|Manifest: NOSIGNATURE
		supermartijn642corelib-1.0.15-mc1.16.5.jar        |SuperMartijn642's Core Lib    |supermartijn642corelib        |1.0.15              |SIDED_SETU|Manifest: NOSIGNATURE
		Simply-Light-Mod-1.16.5.jar                       |Simply Light                  |simplylight                   |1.16.5-1.3.1-build.1|SIDED_SETU|Manifest: NOSIGNATURE
		Fairy-Lights-Mod-1.16.5.jar                       |Fairy Lights                  |fairylights                   |4.0.5               |SIDED_SETU|Manifest: NOSIGNATURE
		Creatures-and-Beasts-Mod-1.16.5.jar               |Creatures and Beasts          |cnb                           |1.2.11              |SIDED_SETU|Manifest: NOSIGNATURE
		curios-forge-1.16.5-4.0.5.3.jar                   |Curios API                    |curios                        |1.16.5-4.0.5.3      |SIDED_SETU|Manifest: NOSIGNATURE
		Patchouli-1.16.4-53.2.jar                         |Patchouli                     |patchouli                     |1.16.4-53.2         |SIDED_SETU|Manifest: NOSIGNATURE
		Collective-Library-1.16.5.jar                     |Collective                    |collective                    |3.8                 |SIDED_SETU|Manifest: NOSIGNATURE
		OreExcavation-1.8.157.jar                         |Ore Excavation                |oreexcavation                 |1.8.157             |SIDED_SETU|Manifest: e7:68:1c:0d:b9:7e:cf:f8:f3:40:9c:84:c5:39:d7:a4:59:78:b0:6b:c3:fd:b7:4f:69:18:a3:88:e3:76:8c:3f
		tombstone-6.6.2-1.16.5.jar                        |Corail Tombstone              |tombstone                     |6.6.2               |SIDED_SETU|Manifest: NOSIGNATURE
		obfuscate-0.6.2-1.16.3.jar                        |Obfuscate                     |obfuscate                     |0.6.2               |SIDED_SETU|Manifest: e1:59:1a:56:ec:97:b3:d0:b3:4b:25:06:1f:83:b0:f4:fd:0c:24:e3:6d:ea:94:b1:9f:22:b0:38:13:60:88:ea
		The-Abyss-Chapter-2-Mod-1.16.5.jar                |TheAbyss                      |theabyss                      |2.2.3-2             |SIDED_SETU|Manifest: NOSIGNATURE
		Mekanism-Mod-Tools-1.16.5.jar                     |Mekanism: Tools               |mekanismtools                 |10.1.2              |SIDED_SETU|Manifest: NOSIGNATURE
		architectury-1.31.60.jar                          |Architectury                  |architectury                  |1.31.60             |SIDED_SETU|Manifest: NOSIGNATURE
		cloth-config-4.14.54-forge.jar                    |Cloth Config v4 API           |cloth-config                  |4.14.54             |SIDED_SETU|Manifest: NOSIGNATURE
		FastLeafDecay-v25.jar                             |FastLeafDecay                 |fastleafdecay                 |v25                 |SIDED_SETU|Manifest: NOSIGNATURE
		CodeChickenLib-1.16.5-4.0.5.438-universal.jar     |CodeChicken Lib               |codechickenlib                |4.0.5.438           |SIDED_SETU|Manifest: 31:e6:db:63:47:4a:6e:e0:0a:2c:11:d1:76:db:4e:82:ff:56:2d:29:93:d2:e5:02:bd:d3:bd:9d:27:47:a5:71
		Dynamic-Trees-Mod-1.16.5.jar                      |Dynamic Trees                 |dynamictrees                  |1.16.5-0.10.0-Beta24|SIDED_SETU|Manifest: NOSIGNATURE
		GeckoLib-Mod-1.16.5.jar                           |GeckoLib                      |geckolib3                     |3.0.63              |SIDED_SETU|Manifest: NOSIGNATURE
		biggerreactors-1.16.5-0.5.1.jar                   |Bigger Reactors               |biggerreactors                |0.5.1               |SIDED_SETU|Manifest: NOSIGNATURE
		Cucumber-1.16.5-4.1.12.jar                        |Cucumber Library              |cucumber                      |4.1.12              |SIDED_SETU|Manifest: NOSIGNATURE
		XP-From-Harvest-Mod-1.16.5.jar                    |XP From Harvest               |xpfromharvest                 |1.2.2               |SIDED_SETU|Manifest: NOSIGNATURE
		Pams-HarvestCraft-2-Trees-Mod-1.16.5.jar          |Pam's HarvestCraft 2 Fruit Tre|pamhc2trees                   |1.0.1               |SIDED_SETU|Manifest: NOSIGNATURE
		cgm-1.1.0-mc1.16.5.jar                            |MrCrayfish's Gun Mod          |cgm                           |1.1.0               |SIDED_SETU|Manifest: NOSIGNATURE
		Advent-of-Ascension-Mod-1.16.5.jar                |Advent of Ascension           |aoa3                          |1.16.5-3.6          |SIDED_SETU|Manifest: NOSIGNATURE
		jei-1.16.5-7.7.1.150.jar                          |Just Enough Items             |jei                           |7.7.1.150           |SIDED_SETU|Manifest: NOSIGNATURE
		abnormals_core-1.16.5-3.3.0.jar                   |Abnormals Core                |abnormals_core                |3.3.0               |SIDED_SETU|Manifest: NOSIGNATURE
		Environmental-Mod-1.16.5.jar                      |Environmental                 |environmental                 |1.1.1               |SIDED_SETU|Manifest: NOSIGNATURE
		Mekanism-Mod-Core-1.16.5.jar                      |Mekanism                      |mekanism                      |10.1.2              |SIDED_SETU|Manifest: NOSIGNATURE
		caelus-forge-1.16.5-2.1.3.2.jar                   |Caelus API                    |caelus                        |1.16.5-2.1.3.2      |SIDED_SETU|Manifest: NOSIGNATURE
		Colytra-Mod-1.16.5.jar                            |Colytra                       |colytra                       |1.16.5-5.1.1.2      |SIDED_SETU|Manifest: NOSIGNATURE
		Inventory-Tweaks-Renewed-Mod-1.16.5.jar           |Inventory Tweaks Renewed      |invtweaks                     |1.16.4-1.0.1        |SIDED_SETU|Manifest: NOSIGNATURE
		Waystones-Mod-1.16.5.jar                          |Waystones                     |waystones                     |7.6.4               |SIDED_SETU|Manifest: NOSIGNATURE
		appliedenergistics2-8.4.4.jar                     |Applied Energistics 2         |appliedenergistics2           |8.4.4               |SIDED_SETU|Manifest: 95:58:cc:83:9d:a8:fa:4f:e9:f3:54:90:66:61:c8:ae:9c:08:88:11:52:52:df:2d:28:5f:05:d8:28:57:0f:98
		NaturesCompass-1.16.5-1.9.1-forge.jar             |Nature's Compass              |naturescompass                |1.16.5-1.9.1-forge  |SIDED_SETU|Manifest: NOSIGNATURE
		Untamed-Wilds-Mod-1.16.5.jar                      |Untamed Wilds                 |untamedwilds                  |1.5.5               |SIDED_SETU|Manifest: NOSIGNATURE
		Serene-Seasons-Mod-1.16.5.jar                     |Serene Seasons                |sereneseasons                 |1.16.5-4.0.1.125    |SIDED_SETU|Manifest: NOSIGNATURE
		Basic-Nether-Ores-Mod-1.16.5.jar                  |Basic Nether Ores             |bno                           |5.5.0               |SIDED_SETU|Manifest: NOSIGNATURE
		phosphophyllite-1.16.5-0.5.1.jar                  |Phosphophyllite               |phosphophyllite               |0.5.1               |SIDED_SETU|Manifest: NOSIGNATURE
		Dungeon-Crawl-Mod-1.16.5.jar                      |Dungeon Crawl                 |dungeoncrawl                  |2.3.8               |SIDED_SETU|Manifest: NOSIGNATURE
		charginggadgets-1.3.0.jar                         |Charging Gadgets              |charginggadgets               |1.3.0               |SIDED_SETU|Manifest: NOSIGNATURE
		mcjtylib-1.16-5.1.2.jar                           |McJtyLib                      |mcjtylib                      |1.16-5.1.2          |SIDED_SETU|Manifest: NOSIGNATURE
		Ice-and-Fire-Mod-1.16.5.jar                       |Ice and Fire                  |iceandfire                    |2.1.9-1.16.5        |SIDED_SETU|Manifest: NOSIGNATURE
		iChun-Util-Mod-1.16.5.jar                         |iChunUtil                     |ichunutil                     |10.5.0              |SIDED_SETU|Manifest: NOSIGNATURE
		mininggadgets-1.7.5.jar                           |Mining Gadgets                |mininggadgets                 |1.7.5               |SIDED_SETU|Manifest: NOSIGNATURE
		forge-1.16.5-36.2.34-universal.jar                |Forge                         |forge                         |36.2.34             |SIDED_SETU|Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		Dynamic-Surroundings-Mod-1.16.5.jar               |§3Dynamic Surroundings        |dsurround                     |4.0.5.0             |SIDED_SETU|Manifest: NOSIGNATURE
		Iron-Chests-Mod-1.16.5.jar                        |Iron Chests                   |ironchest                     |1.16.5-11.2.21      |SIDED_SETU|Manifest: NOSIGNATURE
		ZeroCore2-1.16.5-2.1.4.jar                        |Zero CORE 2                   |zerocore                      |1.16.5-2.1.4        |SIDED_SETU|Manifest: NOSIGNATURE
		ExtremeReactors2-1.16.5-2.0.31.jar                |Extreme Reactors              |bigreactors                   |1.16.5-2.0.31       |SIDED_SETU|Manifest: NOSIGNATURE
		forge-1.16.5-36.2.34-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |SIDED_SETU|Manifest: NOSIGNATURE
		cofh_core-1.16.5-1.3.1.jar                        |CoFH Core                     |cofh_core                     |1.3.1               |SIDED_SETU|Manifest: NOSIGNATURE
		Thermal-Foundation-Mod-1.16.5.jar                 |Thermal Series                |thermal                       |1.3.2               |SIDED_SETU|Manifest: NOSIGNATURE
		Thermal-Expansion-Mod-1.16.5.jar                  |Thermal Expansion             |thermal_expansion             |1.3.0               |SIDED_SETU|Manifest: 75:0b:cc:9b:64:2e:9b:c4:41:d1:95:00:71:ee:87:1a:b3:5e:4b:da:8e:e8:39:00:fd:5d:e5:9c:40:42:33:09
		Tinkers-Construct-Mod-1.16.5.jar                  |Tinkers' Construct            |tconstruct                    |3.2.1.296           |SIDED_SETU|Manifest: NOSIGNATURE
		EnchantmentDescriptions-1.16.5-7.0.12.jar         |EnchantmentDescriptions       |enchdesc                      |7.0.12              |SIDED_SETU|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		Pandoras-Creatures-Mod-1.16.5.jar                 |Pandoras Creatures            |pandoras_creatures            |1.16.3-2.0.1        |SIDED_SETU|Manifest: NOSIGNATURE
		titanium-1.16.5-3.2.8.4-10.jar                    |Titanium                      |titanium                      |3.2.8.4             |SIDED_SETU|Manifest: NOSIGNATURE
		Pams-HarvestCraft-2-Crops-Mod-1.16.5.jar          |Pam's HarvestCraft 2 Crops    |pamhc2crops                   |version             |SIDED_SETU|Manifest: NOSIGNATURE
		ChickenChunks-1.16.5-2.9.0.88-universal.jar       |ChickenChunks                 |chickenchunks                 |2.9.0.88            |SIDED_SETU|Manifest: 31:e6:db:63:47:4a:6e:e0:0a:2c:11:d1:76:db:4e:82:ff:56:2d:29:93:d2:e5:02:bd:d3:bd:9d:27:47:a5:71
		Ambient-Additions-Mod-1.16.5.jar                  |Ambient Additions             |ambientadditions              |0.1.0               |SIDED_SETU|Manifest: NOSIGNATURE
		Mantle-1.16.5-1.6.127.jar                         |Mantle                        |mantle                        |1.6.127             |SIDED_SETU|Manifest: NOSIGNATURE
		Xaeros-Minimap-Mod-1.16.5.jar                     |Xaero's Minimap               |xaerominimap                  |21.22.2             |SIDED_SETU|Manifest: NOSIGNATURE
		EuhDawsons-GraveStone-Mod-1.16.5.jar              |Gravestone Mod                |gravestone                    |1.16.5-1.0.7        |SIDED_SETU|Manifest: NOSIGNATURE
		MultiBeds-Mod-1.16.5.jar                          |Multi-Beds                    |multibeds                     |1.7.15              |SIDED_SETU|Manifest: NOSIGNATURE
		AutoRegLib-1.16.5.jar                             |AutoRegLib                    |autoreglib                    |1.6-49              |SIDED_SETU|Manifest: NOSIGNATURE
		Quark-Mod-1.16.5.jar                              |Quark                         |quark                         |r2.4-322            |SIDED_SETU|Manifest: NOSIGNATURE
		Harvest-Mod-1.16.5.jar                            |Harvest                       |harvest                       |1.0.3               |SIDED_SETU|Manifest: NOSIGNATURE
		appleskin-forge-mc1.16.x-2.2.0.jar                |AppleSkin                     |appleskin                     |mc1.16.4-2.2.0      |SIDED_SETU|Manifest: NOSIGNATURE
		Ring-of-Attraction-Mod-1.16.5.jar                 |Ring of Attraction            |ring_of_attraction            |1.2.12              |SIDED_SETU|Manifest: NOSIGNATURE
		Oh-The-Biomes-Youll-Go-Mod-1.16.5.jar             |Oh The Biomes You'll Go       |byg                           |1.3.4               |SIDED_SETU|Manifest: NOSIGNATURE
		Forestry-Mod-1.16.5.jar                           |Forestry                      |forestry                      |6.0.11              |ERROR     |Manifest: NOSIGNATURE
	Crash Report UUID: 76875dc0-5bbb-4f85-b793-919c2d1399a8
