### ISSUE TITLE
Beehouses can not be instantiated on server start in build 394

### ISSUE THREAD

**Issue by christianvdstap** [ForestryMC/ForestryMC#434]
Scary exception on world load full mod listing can be found at http://forum.industrial-craft.net/index.php?page=Thread&postID=152179 (the third post has the update delta):

[11:42:22] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.InstantiationException: forestry.apiculture.worldgen.ComponentVillageBeeHouse
[11:42:22] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at java.lang.Class.newInstance(Class.java:359)
[11:42:22] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.world.gen.structure.MapGenStructureIO.func_143032_b(SourceFile:81)
[11:42:22] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.world.gen.structure.StructureStart.func_143020_a(StructureStart.java:104)
[11:42:22] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.world.gen.structure.MapGenStructureIO.func_143035_a(SourceFile:69)
[11:42:22] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.world.gen.structure.MapGenStructure.func_143027_a(MapGenStructure.java:267)
[11:42:22] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.world.gen.structure.MapGenStructure.func_151538_a(MapGenStructure.java:30)
[11:42:22] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.world.gen.MapGenBase.func_151539_a(SourceFile:30)
[11:42:22] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.world.gen.ChunkProviderFlat.func_82695_e(SourceFile:217)
[11:42:22] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:49)
[11:42:22] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:12)
[11:42:22] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:344)
[11:42:22] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302)
[11:42:22] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12)
[11:42:22] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:126)
[11:42:22] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101)
[11:42:22] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:265)
[11:42:22] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:235)
[11:42:22] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:258)
[11:42:22] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
[11:42:22] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
[11:42:22] [Server thread/WARN]: Skipping Piece with id Forestry:BeeHouse
[11:42:22] [Server thread/WARN]: Failed Piece with id Forestry:BeeHouse

**Comment by mezz** [comment]
Thanks for the report! 
I think I just fixed this yesterday, can you try with the latest unstable build?

**Comment by mezz** [comment]
Same as #437
