### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by marcin212** [ForestryMC/ForestryMC#465]
Click use in catalogue and next right click with letter on any block.
Console is empty.

forestry_1.7.10-3.3.0.422-unstable
forge-1.7.10-10.13.2.1286

**Comment by CovertJaguar** [comment]
Usually errors such as this should print something in the Forge log files.

**Comment by marcin212** [comment]
on server-side:
```
java.lang.NullPointerException
        at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:620) ~[nh.class:?]
        at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60) ~[jo.class:?]
        at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9) ~[jo.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]

```

**Comment by mezz** [comment]
Ok I have narrowed down the bug a little.
It is with the catalogue closing.
If you close the catalogue by setting the trade, and then open any forestry item GUI against a block, it will crash. If you open the player's inventory in between those two steps, it's fine.

**Comment by mezz** [comment]
Thanks again marcin212
Fixed in the latest unstable.
