### ISSUE TITLE
weird thing

### ISSUE THREAD

**Issue by Manuepolis23** [ForestryMC/ForestryMC#495]
the last stable version works with ex nihilo but previous unstable versions don't and crash the game

---- Minecraft Crash Report ----
// Everything's going to plan. No, really, that was supposed to happen.

Time: 2/2/15 9:11 PM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: forestry/apiculture/FlowerProviderVanilla
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:162)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:695)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:288)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:541)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:214)
	at org.multimc.EntryPoint.listen(EntryPoint.java:165)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)
Caused by: java.lang.NoClassDefFoundError: forestry/apiculture/FlowerProviderVanilla
	at exnihilo.compatibility.foresty.HiveRegistry.<clinit>(HiveRegistry.java:25)
	at exnihilo.compatibility.foresty.Forestry.loadCompatibility(Forestry.java:28)
	at exnihilo.ExNihilo.PostInitialize(ExNihilo.java:132)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:694)
	... 17 more
Caused by: java.lang.ClassNotFoundException: forestry.apiculture.FlowerProviderVanilla
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 46 more
Caused by: java.lang.SecurityException: class "forestry.apiculture.FlowerProviderVanilla"'s signer information does not match signer information of other classes in the same package
	at java.lang.ClassLoader.checkCerts(Unknown Source)
	at java.lang.ClassLoader.preDefineClass(Unknown Source)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 48 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.7.0_71, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 357878672 bytes (341 MB) / 1489502208 bytes (1420 MB) up to 3340763136 bytes (3186 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx3584m -XX:PermSize=256m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.85.1291 Minecraft Forge 10.13.2.1291 Optifine OptiFine_1.7.10_HD_U_B5 71 mods loaded, 71 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	FML{7.10.85.1291} [Forge Mod Loader] (forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Forge{10.13.2.1291} [Minecraft Forge] (forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Aroma1997Core{1.0.2.13} [Aroma1997Core] (Aroma1997Core-1.7.10-1.0.2.13.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	bowinfinityfix{rv0} [Bow Infinity Fix] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	CodeChickenCore{1.0.4.35} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	<CoFH ASM>{000} [CoFH ASM Data Initialization] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	MobiusCore{1.2.3} [MobiusCore] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	NotEnoughItems{1.0.4.83} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.4.83-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	VeinMiner_coremod{${version}_build-null} [Core mod] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	DamageIndicatorsMod{3.2.3} [Damage Indicators] ([1.7.10]DamageIndicatorsMod-3.2.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	bspkrsCore{6.15} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.15.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	StatusEffectHUD{1.27} [StatusEffectHUD] ([1.7.10]StatusEffectHUD-client-1.27.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	act{0.0.2a_1.7.10} [AdminCommandsToolbox] (AdminCommandsToolbox-0.0.2a_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Aroma1997CoreHelper{1.0.2.13} [Aroma1997Core|Helper] (Aroma1997Core-1.7.10-1.0.2.13.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	AromaBackup{0.0.0.5} [AromaBackup] (AromaBackup-1.7.10-0.0.0.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	bdlib{1.6.0.36} [BD Lib] (bdlib-mc1710-1.6.0.36.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.1036-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	ChickenChunks{1.3.4.17} [ChickenChunks] (ChickenChunks-1.7.10-1.3.4.17-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	CleanView{1.7.10-v2} [CleanView] (CleanView-1.7.10-v2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	ClockHUD{1.7.10-1.0} [Clock HUD] (ClockHUD-1.7.10-1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	CoFHCore{1.7.10R3.0.0B9} [CoFH Core] (CoFHCore-[1.7.10]3.0.0B9-117.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	EUGenFix{1.0} [EU Generator Fix] (EUGenFix-1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	ThermalFoundation{1.7.10R1.0.0RC1} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.0.0RC1-35.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	ForgeMultipart{1.1.0.309} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.0.309-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	ExtraUtilities{1.2.1} [Extra Utilities] (extrautilities-1.2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	inpure|core{1.7.10R1.0.0B8} [INpureCore] (INpureCore-[1.7.10]1.0.0B8-49.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	CreeperCollateral{1.7.10R1.0.0B3} [CreeperCollateral] (CreeperCollateral-[1.7.10]1.0.0B3-6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	exnihilo{1.37} [Ex Nihilo] (Ex-Nihilo-1.37.jar) Unloaded->Constructed->Pre-initialized->Initialized->Errored
	FastCraft{1.16} [FastCraft] (fastcraft-1.16.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	FlatSigns{2.1.0.19} [Flat Signs] (FlatSigns-1.7.10-universal-2.1.0.19.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	fognerf{1.7.10-0.3} [Fog Nerf] (fognerf-1.7.10-0.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Forestry{3.3.0.452-unstable} [Forestry for Minecraft] (forestry_1.7.10-3.3.0.452-unstable-modified.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	ibench{1.0.12} [iBench] (ibench-1.7.10-1.0.12.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	iChunUtil{4.1.3} [iChunUtil] (iChunUtil-4.1.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	inventorytweaks{1.59-dev-156-af3bc68} [Inventory Tweaks] (InventoryTweaks-1.59-dev-156.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	MineTweaker3{3.0.9B} [MineTweaker 3] (MineTweaker3-1.7.10-3.0.9C.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	MTRM{1.0} [MineTweakerRecipeMaker] (MineTweakerRecipeMaker-1.7.10-1.1.0.11.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	modtweaker2{1.0} [Mod Tweaker 2] (ModTweaker 2-0.7.b18.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	NEIAddons{1.12.3.13} [NEI Addons] (neiaddons-mc1710-1.12.3.13.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	NEIAddons|Botany{1.12.3.13} [NEI Addons: Botany] (neiaddons-mc1710-1.12.3.13.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	NEIAddons|Forestry{1.12.3.13} [NEI Addons: Forestry] (neiaddons-mc1710-1.12.3.13.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	NEIAddons|CraftingTables{1.12.3.13} [NEI Addons: Crafting Tables] (neiaddons-mc1710-1.12.3.13.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	NEIAddons|ExNihilo{1.12.3.13} [NEI Addons: Ex Nihilo] (neiaddons-mc1710-1.12.3.13.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	neiintegration{1.0.5} [NEI Integration] (NEIIntegration-MC1.7.10-1.0.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	notenoughkeys{@MOD_VERSION@} [NotEnoughKEys] (NotEnoughKeys-1.7.10-1.0.0b29.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	ObsidiPlates{3.0.0.18} [ObsidiPlates] (ObsidiPlates-1.7.10-universal-3.0.0.18.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	OmnisCore{0.0.5} [Omnis Core] (OmnisCore-0.0.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	MapWriter{2.1.1} [MapWriter] (Opis-1.2.3_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Opis{1.2.3} [Opis] (Opis-1.2.3_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	fodc{1.6.0} [Ore Dictionary Converter] (OreDictionaryConverter-1.6.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	harvestcraft{1.7.10d} [Pam's HarvestCraft] (Pam's HarvestCraft 1.7.10f.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	ThermalExpansion{1.7.10R4.0.0B7} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.0B7-21.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Translocator{1.1.1.14} [Translocator] (Translocator-1.7.10-1.1.1.14-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	ttCore{MC1.7.10-0.1.0-61} [ttCore] (ttCore-MC1.7.10-0.1.0-61.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Turbo{1.2.0} [�e�nMinecraft Turbo] (Turbo-1.7.10-1.2.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	VeinMiner{0.21.2} [Vein Miner] (VeinMiner-1.7.10_0.21.2.44.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	VeinMinerModSupport{0.21.2} [Mod Support] (VeinMiner-1.7.10_0.21.2.44.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Waila{1.5.8} [Waila] (Waila-1.5.8a_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	WailaHarvestability{1.1.1} [Waila Harvestability] (WailaHarvestability-mc1.7.x-1.1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	wailaplugins{MC1.7.10-0.0.1-13} [WAILA Plugins] (WAILAPlugins-MC1.7.10-0.0.1-13.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	WaslieCore{1.1} [WaslieCore] (WaslieCore-1.1_B43.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	wawla{1.1.1} [What Are We Looking At] (Wawla-1.1.1_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	WR-CBE|Core{1.4.1.9} [WR-CBE Core] (WR-CBE-1.7.10-1.4.1.9-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	WR-CBE|Addons{1.4.1.9} [WR-CBE Addons] (WR-CBE-1.7.10-1.4.1.9-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	WR-CBE|Logic{1.4.1.9} [WR-CBE Logic] (WR-CBE-1.7.10-1.4.1.9-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	McMultipart{1.1.0.309} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.0.309-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	FMPIntegration{1.0} [FMPIntegration] (fmpintegration-1.2.2-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	ForgeMicroblock{1.1.0.309} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.0.309-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine
	Forestry : Warning: You have mods that change the behavior of Minecraft, ForgeModLoader, and/or Minecraft Forge to your client: 
Optifine
These may have caused this error, and may not be supported. Try reproducing the crash WITHOUT these mods, and report it then.

**Comment by Parker8283** [comment]
Ex Nihilo problem. Report it to Erasmus Crowley.
