### ISSUE TITLE
Infested Crash

### ISSUE THREAD

**Issue by a810587921** [ForestryMC/ForestryMC#558]
java.lang.ClassCastException: forestry.arboriculture.gadgets.TileLeaves cannot be cast to exnihilo.blocks.tileentities.TileEntityLeavesInfested
	at exnihilo.blocks.BlockLeavesInfested.func_149674_a(BlockLeavesInfested.java:60)
	at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:562)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:276)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:920)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
	at java.lang.Thread.run(Unknown Source)

Version: 3.4.0.7

**Comment by mezz** [comment]
Thanks for the report!
This looks like a bug for exnihilo, please report to them here: 
https://bitbucket.org/Erasmus_Crowley/ex-nihilo/issues
