### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by a810587921** [ForestryMC/ForestryMC#576]
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity

	at forestry.core.gadgets.TileAnalyzer.workCycle(TileAnalyzer.java:237)

	at forestry.core.gadgets.TilePowered.func_145845_h(TilePowered.java:61)

	at net.minecraft.world.World.func_72939_s(World.java:2491)

	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:669)

	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:943)

	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423)

	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)

	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)

	at java.lang.Thread.run(Unknown Source)

Version: 1.7.10-3.4.0.7

**Comment by mezz** [comment]
Thanks for the report!
This is fixed in the latest unstable version, it was first reported here: #557
Forestry 3.5.0 stable is coming soon and will have the fix as well.
