### ISSUE TITLE
Crash server

### ISSUE THREAD

**Issue by Shadow232** [ForestryMC/ForestryMC#599]
Get crash on world load
forestry - 3.5.2.10
Forge - 1291

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:2418)

-- Entity being ticked --
Details:
	Entity Type: Forestry.butterflyGE (forestry.lepidopterology.entities.EntityButterfly)
	Entity ID: 11
	Entity Name: entity.Forestry.butterflyGE.name
	Entity's Exact location: 347.39, 85.72, 2021.25
	Entity's Block location: World: (347,85,2021), Chunk: (at 11,5,5 in 21,126; contains blocks 336,0,2016 to 351,255,2031), Region: (0,3; contains chunks 0,96 to 31,127, blocks 0,0,1536 to 511,255,2047)
	Entity's Momentum: 0.17, -0.10, -0.17
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:2418)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:669)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:943)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
	at java.lang.Thread.run(Thread.java:745)

**Comment by mezz** [comment]
Thanks for the report!
This duplicates this issue: https://github.com/ForestryMC/ForestryMC/issues/597
