### ISSUE TITLE
Crash with Version 3.5.3.11

### ISSUE THREAD

**Issue by ReneMuetti** [ForestryMC/ForestryMC#607]
CodeChickenCore 1.0.4.29
Forestry 3.5.3.11
EnderStorage 1.4.6.31
```
---- Minecraft Crash Report ----
// Don't do that.

Time: 10.04.15 10:13
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at net.minecraftforge.fluids.FluidRegistry.isFluidRegistered(FluidRegistry.java:97)
	at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:30)
	at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:58)
	at codechicken.enderstorage.storage.liquid.TankSynchroniser$TankState.<init>(TankSynchroniser.java:36)
	at codechicken.enderstorage.storage.liquid.TileEnderTank$EnderTankState.<init>(TileEnderTank.java:33)
	at codechicken.enderstorage.storage.liquid.TileEnderTank.<init>(TileEnderTank.java:99)
	at codechicken.enderstorage.common.BlockEnderStorage.func_149915_a(BlockEnderStorage.java:60)
	at net.minecraft.block.Block.createTileEntity(Block.java:1446)
	at net.minecraft.world.chunk.Chunk.func_150806_e(Chunk.java:850)
	at net.minecraft.world.World.func_147438_o(World.java:2540)
	at forestry.apiculture.flowers.FlowerRegistry.isAcceptedFlower(FlowerRegistry.java:119)
	at forestry.apiculture.flowers.FlowerProvider.isAcceptedFlower(FlowerProvider.java:40)
	at forestry.apiculture.genetics.Bee.hasFlower(Bee.java:336)
	at forestry.apiculture.BeekeepingLogic.queenWorkTick(BeekeepingLogic.java:138)
	at forestry.apiculture.BeekeepingLogic.update(BeekeepingLogic.java:125)
	at forestry.apiculture.gadgets.TileAlvearyPlain.updateServerSide(TileAlvearyPlain.java:141)
	at forestry.apiculture.gadgets.TileAlveary.func_145845_h(TileAlveary.java:75)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraftforge.fluids.FluidRegistry.isFluidRegistered(FluidRegistry.java:97)
	at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:30)
	at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:58)
	at codechicken.enderstorage.storage.liquid.TankSynchroniser$TankState.<init>(TankSynchroniser.java:36)
	at codechicken.enderstorage.storage.liquid.TileEnderTank$EnderTankState.<init>(TileEnderTank.java:33)
	at codechicken.enderstorage.storage.liquid.TileEnderTank.<init>(TileEnderTank.java:99)
	at codechicken.enderstorage.common.BlockEnderStorage.func_149915_a(BlockEnderStorage.java:60)
	at net.minecraft.block.Block.createTileEntity(Block.java:1446)
	at net.minecraft.world.chunk.Chunk.func_150806_e(Chunk.java:850)
	at net.minecraft.world.World.func_147438_o(World.java:2540)
	at forestry.apiculture.flowers.FlowerRegistry.isAcceptedFlower(FlowerRegistry.java:119)
	at forestry.apiculture.flowers.FlowerProvider.isAcceptedFlower(FlowerProvider.java:40)
	at forestry.apiculture.genetics.Bee.hasFlower(Bee.java:336)
	at forestry.apiculture.BeekeepingLogic.queenWorkTick(BeekeepingLogic.java:138)
	at forestry.apiculture.BeekeepingLogic.update(BeekeepingLogic.java:125)
	at forestry.apiculture.gadgets.TileAlvearyPlain.updateServerSide(TileAlvearyPlain.java:141)
	at forestry.apiculture.gadgets.TileAlveary.func_145845_h(TileAlveary.java:75)

-- Block entity being ticked --
Details:
	Name: forestry.Alveary // forestry.apiculture.gadgets.TileAlvearyPlain
	Block type: ID #423 (tile.for.alveary // forestry.apiculture.gadgets.BlockAlveary)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-320,71,328), Chunk: (at 0,4,8 in -20,20; contains blocks -320,0,320 to -305,255,335), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Actual block type: ID #423 (tile.for.alveary // forestry.apiculture.gadgets.BlockAlveary)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
	Level name: world_nr_2
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 766 Drop: 0
	Level seed: -7165677588934908228
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (232,64,252), Chunk: (at 8,4,12 in 14,15; contains blocks 224,0,240 to 239,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 312835592 game time, 186843838 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 55988 (now: false), thunder time: 19240 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Linux (amd64) version 2.6.32-5-amd64
	Java Version: 1.8.0_31, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 432548800 bytes (412 MB) / 1919942656 bytes (1831 MB) up to 3743416320 bytes (3570 MB)
	JVM Flags: 0 total; 
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 11, tcache: 0, allocated: 1, tallocated: 5070
	FML: MCP v9.05 FML v7.10.104.1360 Minecraft Forge 10.13.3.1360 64 mods loaded, 64 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FML{7.10.104.1360} [Forge Mod Loader] (minecraft_server.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Forge{10.13.3.1360} [Minecraft Forge] (minecraft_server.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CodeChickenCore{1.0.4.29} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	<CoFH ASM>{000} [CoFH ASM Data Initialization] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	IC2{2.2.712-experimental} [IndustrialCraft 2] (IndustrialCraft 2 2.2.712 exp.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	AdvancedSolarPanel{1.7.10-3.5.1} [Advanced Solar Panels] (Advanced Solar Panels 3.5.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	AdvancedMachines{1.1.3} [IC2 Advanced Machines Addon] (AdvancedMachinesAS 1.1.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ArchimedesShips{1.7.10 v1.7.1} [Archimedes' Ships] (ArchimedesShips 1.7.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Backpack{2.0.1} [Backpack] (Backpack 2.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BattleTowers{1.5.1} [Battle Towers] (BattleTowers-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FLabsBF{4.3} [Better Furnaces] (Better Furnaces V4.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BiblioCraft{1.10.2} [BiblioCraft] (BiblioCraft 1.10.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CoFHCore{1.7.10R3.0.0RC7} [CoFH Core] (CoFHCore 3.0.0RC7-211.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Core{6.4.8} [BuildCraft] (Buildcraft 6.4.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Forestry{3.5.0.509-unstable} [Forestry for Minecraft] (Forestry 3.5.0.509.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BiblioWoodsForestry{1.7} [BiblioWoods Forestry Edition] (BiblioWoods Forestry v1.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BinnieCore{2.0-pre8} [Binnie Core] (Binnie Mods 2.0 pre 8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Botany{2.0-pre8} [Botany] (Binnie Mods 2.0 pre 8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ExtraBees{2.0-pre8} [Extra Bees] (Binnie Mods 2.0 pre 8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ExtraTrees{2.0-pre8} [Extra Trees] (Binnie Mods 2.0 pre 8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Genetics{2.0-pre8} [Genetics] (Binnie Mods 2.0 pre 8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Compat{6.4.0} [BuildCraft Compat] (BuildCraft 6.4.2 Compat.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Transport{6.4.8} [BC Transport] (Buildcraft 6.4.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Silicon{6.4.8} [BC Silicon] (Buildcraft 6.4.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Builders{6.4.8} [BC Builders] (Buildcraft 6.4.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Energy{6.4.8} [BC Energy] (Buildcraft 6.4.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Factory{6.4.8} [BC Factory] (Buildcraft 6.4.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ChickenChunks{1.3.4.16} [ChickenChunks] (ChickenChunks 1.3.4.16 universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ComputerCraft{1.73} [ComputerCraft] (ComputerCraft 1.73.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	craftguide{1.6.8.1} [CraftGuide] (CraftGuide 1.6.8.1.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	customnpcs{1.7.10c} [CustomNpcs] (CustomNPCs 1.7.10c 2015-03-03.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	dungeonpack{1.7.10-1.0} [Dungeon Pack] (DungeonPack 1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Dynmap{2.2-alpha-1-106} [Dynmap] (Dynmap-2.2.0-alpha-1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	eplus{3.0.2-d} [Enchanting Plus] (EnchantingPlus 3.0.2d.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	EnderStorage{1.4.6.31} [EnderStorage] (EnderStorage 1.4.6.31.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	factorization.notify{1.0} [Factorization Notification System] (Factorization 0.8.89.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	factorization.dimensionalSlice{0.8.89} [Factorization Dimensional Slices] (Factorization 0.8.89.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	factorization{0.8.89} [Factorization] (Factorization 0.8.89.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	factorization.misc{0.8.89} [Factorization Miscellaneous Nonsense] (Factorization 0.8.89.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FastCraft{1.21} [FastCraft] (FastCraft 1.21.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	GraviSuite{1.7.10-2.0.3} [Graviation Suite] (GraviSuite 2.0.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	IronChest{6.0.62.742} [Iron Chest] (IronChest 6.0.62.742.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	JABBA{1.2.0b} [JABBA] (Jabba 1.2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft 4.2.3.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Railcraft{9.5.0.8} [Railcraft] (Railcraft 9.5.0.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ThermalFoundation{1.7.10R1.0.0RC7} [Thermal Foundation] (ThermalFoundation 1.0.0RC7-62.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ThermalExpansion{1.7.10R4.0.0RC7} [Thermal Expansion] (ThermalExpansion 4.0.0RC7-141.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MagicBees{1.7.10-2.1.22} [Magic Bees] (MagicBees 2.1.22.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	cfm{3.4.7} [�9MrCrayfish's Furniture Mod] (MrCrayfish Furniture Mod v3.4.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MultiPageChest{1.3.4} [Multi Page Chest] (MultiPageChest 1.3.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Mystcraft{0.11.2.01} [Mystcraft] (Mystcraft 0.11.2.01.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	NetherOres{1.7.10R2.3.0RC4} [Nether Ores] (NetherOres 2.3.0RC4-4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	RedstoneArsenal{1.7.10R1.1.0RC7} [Redstone Arsenal] (RedstoneArsenal 1.1.0RC7-65.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	libsandstone{1.0.0} [libsandstone] (LibSandstone 1.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	xreliquary{1.2.DEV} [Reliquary] (Reliquary 1.2.160.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	SSTOW{1.7.10-0.1-RC9-7} [Soul Shards: The Old Ways] (SoulShards TOW 0.1-RC9-7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	StevesCarts{2.0.0.b18} [Steve's Carts 2] (StevesCarts 2.0.0 b18.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ThaumcraftMobAspects{1.7.x-2B} [Thaumcraft Mob Aspects] (Thaumcraft Mob Aspects 1.7.x 2B Sapshot 17.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	TwilightForest{2.3.5} [The Twilight Forest] (The Twilight Forest 2.3.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	bspkrsCore{6.16} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.16.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Treecapitator{1.7.10} [Treecapitator] (Treecapitator 2.0.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	AS_UpdateCheck{1.1.6} [AtomicStryker Update Check Mod] (UpdateCheckerMod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CoFHCore: -[1.7.10]3.0.0RC7-211
	ThermalFoundation: -[1.7.10]1.0.0RC7-62
	ThermalExpansion: -[1.7.10]4.0.0RC7-141
	NetherOres: Lacking version information.
	RedstoneArsenal: -[1.7.10]1.1.0RC7-65
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 0 / 7; []
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)
```
CodeChickenCore 1.0.4.29
Forestry 3.4.0.7
EnderStorage 1.4.6.31
this Combo works fine ...

can you please fix this Crash?
Thanks for support :)

**Comment by mezz** [comment]
Thanks for the report!
This looks like a duplicate issue of this one: https://github.com/ForestryMC/ForestryMC/issues/604
They claimed it was a Forge bug. Downgrading to stable Forge (10.13.2.1291) should fix the error.

**Comment by mezz** [comment]
Fixed in Forestry in the latest unstable version.
