### ISSUE TITLE
Unstable Build 528 now crashing with older Forge version.

### ISSUE THREAD

**Issue by Blood-Asp** [ForestryMC/ForestryMC#612]
After fixing the fluids of the forge 1355 version in build 528, using older versions of forge crashes forestry when opening a Gui.

Description: Exception in server tick loop

java.lang.NoSuchMethodError: net.minecraftforge.fluids.FluidStack.getFluidID()I
	at forestry.core.fluids.TankManager.updateGuiData(TankManager.java:202)
	at forestry.core.fluids.TankManager.updateGuiData(TankManager.java:186)
	at forestry.farming.gui.ContainerFarm.func_75142_b(ContainerFarm.java:93)
	at net.minecraft.inventory.Container.func_75132_a(SourceFile:54)
	at forestry.farming.gui.ContainerFarm.func_75132_a(ContainerFarm.java:103)
	at cpw.mods.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:88)
	at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2209)
	at forestry.farming.gadgets.TileFarm.openGui(TileFarm.java:55)
	at forestry.core.gadgets.BlockStructure.func_149727_a(BlockStructure.java:79)
	at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:376)
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by Parker8283** [comment]
Side affect of Forge making breaking changes. Nothing we can really do. Use the older version of Forestry with the older version of Forge.

**Comment by Blood-Asp** [comment]
Then pease set the required forge version to 1355 so it does not start with the wrong version.
Crashing somewhere midgame is not ideal.

**Comment by Parker8283** [comment]
That is doable

**Comment by mezz** [comment]
Thanks for the report!
Sorry, I thought `getFluidID()` was available going back much farther that it is. Will do.
