### ISSUE TITLE
Analyzer caused server crash

### ISSUE THREAD

**Issue by healiethellama** [ForestryMC/ForestryMC#640]
[22:42:35] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking block entity
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:642) ~[MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) ~[lt.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) ~[MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
Caused by: java.lang.NullPointerException
at forestry.core.gadgets.TileAnalyzer.workCycle(TileAnalyzer.java:237) ~[TileAnalyzer.class:?]
at forestry.core.gadgets.TilePowered.func_145845_h(TilePowered.java:61) ~[TilePowered.class:?]
at net.minecraft.world.World.func_72939_s(World.java:1939) ~[ahb.class:?]
at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489) ~[mt.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636) ~[MinecraftServer.class:?]
... 4 more

**Comment by mezz** [comment]
Thanks for the report!
Please post the full crash log to http://gist.github.com

**Comment by healiethellama** [comment]
Distillery is crashing too, I'll work that in.

**Comment by healiethellama** [comment]
https://gist.github.com/healiethellama/bb5300569a39a9659a2b#file-gistfile1-txt

**Comment by healiethellama** [comment]
nvm distillery is different mod, just dunno how to change the thing..

**Comment by healiethellama** [comment]
nvm distillery is different mod, will have to go elsewhere for that one.

**Comment by mezz** [comment]
It looks like your version of Forestry is out of date. 
This is the same issue: #557
Please update to the latest Forestry and it will work fine.

**Comment by healiethellama** [comment]
We're using Direwolf 20 for 1.7.10, version 1.2.1, so it'll have to wait until the mod pack catches up.
