### ISSUE TITLE
Crash with Buildcraft 7

### ISSUE THREAD

**Issue by Wykks** [ForestryMC/ForestryMC#653]
Getting crash with buildcraft 7 and Forestry 3.5.4.13

	---- Minecraft Crash Report ----
	// Daisy, daisy...

	Time: 08/05/15 17:16
	Description: There was a severe problem during mod loading that has caused the game to fail

	cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: buildcraft/core/CreativeTabBuildCraft
		at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
		at cpw.mods.fml.common.Loader.initializeMods(Loader.java:719)
		at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:309)
		at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)
		at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
		at net.minecraft.client.main.Main.main(SourceFile:148)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
		at java.lang.reflect.Method.invoke(Unknown Source)
		at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
		at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	Caused by: java.lang.NoClassDefFoundError: buildcraft/core/CreativeTabBuildCraft
		at forestry.pipes.proxy.ProxyPipes.initPropolisPipe(ProxyPipes.java:35)
		at forestry.pipes.proxy.ClientProxyPipes.initPropolisPipe(ClientProxyPipes.java:28)
		at forestry.plugins.PluginPropolisPipe.postInit(PluginPropolisPipe.java:64)
		at forestry.plugins.PluginManager.runPostInit(PluginManager.java:296)
		at forestry.core.ForestryCore.postInit(ForestryCore.java:118)
		at forestry.core.ForestryClient.postInit(ForestryClient.java:41)
		at forestry.Forestry.postInit(Forestry.java:117)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
		at java.lang.reflect.Method.invoke(Unknown Source)
		at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
		at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
		at java.lang.reflect.Method.invoke(Unknown Source)
		at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
		at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
		at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
		at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
		at com.google.common.eventbus.EventBus.post(EventBus.java:275)
		at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
		at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
		at java.lang.reflect.Method.invoke(Unknown Source)
		at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
		at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
		at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
		at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
		at com.google.common.eventbus.EventBus.post(EventBus.java:275)
		at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
		at cpw.mods.fml.common.Loader.initializeMods(Loader.java:717)
		... 10 more
	Caused by: java.lang.ClassNotFoundException: buildcraft.core.CreativeTabBuildCraft
		at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
		at java.lang.ClassLoader.loadClass(Unknown Source)
		at java.lang.ClassLoader.loadClass(Unknown Source)
		... 43 more
	Caused by: java.lang.NullPointerException

**Comment by Parker8283** [comment]
Forestry is built with BC 6. BC 7 is, by nature of it having increased the major version number, a major update, causing breaking changes to the API and internal code. Because of that, it won't work the current Forestry. Last I checked, BC 7 is still in beta. Until it's stable, Forestry will continue to support BC 6,

**Comment by Vexatos** [comment]
Pretty sure @asiekierka already has a fork for BC 7 running and will PR it once BC 7 is considered "stable".

**Comment by asiekierka** [comment]
As a workaround, disable Apiarist Pipes.

**Comment by Wykks** [comment]
Yeah sorry, I knew that. That's why I tried to disable the integration like that (which is not enough) : 

    # Compatibility plugin for BuildCraft 6.
    B:buildcraft.fuels=false

    # Compatibility plugin for BuildCraft 6.
    B:buildcraft.recipes=false

    # Compatibility plugin for BuildCraft 6.
    B:buildcraft.statements=false

    # Compatibility plugin for BuildCraft 6.
    B:buildcraft.transport=false

Got it working, by disabling apiarist pipe : 


    # Adds the apiarist's pipe for beekeeping if apiculture is enabled and BuildCraft 6 is present.
    B:propolis.pipe=false


Thanks !
