### ISSUE TITLE
Forestry 3.5.4.13, 3.6.0.536, 3.6.0.555  - java.lang.Throwable errors

### ISSUE THREAD

**Issue by MBfromOK** [ForestryMC/ForestryMC#656]
Game seems to be loading fine and then I see all these red errors fly by... Server is laggy and keeps saying it is behind.

Server will finish loading, but game is jumpy and I have issues staying connected.

I haven't done a character for character comparison, but have seen Throwable errors for all the above versions

Forge 1.7.10.-10.13.3.1403
MinecraftServer 1.7.10

```
[00:40:11] [Server thread/INFO] [Forestry/Forestry]: Recreating all gamemode definitions from the defaults. This may be caused by an upgrade
[00:40:11] [Server thread/INFO] [STDERR/Forestry]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.NullPointerException
[00:40:11] [Server thread/INFO] [STDERR/Forestry]: [java.lang.Throwable$WrappedPrintStream:println:748]:        at forestry.core.config.Config.CopyFileToFS(Config.java:345)
[00:40:11] [Server thread/INFO] [STDERR/Forestry]: [java.lang.Throwable$WrappedPrintStream:println:748]:        at forestry.core.config.Config.loadModes(Config.java:286)
[00:40:11] [Server thread/INFO] [STDERR/Forestry]: [java.lang.Throwable$WrappedPrintStream:println:748]:        at forestry.core.config.Config.load(Config.java:136)
[00:40:11] [Server thread/INFO] [STDERR/Forestry]: [java.lang.Throwable$WrappedPrintStream:println:748]:        at forestry.core.ForestryCore.preInit(ForestryCore.java:55)
[00:40:11] [Server thread/INFO] [STDERR/Forestry]: [java.lang.Throwable$WrappedPrintStream:println:748]:        at forestry.Forestry.preInit(Forestry.java:107)
[00:40:11] [Server thread/INFO] [STDERR/Forestry]: [java.lang.Throwable$WrappedPrintStream:println:748]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[00:40:11] [Server thread/INFO] [STDERR/Forestry]: [java.lang.Throwable$WrappedPrintStream:println:748]:        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[00:40:11] [Server thread/INFO] [STDERR/Forestry]: [java.lang.Throwable$WrappedPrintStream:println:748]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[00:40:11] [Server thread/INFO] [STDERR/Forestry]: [java.lang.Throwable$WrappedPrintStream:println:748]:        at java.lang.reflect.Method.invoke(Method.java:497)
[00:40:11] [Server thread/INFO] [STDERR/Forestry]: [java.lang.Throwable$WrappedPrintStream:println:748]:        at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
[00:40:11] [Server thread/INFO] [STDERR/Forestry]: [java.lang.Throwable$WrappedPrintStream:println:748]:        at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
[00:40:11] [Server thread/INFO] [STDERR/Forestry]: [java.lang.Throwable$WrappedPrintStream:println:748]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[00:40:11] [Server thread/INFO] [STDERR/Forestry]: [java.lang.Throwable$WrappedPrintStream:println:748]:        at java.lang.reflect.Method.invoke(Method.java:497)
[00:40:11] [Server thread/INFO] [STDERR/Forestry]: [java.lang.Throwable$WrappedPrintStream:println:748]:        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
[00:40:11] [Server thread/INFO] [STDERR/Forestry]: [java.lang.Throwable$WrappedPrintStream:println:748]:        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
[00:40:11] [Server thread/INFO] [STDERR/Forestry]: [java.lang.Throwable$WrappedPrintStream:println:748]:        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
[00:40:11] [Server thread/INFO] [STDERR/Forestry]: [java.lang.Throwable$WrappedPrintStream:println:748]:        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
[00:40:11] [Server thread/INFO] [STDERR/Forestry]: [java.lang.Throwable$WrappedPrintStream:println:748]:        at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[00:40:11] [Server thread/INFO] [STDERR/Forestry]: [java.lang.Throwable$WrappedPrintStream:println:748]:        at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
[00:40:11] [Server thread/INFO] [STDERR/Forestry]: [java.lang.Throwable$WrappedPrintStream:println:748]:        at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
[00:40:11] [Server thread/INFO] [STDERR/Forestry]: [java.lang.Throwable$WrappedPrintStream:println:748]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[00:40:11] [Server thread/INFO] [STDERR/Forestry]: [java.lang.Throwable$WrappedPrintStream:println:748]:        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[00:40:11] [Server thread/INFO] [STDERR/Forestry]: [java.lang.Throwable$WrappedPrintStream:println:748]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[00:40:11] [Server thread/INFO] [STDERR/Forestry]: [java.lang.Throwable$WrappedPrintStream:println:748]:        at java.lang.reflect.Method.invoke(Method.java:497)
[00:40:11] [Server thread/INFO] [STDERR/Forestry]: [java.lang.Throwable$WrappedPrintStream:println:748]:        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
[00:40:11] [Server thread/INFO] [STDERR/Forestry]: [java.lang.Throwable$WrappedPrintStream:println:748]:        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
[00:40:11] [Server thread/INFO] [STDERR/Forestry]: [java.lang.Throwable$WrappedPrintStream:println:748]:        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
[00:40:11] [Server thread/INFO] [STDERR/Forestry]: [java.lang.Throwable$WrappedPrintStream:println:748]:        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
[00:40:11] [Server thread/INFO] [STDERR/Forestry]: [java.lang.Throwable$WrappedPrintStream:println:748]:        at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[00:40:11] [Server thread/INFO] [STDERR/Forestry]: [java.lang.Throwable$WrappedPrintStream:println:748]:        at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
[00:40:11] [Server thread/INFO] [STDERR/Forestry]: [java.lang.Throwable$WrappedPrintStream:println:748]:        at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:533)
[00:40:11] [Server thread/INFO] [STDERR/Forestry]: [java.lang.Throwable$WrappedPrintStream:println:748]:        at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:88)
[00:40:11] [Server thread/INFO] [STDERR/Forestry]: [java.lang.Throwable$WrappedPrintStream:println:748]:        at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:314)
[00:40:11] [Server thread/INFO] [STDERR/Forestry]: [java.lang.Throwable$WrappedPrintStream:println:748]:        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:117)
[00:40:11] [Server thread/INFO] [STDERR/Forestry]: [java.lang.Throwable$WrappedPrintStream:println:748]:        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
[00:40:11] [Server thread/INFO] [STDERR/Forestry]: [java.lang.Throwable$WrappedPrintStream:println:748]:        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

**Comment by Nirek-K** [comment]
It can't write to the file system, file/folder permission issue of some kind.

**Comment by MBfromOK** [comment]
ok, thanks, will reset file permissions and see if that helps...
