### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by roboliutas** [ForestryMC/ForestryMC#658]
Im probably dumb and dont know how to fix it but

---- Minecraft Crash Report ----
// I blame Dinnerbone.

Time: 5/10/15 4:13 PM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: forestry/apiculture/FlowerProviderVanilla
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:162)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:695)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:288)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:541)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: forestry/apiculture/FlowerProviderVanilla
	at exnihilo.compatibility.foresty.HiveRegistry.<clinit>(HiveRegistry.java:25)
	at exnihilo.compatibility.foresty.Forestry.loadCompatibility(Forestry.java:28)
	at exnihilo.ExNihilo.PostInitialize(ExNihilo.java:132)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:694)
	... 10 more
Caused by: java.lang.ClassNotFoundException: forestry.apiculture.FlowerProviderVanilla
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 39 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 41 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (x86) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 324563480 bytes (309 MB) / 659808256 bytes (629 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.85.1291 Minecraft Forge 10.13.2.1291 82 mods loaded, 82 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	FML{7.10.85.1291} [Forge Mod Loader] (forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Forge{10.13.2.1291} [Minecraft Forge] (forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	CodeChickenCore{1.0.4.35} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	NotEnoughItems{1.0.4.90} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.4.90-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	PlayerAPI{1.3} [Player API] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	RenderPlayerAPI{1.3} [Render Player API] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	SmartCore{1.0.2} [Smart Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	VeinMiner_coremod{null_build-null} [Core mod] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	OpenModsCore{0.7.1} [OpenModsCore] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	debug{1.0} [debug] (denseores-2.(-1).0 (alpha 1.8).jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	dynamicswordskills{1.7.10-1.6.5} [Dynamic Sword Skills] (1.7.10-dynamicswordskills-1.6.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	AppleCore{1.0.2} [AppleCore] (AppleCore-mc1.7.10-1.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	CoFHCore{1.7.10R3.0.2} [CoFH Core] (CoFHCore-[1.7.10]3.0.2-262.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	BuildCraft|Core{6.4.14} [BuildCraft] (buildcraft-6.4.14.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Forestry{3.5.6.15} [Forestry for Minecraft] (forestry_1.7.10-3.5.6.15.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	BinnieCore{2.0-pre8} [Binnie Core] (binnie-mods-2.0-pre8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Botany{2.0-pre8} [Botany] (binnie-mods-2.0-pre8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	ExtraBees{2.0-pre8} [Extra Bees] (binnie-mods-2.0-pre8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	ExtraTrees{2.0-pre8} [Extra Trees] (binnie-mods-2.0-pre8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Genetics{2.0-pre8} [Genetics] (binnie-mods-2.0-pre8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	qmunitylib{1.0} [QmunityLib] (QmunityLib-1.7.10-0.1.107-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	bluepower{0.2.928} [Blue Power] (BluePower-1.7.10-0.2.928-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Botania{r1.6-187} [Botania] (Botania r1.6-187.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	BuildCraft|Transport{6.4.14} [BC Transport] (buildcraft-6.4.14.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	BuildCraft|Silicon{6.4.14} [BC Silicon] (buildcraft-6.4.14.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	BuildCraft|Builders{6.4.14} [BC Builders] (buildcraft-6.4.14.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	BuildCraft|Energy{6.4.14} [BC Energy] (buildcraft-6.4.14.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	BuildCraft|Factory{6.4.14} [BC Factory] (buildcraft-6.4.14.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Waila{1.5.8} [Waila] (Waila-1.5.8a_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Calculator{Universal} [Calculator] (Calculator-1.7.10-1.6.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	ChickenChunks{1.3.4.19} [ChickenChunks] (ChickenChunks-1.7.10-1.3.4.19-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	clockworkphase{1.7.10_1.0c} [Clockwork Phase] (clockworkphase-1.7.10_1.0c.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	exnihilo{1.38-21} [Ex Nihilo] (Ex-Nihilo-1.38-21.jar) Unloaded->Constructed->Pre-initialized->Initialized->Errored
	exastris{MC1.7.10-1.16-26} [Ex Astris] (Ex-Astris-MC1.7.10-1.16-26.jar) Unloaded->Constructed->Pre-initialized->Initialized->Errored
	ExtraUtilities{1.2.1} [Extra Utilities] (extrautilities-1.2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	FlatBedrockx{1.0.2} [FlatBedrock Xplosion's Edition] (FlatBedrock-1.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	inventorytweaks{1.58-147-645ca10} [Inventory Tweaks] (InventoryTweaks-1.58-147.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	IronChest{6.0.41.729} [Iron Chest] (ironchest-1.7.10-6.0.41.729-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	JABBA{1.1.4} [JABBA] (Jabba-1.1.4_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	lootbags{1.5.2} [Loot Bags] (LootBags-1.7.10-1.5.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	lycanitesmobs{1.10.13.2 - MC 1.7.10} [Lycanites Mobs] (LycanitesMobsComplete 1.10.13.2 [1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	freshwatermobs{1.10.13.2 - MC 1.7.10} [Lycanites Freshwater Mobs] (LycanitesMobsComplete 1.10.13.2 [1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	demonmobs{1.10.13.2 - MC 1.7.10} [Lycanites Demon Mobs] (LycanitesMobsComplete 1.10.13.2 [1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	desertmobs{1.10.13.2 - MC 1.7.10} [Lycanites Desert Mobs] (LycanitesMobsComplete 1.10.13.2 [1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	mountainmobs{1.10.13.2 - MC 1.7.10} [Lycanites Mountain Mobs] (LycanitesMobsComplete 1.10.13.2 [1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	junglemobs{1.10.13.2 - MC 1.7.10} [Lycanites Jungle Mobs] (LycanitesMobsComplete 1.10.13.2 [1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	swampmobs{1.10.13.2 - MC 1.7.10} [Lycanites Swamp Mobs] (LycanitesMobsComplete 1.10.13.2 [1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	shadowmobs{1.10.13.2 - MC 1.7.10} [Lycanites Shadow Mobs] (LycanitesMobsComplete 1.10.13.2 [1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	infernomobs{1.10.13.2 - MC 1.7.10} [Lycanites Inferno Mobs] (LycanitesMobsComplete 1.10.13.2 [1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	saltwatermobs{1.10.13.2 - MC 1.7.10} [Lycanites Saltwater Mobs] (LycanitesMobsComplete 1.10.13.2 [1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	forestmobs{1.10.13.2 - MC 1.7.10} [Lycanites Forest Mobs] (LycanitesMobsComplete 1.10.13.2 [1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	plainsmobs{1.10.13.2 - MC 1.7.10} [Lycanites Plains Mobs] (LycanitesMobsComplete 1.10.13.2 [1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	arcticmobs{1.10.13.2 - MC 1.7.10} [Lycanites Arctic Mobs] (LycanitesMobsComplete 1.10.13.2 [1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	malisiscore{1.7.10-0.11.4} [MalisisCore] (malisiscore-1.7.10-0.11.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	malisisdoors{1.7.10-1.5.1} [Malisis' Doors] (malisisdoors-1.7.10-1.5.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	MapWriter{2.1.2} [MapWriter] (MapWriter-1.7.10-2.1.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	NEIAddons{1.12.3.11} [NEI Addons] (neiaddons-mc1710-1.12.3.11.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	NEIAddons|Botany{1.12.3.11} [NEI Addons: Botany] (neiaddons-mc1710-1.12.3.11.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	NEIAddons|Forestry{1.12.3.11} [NEI Addons: Forestry] (neiaddons-mc1710-1.12.3.11.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	NEIAddons|CraftingTables{1.12.3.11} [NEI Addons: Crafting Tables] (neiaddons-mc1710-1.12.3.11.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	NEIAddons|ExNihilo{1.12.3.11} [NEI Addons: Ex Nihilo] (neiaddons-mc1710-1.12.3.11.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	neiintegration{1.0.7} [NEI Integration] (NEIIntegration-MC1.7.10-1.0.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	neresources{0.1.0.95} [Not Enough Resources] (NotEnoughResources-1.7.10-0.1.0.95.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	OpenMods{0.7.1} [OpenMods] (OpenModsLib-1.7.10-0.7.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	OpenBlocks{1.4.1} [OpenBlocks] (OpenBlocks-1.7.10-1.4.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	harvestcraft{1.7.10g} [Pam's HarvestCraft] (Pam's HarvestCraft 1.7.10g.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	ProjectE{1.7.10-PE1.4.5} [ProjectE] (ProjectE-1.7.10-PE1.4.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	quantumflux{1.1.0} [QuantumFlux] (QuantumFlux-1.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	RandomThings{2.2.3} [Random Things] (RandomThings-2.2.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	rftools{2.83} [RFTools] (rftools-2.83.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Roguelike{1.3.5} [Roguelike Dungeons] (roguelike-1.7.10-1.3.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	secretroomsmod{4.7.1} [The SecretRoomsMod] (secretroomsmod-1.7.10-4.7.1.413.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	SmartMoving{15.5} [Smart Moving] (SmartMoving-1.7.10-15.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	SmartRender{2.1} [Smart Render] (SmartRender-1.7.10-2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	SolarExpansion{1.5a} [Solar Expansion] (SolarExpansion-Basic-1.5a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	VeinMiner{0.21.2} [Vein Miner] (VeinMiner-1.7.10_0.21.2.43.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	VeinMinerModSupport{0.21.2} [Mod Support] (VeinMiner-1.7.10_0.21.2.43.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	wawla{1.2.1} [What Are We Looking At] (Wawla-1.2.1_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	THKaguyaMod{2.90-1.7.10} [Itutu no Nandai MOD+ (Touhou Items Mod)] (?????MOD+ ver2.90-1.7.10.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	OpenModsLib class transformers: [stencil_patches:FINISHED],[movement_callback:ACTIVATED],[map_gen_fix:ENABLED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
	CoFHCore: -[1.7.10]3.0.2-262
	Stencil buffer state: Function set: GL30, pool: forge, bits: 8

**Comment by roboliutas** [comment]
With a little bit of digging  found the fix for it...
