### ISSUE TITLE
Crash when opening Thermionic Fabricator

### ISSUE THREAD

**Issue by AngleWyrm** [ForestryMC/ForestryMC#671]
---- Minecraft Crash Report ----
// On the bright side, I bought you a teddy bear!

Time: 5/17/15 8:40 PM
Description: Unexpected error

java.lang.IllegalArgumentException: Cannot create a fluidstack from a null fluid
	at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:36)
	at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:67)
	at forestry.core.fluids.TankManager.processGuiUpdate(TankManager.java:232)
	at forestry.core.gui.ContainerLiquidTanks.func_75137_b(ContainerLiquidTanks.java:90)
	at net.minecraft.client.network.NetHandlerPlayClient.func_147245_a(NetHandlerPlayClient.java:1151)
	at net.minecraft.network.play.server.S31PacketWindowProperty.func_148833_a(SourceFile:26)
	at net.minecraft.network.play.server.S31PacketWindowProperty.func_148833_a(SourceFile:9)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1602)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:286)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:376)
	at org.multimc.EntryPoint.listen(EntryPoint.java:165)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)

**Comment by mezz** [comment]
Thanks for the report!
Can you please post the full crash report to http://gist.github.com?

**Comment by mezz** [comment]
@AngleWyrm Can you please post the full crash report to http://gist.github.com?
