### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by LemonNick** [ForestryMC/ForestryMC#718]
java.util.ConcurrentModificationException
    at java.util.HashMap$HashIterator.nextEntry(HashMap.java:926)
    at java.util.HashMap$KeyIterator.next(HashMap.java:960)
    at net.minecraft.entity.EntityTracker.func_72788_a(EntityTracker.java:271)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:978)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
    at java.lang.Thread.run(Thread.java:744)

**Comment by mezz** [comment]
Thanks for the report!
Please post the full crash log to http://gist.github.com and link back here.
There is nothing here that looks like it's from Forestry.
