### ISSUE TITLE
Crashing on launch on Mac with recommended Forge build

### ISSUE THREAD

**Issue by Bojkowski** [ForestryMC/ForestryMC#770]
Hey, I'm a Java noob so hoping this isn't some lame user error. I had a version of Forestry working for a little while (I can't remember which one) but after updating it either 'shuts down internal server' on launch or crashes Minecraft. Have tried launching via MultiMC and Minecraft crashes out completely. Wondering if I'm using the wrong version of Java, but have no clue. I'm on a Mac. Here's the crash report from MultiMC...

[09:33:58] [main/INFO] [FML/]: Forge Mod Loader version 7.10.25.1207 for Minecraft 1.7.10 loading
[09:33:58] [main/INFO] [FML/]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_51, running on Mac OS X:x86_64:10.10.4, installed at /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home
[09:33:58] [main/DEBUG] [FML/]: Java classpath at launch is /Applications/MultiMC.app/Contents/MacOS/jars/NewLaunch.jar
[09:33:58] [main/DEBUG] [FML/]: Java library path at launch is /Applications/MultiMC.app/Contents/MacOS/instances/Boiks-Craft/natives
[09:33:58] [main/DEBUG] [FML/]: Enabling runtime deobfuscation
[09:33:58] [main/DEBUG] [FML/]: Instantiating coremod class FMLCorePlugin
[09:33:58] [main/DEBUG] [FML/]: Added access transformer class cpw.mods.fml.common.asm.transformers.AccessTransformer to enqueued access transformers
[09:33:58] [main/DEBUG] [FML/]: Enqueued coremod FMLCorePlugin
[09:33:58] [main/DEBUG] [FML/]: Instantiating coremod class FMLForgePlugin
[09:33:58] [main/DEBUG] [FML/]: Added access transformer class net.minecraftforge.transformers.ForgeAccessTransformer to enqueued access transformers
[09:33:58] [main/DEBUG] [FML/]: Enqueued coremod FMLForgePlugin
[09:33:58] [main/DEBUG] [FML/]: All fundamental core mods are successfully located
[09:33:58] [main/DEBUG] [FML/]: Discovering coremods
[09:33:58] [main/DEBUG] [FML/]: Examining for coremod candidacy forestry_1.7.10-3.6.3.20.jar
[09:33:58] [main/DEBUG] [FML/]: Not found coremod data in forestry_1.7.10-3.6.3.20.jar
[09:33:58] [main/INFO] [LaunchWrapper/]: Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[09:33:58] [main/INFO] [LaunchWrapper/]: Loading tweak class name cpw.mods.fml.common.launcher.FMLDeobfTweaker
[09:33:58] [main/INFO] [LaunchWrapper/]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[09:33:58] [main/ERROR] [LaunchWrapper/]: Unable to launch
java.util.ConcurrentModificationException
    at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901) ~[?:1.8.0_51]
    at java.util.ArrayList$Itr.remove(ArrayList.java:865) ~[?:1.8.0_51]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:117) [launchwrapper-1.9.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.9.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
    at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310) [NewLaunch.jar:?]
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394) [NewLaunch.jar:?]
    at org.multimc.EntryPoint.listen(EntryPoint.java:170) [NewLaunch.jar:?]
    at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]

**Comment by mezz** [comment]
Thanks for the report!
Unfortunately I have no idea what this crash means. I suggest you back up your world and try removing some mods until it works again.  
Forestry works with Java 6, 7, and 8, and there's nothing here that seems Forestry-related or looks familiar.

**Comment by Bojkowski** [comment]
Weirdly installing FastCraft seems to have fixed the problem. Go figure. :)

**Comment by mezz** [comment]
Well, glad that worked. ??? Thanks for reporting back.

@sfPlayer1 any idea what happened here?

**Comment by Player3324** [comment]
It is clearly a bug in FML, CoreModManager.sortTweakList modifies "tweakers" while Launch.launch uses an iterator over it.
