### ISSUE TITLE
java.lang.NullPointerException: Ticking block entity

### ISSUE THREAD

**Issue by 008** [ForestryMC/ForestryMC#799]
http://pastebin.com/9gRaaHPu

java.lang.NullPointerException: Ticking block entity
    at forestry.apiculture.BeekeepingLogic.isQueenAlive(BeekeepingLogic.java:302)
    at forestry.apiculture.BeekeepingLogic.hasHealthyQueen(BeekeepingLogic.java:316)
    at forestry.apiculture.BeekeepingLogic.canWork(BeekeepingLogic.java:145)
    at forestry.apiculture.gadgets.TileBeehouse.updateServerSide(TileBeehouse.java:200)
    at forestry.core.gadgets.TileForestry.func_145845_h(TileForestry.java:132)
    at net.minecraft.world.World.func_72939_s(World.java:2513)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:669)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:954)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
    at java.lang.Thread.run(Thread.java:745)

**Comment by mezz** [comment]
Thanks for the report!
Can you please back up your world and try the [latest unstable build](http://jenkins.ic2.player.to/job/Forestry_Dev/)? This should be fixed there.

**Comment by mezz** [comment]
@008 are you able to test with the new version?

**Comment by 008** [comment]
@mezz i cant see crash again after clean (/regen) that chunk.

**Comment by mezz** [comment]
Ok I will mark this as resolved for now. If you see the issue with the latest unstable build, please report back.
