### ISSUE TITLE
Game crash: magicbees.bees.BeeMutation

### ISSUE THREAD

**Issue by Protheus** [ForestryMC/ForestryMC#839]
using:

Forestry_1.7.10-4.0.0.690-unstable to 705
Magicbees-1.7.10-2.3.4
Magicbees-1.7.10-2.3.5

Getting the error below (http://pastebin.com/ydEcXFnY) - not sure if it is forestry or magic bees. Any suggestions ?

cpw.mods.fml.common.LoaderException: java.lang.AbstractMethodError
        at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
        at cpw.mods.fml.common.Loader.initializeMods(Loader.java:744)
        at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
        at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)
        at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
        at net.minecraft.client.main.Main.main(SourceFile:148)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.AbstractMethodError
        at forestry.apiculture.genetics.BeeHelper.registerMutation(BeeHelper.java:244)
        at magicbees.bees.BeeMutation.<init>(BeeMutation.java:409)
        at magicbees.bees.BeeMutation.setupMutations(BeeMutation.java:47)
        at magicbees.bees.BeeManager.lateBeeInit(BeeManager.java:41)
        at magicbees.main.MagicBees.postInit(MagicBees.java:71)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
        at com.google.common.eventbus.EventBus.post(EventBus.java:275)
        at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
        at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
        at com.google.common.eventbus.EventBus.post(EventBus.java:275)
        at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
        at cpw.mods.fml.common.Loader.initializeMods(Loader.java:742)
        ... 10 more

**Comment by mezz** [comment]
The crash doesn't make a lot of sense, but I'm pretty sure Magic Bees isn't compatible with Forestry Unstable right now.

**Comment by Protheus** [comment]
Yep. Using the normal version all is well..so lets wait a bit more :-) thank you for the feedback.
