### ISSUE TITLE
TileStairs NullPointerException

### ISSUE THREAD

**Issue by Cooki3Monsta** [ForestryMC/ForestryMC#877]
Getting this error causing server to crash. Forestry Version FORESTRY_1.7.10-3.6.3.20

[20:06:16] [Server thread/ERROR]:   Cause of unexpected exception was
java.lang.NullPointerException
    at forestry.arboriculture.gadgets.TileStairs.writeData(TileStairs.java:80) ~[TileStairs.class:?]
    at forestry.core.network.PacketTileStream.writeData(PacketTileStream.java:39) ~[PacketTileStream.class:?]
    at forestry.core.network.ForestryPacket.getPacket(ForestryPacket.java:40) ~[ForestryPacket.class:?]
    at forestry.arboriculture.gadgets.TileStairs.func_145844_m(TileStairs.java:71) ~[TileStairs.class:?]
    at net.minecraft.entity.player.EntityPlayerMP.func_147097_b(EntityPlayerMP.java:699) ~[mw.class:?]
    at net.minecraft.entity.player.EntityPlayerMP.func_70071_h_(EntityPlayerMP.java:374) ~[mw.class:?]
    at net.minecraft.world.World.func_72866_a(World.java:2655) ~[ahb.class:?]
    at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:837) ~[mt.class:?]
    at net.minecraft.world.World.func_72870_g(World.java:2607) ~[ahb.class:?]
    at net.minecraft.world.World.func_72939_s(World.java:2423) ~[ahb.class:?]
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:669) ~[mt.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:954) ~[MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) ~[lt.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809) ~[MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669) [MinecraftServer.class:?]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_60]

**Comment by mezz** [comment]
Thanks for the report!
I have no idea how they got corrupted, but I'll make them turn to larch instead of crashing.
Fixed in 3.6.11
