### ISSUE TITLE
at forestry.arboriculture.gadgets.TileStairs.writeData(TileStairs.java:80)

### ISSUE THREAD

**Issue by CubeBix** [ForestryMC/ForestryMC#912]
java.lang.NullPointerException: Exception ticking world
    at forestry.arboriculture.gadgets.TileStairs.writeData(TileStairs.java:80)
    at forestry.core.network.PacketTileStream.writeData(PacketTileStream.java:39)
    at forestry.core.network.ForestryPacket.getPacket(ForestryPacket.java:40)
    at forestry.arboriculture.gadgets.TileStairs.func_145844_m(TileStairs.java:71)
    at net.minecraft.server.management.PlayerManager$PlayerInstance.func_151252_a(PlayerManager.java:629)
    at net.minecraft.server.management.PlayerManager$PlayerInstance.func_73254_a(PlayerManager.java:571)
    at net.minecraft.server.management.PlayerManager.func_72693_b(PlayerManager.java:84)
    at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:287)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:931)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
    at java.lang.Thread.run(Unknown Source)

crashes server when chunk is loaded containing forestry stairs 1127. i cant remove them or fix this without removing the mod.

Using FTB Infinity 1.11.2 Release version.

**Comment by mezz** [comment]
Thanks for the report!
Can you post the full crash report to pastebin or gist.github.com?

**Comment by CubeBix** [comment]
http://pastebin.com/iHwUcFqy

**Comment by CubeBix** [comment]
forestry version forestry_1.7.10-3.6.6.24

**Comment by mezz** [comment]
The latest Forestry 3.6 version is 3.6.12, please update and it should be fixed http://minecraft.curseforge.com/projects/forestry/files

**Comment by CubeBix** [comment]
ok i shall try manual update to see if works.

**Comment by CubeBix** [comment]
Fixed thank you very much for your help much appreciated.
