### ISSUE TITLE
Fermenter make minecraft Crash！

### ISSUE THREAD

**Issue by Antecer** [ForestryMC/ForestryMC#925]
here is crash report:
http://openeye.openmods.info/crashes/943116f1c6b3c0c6e10121f24462d35a

"
java.lang.IllegalArgumentException: Cannot create a fluidstack from a null fluid

at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:36)
at forestry.factory.tiles.TileFermenter.drain(TileFermenter.java:419)
at buildcraft.transport.pipes.PipeFluidsWood.extractFluid(PipeFluidsWood.java:113)
at buildcraft.transport.pipes.PipeFluidsWood.updateEntity(PipeFluidsWood.java:94)
at buildcraft.transport.TileGenericPipe.func_145845_h(TileGenericPipe.java:388)
at buildcraft.transport.TileGenericPipeCompat.func_145845_h(TileGenericPipeCompat.java:85)
at net.minecraft.world.World.func_72939_s(World.java:1939)
at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2006)
at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
at net.minecraft.client.main.Main.main(SourceFile:148)
at sun.reflect.NativeMethodAccessorImpl.invoke0(-2)
at sun.reflect.NativeMethodAccessorImpl.invoke(-1)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(-1)
at java.lang.reflect.Method.invoke(-1)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by mezz** [comment]
Thanks for the report!
Fixed in the latest unstable build.

**Comment by Antecer** [comment]
My server is constantly restart, please as soon as possible.

**Comment by XFactHD** [comment]
@Antecer it's already fixed, just download the latest unstable build.

**Comment by Antecer** [comment]
@XFactHD Thanks,i'll try it.
