### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by Ghostlyr** [ForestryMC/ForestryMC#941]
Hello. Sometimes i get this error in my log, but i dont know after what action.
Forestry 3.6.12.3 (without any addons)
Forge 10.13.4.1492

``` java.lang.NullPointerException
    at forestry.factory.recipes.RecipeMemory$Recipe.access$000(RecipeMemory.java:205)
    at forestry.factory.recipes.RecipeMemory.getRecipeMatrix(RecipeMemory.java:129)
    at forestry.factory.gadgets.TileWorktable.chooseRecipe(TileWorktable.java:119)
    at forestry.factory.gui.ContainerWorktable.handleSelectionChange(ContainerWorktable.java:121)
    at forestry.core.network.PacketHandler.onGuiChange(PacketHandler.java:199)
    at forestry.core.network.PacketHandler.onPacketData(PacketHandler.java:135)
    at forestry.core.network.PacketHandler.onPacket(PacketHandler.java:59)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_90_PacketHandler_onPacket_ServerCustomPacketEvent.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
    at cpw.mods.fml.common.network.FMLEventChannel.fireRead(FMLEventChannel.java:103)
    at cpw.mods.fml.common.network.NetworkEventFiringHandler.channelRead0(NetworkEventFiringHandler.java:30)
    at cpw.mods.fml.common.network.NetworkEventFiringHandler.channelRead0(NetworkEventFiringHandler.java:18)
    at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98)
    at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337)
    at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785)
    at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169)
    at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244)
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:991)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by Parker8283** [comment]
Could you please provide a link to a [pastebin](pastebin.com) of your full crash report? It has a lot more needed information.

**Comment by mezz** [comment]
@Ghostlyr ?

**Comment by Ghostlyr** [comment]
Oh, sorry, i have not a full crash report, It on appears only on server log. Now error is not observed and i cannot reproduce it.

**Comment by mezz** [comment]
The server log would be helpful if you still have it, https://gist.github.com/ allows large files.

**Comment by Ghostlyr** [comment]
Well, if the problem reiterated i send full log file. Old log is already lost, unfortunately =(

**Comment by mezz** [comment]
Ok thanks! I'll close this, please open a new issue if you have the problem again.
