### ISSUE TITLE
crash when GregTech bees are placed into beealyzer

### ISSUE THREAD

**Issue by Ujinok** [ForestryMC/ForestryMC#963]
crash when GT bees are placed into beealyzer. 
Forestry 4.2.0.823 / 4.1.1.46 
GT unofficial 5.09.11 
Forge 10.13.4.1564 /  10.13.4.1492

Time: 14.11.15 15:55
 Description: Rendering screen
 java.lang.NullPointerException: Rendering screen
 at forestry.core.genetics.Genome.getActiveAllele(Genome.java:185)
 at forestry.core.gui.GuiAlyzer.drawChromosomeRow(GuiAlyzer.java:102)
 at forestry.apiculture.gui.GuiBeealyzer.drawAnalyticsPage1(GuiBeealyzer.java:136)
 at forestry.apiculture.gui.GuiBeealyzer.func_146976_a(GuiBeealyzer.java:79)
 at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:7
 at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1357)
 at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
 at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:89
 at net.minecraft.client.main.Main.main(SourceFile:14
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
 at java.lang.reflect.Method.invoke(Unknown Source)
 at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
 at net.minecraft.launchwrapper.Launch.main(Launch.java:2
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
 at java.lang.reflect.Method.invoke(Unknown Source)
 at net.launcher.components.Game$5.run(Game.java:262)
 at java.lang.Thread.run(Unknown Source)

**Comment by mezz** [comment]
Thanks for the report!
I'm pretty sure this is a GT5 issue, I reported it here: https://github.com/Blood-Asp/GT5-Unofficial/issues/319

**Comment by Ujinok** [comment]
It's like ping-pong))
BloodAsp said: "There is only forestry in the stacktrace. So go to them first"
http://forum.industrial-craft.net/index.php?page=Thread&threadID=11488&pageNo=148&s=2a3331e8c661b8e0a10d87753c3e7ed6c3789d87
Well, i'll try again)

2015-11-15 2:31 GMT+02:00, James Mitchell notifications@github.com:

**Comment by mezz** [comment]
That's a fair response. You did go to me, but you didn't mention it.

Forestry bees and Magic Bees bees are working fine, but the GT bees are returning null there for some reason. I assume there is a mistake in the way they are created.

Anyway, it has been reported to their Github so let's keep conversation there.
