### ISSUE TITLE
Broken Oredictionary Registration (as reported by FML)

### ISSUE THREAD

**Issue by Morketh** [ForestryMC/ForestryMC#973]
As per the instruction in the Console output i am reporting this to you guys. hope this can be addressed.

```
[12:43:29] [Server thread/WARN] [FML/Forestry]: ****************************************
[12:43:29] [Server thread/WARN] [FML/Forestry]: * A broken ore dictionary registration with name cropCherry has occurred. It adds an item (type: class forestry.core.items.ItemFruit) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
TO USERS: YES this is a BUG in the mod Forestry for Minecraft report it to them!
[12:43:29] [Server thread/WARN] [FML/Forestry]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:534)
[12:43:29] [Server thread/WARN] [FML/Forestry]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:501)
[12:43:29] [Server thread/WARN] [FML/Forestry]: *  at forestry.core.items.ItemFruit.registerOreDictionary(ItemFruit.java:73)
[12:43:29] [Server thread/WARN] [FML/Forestry]: *  at forestry.core.items.ItemFruit.<init>(ItemFruit.java:68)
[12:43:29] [Server thread/WARN] [FML/Forestry]: *  at forestry.plugins.PluginCore.registerItems(PluginCore.java:286)
[12:43:29] [Server thread/WARN] [FML/Forestry]: *  at forestry.plugins.PluginManager.runPreInit(PluginManager.java:267)...
[12:43:29] [Server thread/WARN] [FML/Forestry]: ****************************************
[12:43:29] [Server thread/WARN] [FML/Forestry]: ****************************************
[12:43:29] [Server thread/WARN] [FML/Forestry]: * A broken ore dictionary registration with name cropWalnut has occurred. It adds an item (type: class forestry.core.items.ItemFruit) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
TO USERS: YES this is a BUG in the mod Forestry for Minecraft report it to them!
[12:43:29] [Server thread/WARN] [FML/Forestry]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:534)
[12:43:29] [Server thread/WARN] [FML/Forestry]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:501)
[12:43:29] [Server thread/WARN] [FML/Forestry]: *  at forestry.core.items.ItemFruit.registerOreDictionary(ItemFruit.java:73)
[12:43:29] [Server thread/WARN] [FML/Forestry]: *  at forestry.core.items.ItemFruit.<init>(ItemFruit.java:68)
[12:43:29] [Server thread/WARN] [FML/Forestry]: *  at forestry.plugins.PluginCore.registerItems(PluginCore.java:286)
[12:43:29] [Server thread/WARN] [FML/Forestry]: *  at forestry.plugins.PluginManager.runPreInit(PluginManager.java:267)...
[12:43:29] [Server thread/WARN] [FML/Forestry]: ****************************************
[12:43:29] [Server thread/WARN] [FML/Forestry]: ****************************************
[12:43:29] [Server thread/WARN] [FML/Forestry]: * A broken ore dictionary registration with name cropChestnut has occurred. It adds an item (type: class forestry.core.items.ItemFruit) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
TO USERS: YES this is a BUG in the mod Forestry for Minecraft report it to them!
[12:43:29] [Server thread/WARN] [FML/Forestry]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:534)
[12:43:29] [Server thread/WARN] [FML/Forestry]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:501)
[12:43:29] [Server thread/WARN] [FML/Forestry]: *  at forestry.core.items.ItemFruit.registerOreDictionary(ItemFruit.java:73)
[12:43:29] [Server thread/WARN] [FML/Forestry]: *  at forestry.core.items.ItemFruit.<init>(ItemFruit.java:68)
[12:43:29] [Server thread/WARN] [FML/Forestry]: *  at forestry.plugins.PluginCore.registerItems(PluginCore.java:286)
[12:43:29] [Server thread/WARN] [FML/Forestry]: *  at forestry.plugins.PluginManager.runPreInit(PluginManager.java:267)...
[12:43:29] [Server thread/WARN] [FML/Forestry]: ****************************************
[12:43:29] [Server thread/WARN] [FML/Forestry]: ****************************************
[12:43:29] [Server thread/WARN] [FML/Forestry]: * A broken ore dictionary registration with name cropLemon has occurred. It adds an item (type: class forestry.core.items.ItemFruit) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
TO USERS: YES this is a BUG in the mod Forestry for Minecraft report it to them!
[12:43:29] [Server thread/WARN] [FML/Forestry]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:534)
[12:43:29] [Server thread/WARN] [FML/Forestry]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:501)
[12:43:29] [Server thread/WARN] [FML/Forestry]: *  at forestry.core.items.ItemFruit.registerOreDictionary(ItemFruit.java:73)
[12:43:29] [Server thread/WARN] [FML/Forestry]: *  at forestry.core.items.ItemFruit.<init>(ItemFruit.java:68)
[12:43:29] [Server thread/WARN] [FML/Forestry]: *  at forestry.plugins.PluginCore.registerItems(PluginCore.java:286)
[12:43:29] [Server thread/WARN] [FML/Forestry]: *  at forestry.plugins.PluginManager.runPreInit(PluginManager.java:267)...
[12:43:29] [Server thread/WARN] [FML/Forestry]: ****************************************
[12:43:29] [Server thread/WARN] [FML/Forestry]: ****************************************
[12:43:29] [Server thread/WARN] [FML/Forestry]: * A broken ore dictionary registration with name cropPlum has occurred. It adds an item (type: class forestry.core.items.ItemFruit) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
TO USERS: YES this is a BUG in the mod Forestry for Minecraft report it to them!
[12:43:29] [Server thread/WARN] [FML/Forestry]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:534)
[12:43:29] [Server thread/WARN] [FML/Forestry]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:501)
[12:43:29] [Server thread/WARN] [FML/Forestry]: *  at forestry.core.items.ItemFruit.registerOreDictionary(ItemFruit.java:73)
[12:43:29] [Server thread/WARN] [FML/Forestry]: *  at forestry.core.items.ItemFruit.<init>(ItemFruit.java:68)
[12:43:29] [Server thread/WARN] [FML/Forestry]: *  at forestry.plugins.PluginCore.registerItems(PluginCore.java:286)
[12:43:29] [Server thread/WARN] [FML/Forestry]: *  at forestry.plugins.PluginManager.runPreInit(PluginManager.java:267)...
[12:43:29] [Server thread/WARN] [FML/Forestry]: ****************************************
[12:43:29] [Server thread/WARN] [FML/Forestry]: ****************************************
[12:43:29] [Server thread/WARN] [FML/Forestry]: * A broken ore dictionary registration with name cropDate has occurred. It adds an item (type: class forestry.core.items.ItemFruit) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
TO USERS: YES this is a BUG in the mod Forestry for Minecraft report it to them!
[12:43:29] [Server thread/WARN] [FML/Forestry]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:534)
[12:43:29] [Server thread/WARN] [FML/Forestry]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:501)
[12:43:29] [Server thread/WARN] [FML/Forestry]: *  at forestry.core.items.ItemFruit.registerOreDictionary(ItemFruit.java:73)
[12:43:29] [Server thread/WARN] [FML/Forestry]: *  at forestry.core.items.ItemFruit.<init>(ItemFruit.java:68)
[12:43:29] [Server thread/WARN] [FML/Forestry]: *  at forestry.plugins.PluginCore.registerItems(PluginCore.java:286)
[12:43:29] [Server thread/WARN] [FML/Forestry]: *  at forestry.plugins.PluginManager.runPreInit(PluginManager.java:267)...
[12:43:29] [Server thread/WARN] [FML/Forestry]: ****************************************
[12:43:29] [Server thread/WARN] [FML/Forestry]: ****************************************
[12:43:29] [Server thread/WARN] [FML/Forestry]: * A broken ore dictionary registration with name cropPapaya has occurred. It adds an item (type: class forestry.core.items.ItemFruit) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
TO USERS: YES this is a BUG in the mod Forestry for Minecraft report it to them!
[12:43:29] [Server thread/WARN] [FML/Forestry]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:534)
[12:43:29] [Server thread/WARN] [FML/Forestry]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:501)
[12:43:29] [Server thread/WARN] [FML/Forestry]: *  at forestry.core.items.ItemFruit.registerOreDictionary(ItemFruit.java:73)
[12:43:29] [Server thread/WARN] [FML/Forestry]: *  at forestry.core.items.ItemFruit.<init>(ItemFruit.java:68)
[12:43:29] [Server thread/WARN] [FML/Forestry]: *  at forestry.plugins.PluginCore.registerItems(PluginCore.java:286)
[12:43:29] [Server thread/WARN] [FML/Forestry]: *  at forestry.plugins.PluginManager.runPreInit(PluginManager.java:267)...
[12:43:29] [Server thread/WARN] [FML/Forestry]: ****************************************
```

**Comment by mezz** [comment]
Thanks for the report!
This has already been fixed in the latest versions.

**Comment by Morketh** [comment]
wonderful looks ill be updating thank you @mezz
